const keys = [
  'pageTitle',
  'metaDescription',
  'brandHomeLabel',
  'navLabel',
  'navProjects',
  'navNow',
  'navAbout',
  'navContact',
  'headline',
  'intro',
  'privacyNote',
  'reasonLabel',
  'chooseOne',
  'reasonNotEnough',
  'reasonBlockedIncorrectly',
  'reasonLayoutLanguage',
  'reasonConfiguration',
  'reasonBugSlowdown',
  'reasonNoLongerNeeded',
  'reasonPrivacyPermissions',
  'reasonOther',
  'detailsLabel',
  'detailsHelp',
  'featureLabel',
  'featureHelp',
  'contactLabel',
  'contactHelp',
  'submit',
  'status',
  'footerSource'
];

function makeCopy(values) {
  return Object.fromEntries(keys.map((key, index) => [key, values[index]]));
}

export const LOCALE_COPY_GROUP_8 = {
  hu: makeCopy([
    'Visszajelzés a YouTube Mix Blockerről',
    'Opcionális visszajelzés a YouTube Mix Blocker eltávolítása után.',
    'Oleksandr Molodchyk kezdőlapja',
    'Fő navigáció',
    'Projektek',
    'Most',
    'Névjegy',
    'Kapcsolat',
    'Segíts javítani a bővítményt',
    'Ha a YouTube Mix Blocker nem váltotta be a várakozásaidat, egy rövid megjegyzés is elég. Ez az űrlap opcionális, és nem kér elérhetőséget.',
    'A bővítmény eltávolítás után csak általános forrás-, verzió- és böngészőnyelv-paraméterekkel nyitja meg ezt az oldalt. Ne adj meg személyes adatot, hacsak nem szándékosan szeretnéd megosztani.',
    'Miért távolítottad el?',
    'Válassz egyet',
    'Nem blokkolt elég YouTube Mixet',
    'Valamit tévesen blokkolt vagy módosított',
    'Nem működött a YouTube-elrendezésemmel vagy nyelvemmel',
    'Zavaros volt beállítani',
    'Hibát, lassulást vagy kompatibilitási problémát okozott',
    'Már nincs rá szükségem',
    'Adatvédelmi vagy engedélyezési aggály',
    'Egyéb',
    'Mi történt, vagy mit vártál volna helyette?',
    'Opcionális. Egy-két mondat elég.',
    'Milyen funkció miatt próbálnád ki újra?',
    'Opcionális.',
    'Válaszcím',
    'Opcionális. Csak akkor add meg, ha választ szeretnél.',
    'Visszajelzés küldése',
    'A visszajelzést a Formspree dolgozza fel.',
    'Forrás'
  ]),
  hy: makeCopy([
    'Կարծիք YouTube Mix Blocker-ի մասին',
    'Ընտրովի կարծիք YouTube Mix Blocker-ը հեռացնելուց հետո։',
    'Oleksandr Molodchyk-ի գլխավոր էջ',
    'Հիմնական նավարկում',
    'Նախագծեր',
    'Հիմա',
    'Մասին',
    'Կապ',
    'Օգնեք բարելավել ընդլայնումը',
    'Եթե YouTube Mix Blocker-ը չարդարացրեց ձեր սպասելիքները, կարճ նշումը բավական է։ Այս ձևը ընտրովի է և չի պահանջում կոնտակտային տվյալներ։',
    'Ընդլայնումը հեռացնելուց հետո այս էջը բացվում է միայն աղբյուրի, տարբերակի և դիտարկչի լեզվի ընդհանուր պարամետրերով։ Մի ներառեք անձնական տվյալներ, եթե հատուկ չեք ուզում դրանք կիսել։',
    'Ինչու՞ հեռացրեցիք։',
    'Ընտրեք մեկը',
    'Բավականաչափ YouTube Mixes չէր արգելափակում',
    'Սխալմամբ ինչ-որ բան արգելափակում կամ փոխում էր',
    'Չէր աշխատում իմ YouTube դասավորության կամ լեզվի հետ',
    'Կարգավորելը շփոթեցնող էր',
    'Առաջացնում էր սխալ, դանդաղեցում կամ համատեղելիության խնդիր',
    'Այլևս պետք չէ',
    'Գաղտնիության կամ թույլտվությունների մտահոգություն',
    'Այլ',
    'Ի՞նչ տեղի ունեցավ կամ ի՞նչ էիք սպասում փոխարենը։',
    'Ընտրովի։ Մեկ-երկու նախադասությունը բավական է։',
    'Ո՞ր գործառույթը կստիպեր նորից փորձել։',
    'Ընտրովի։',
    'Պատասխանի հասցե',
    'Ընտրովի։ Նշեք միայն եթե պատասխան եք ուզում։',
    'Ուղարկել կարծիք',
    'Կարծիքը մշակվում է Formspree-ի միջոցով։',
    'Աղբյուր'
  ]),
  ka: makeCopy([
    'YouTube Mix Blocker-ის გამოხმაურება',
    'სურვილისამებრ გამოხმაურება YouTube Mix Blocker-ის წაშლის შემდეგ.',
    'Oleksandr Molodchyk-ის მთავარი გვერდი',
    'მთავარი ნავიგაცია',
    'პროექტები',
    'ახლა',
    'შესახებ',
    'კონტაქტი',
    'დაგვეხმარეთ გაფართოების გაუმჯობესებაში',
    'თუ YouTube Mix Blocker-მა მოლოდინი ვერ გაამართლა, მოკლე ჩანაწერიც საკმარისია. ეს ფორმა სურვილისამებრია და საკონტაქტო ინფორმაციას არ ითხოვს.',
    'გაფართოება წაშლის შემდეგ ამ გვერდს ხსნის მხოლოდ წყაროს, ვერსიისა და ბრაუზერის ენის ზოგადი პარამეტრებით. პირადი მონაცემები არ შეიყვანოთ, თუ მათი განზრახ გაზიარება არ გსურთ.',
    'რატომ წაშალეთ?',
    'აირჩიეთ ერთი',
    'საკმარის YouTube Mixes-ს არ ბლოკავდა',
    'რაღაცას არასწორად ბლოკავდა ან ცვლიდა',
    'ჩემს YouTube განლაგებაზე ან ენაზე არ მუშაობდა',
    'მისი კონფიგურაცია დამაბნეველი იყო',
    'იწვევდა შეცდომას, შენელებას ან თავსებადობის პრობლემას',
    'აღარ მჭირდება',
    'კონფიდენციალურობის ან ნებართვების შეშფოთება',
    'სხვა',
    'რა მოხდა ან რას ელოდით ამის ნაცვლად?',
    'სურვილისამებრ. ერთი-ორი წინადადება საკმარისია.',
    'რომელი ფუნქცია გაიძულებდათ ხელახლა გეცადათ?',
    'სურვილისამებრ.',
    'პასუხის მისამართი',
    'სურვილისამებრ. მიუთითეთ მხოლოდ თუ პასუხი გსურთ.',
    'გამოხმაურების გაგზავნა',
    'გამოხმაურებას ამუშავებს Formspree.',
    'წყარო'
  ]),
  kn: makeCopy([
    'YouTube Mix Blocker ಪ್ರತಿಕ್ರಿಯೆ',
    'YouTube Mix Blocker ಅನ್ನು ಅನ್‌ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿದ ನಂತರದ ಐಚ್ಛಿಕ ಪ್ರತಿಕ್ರಿಯೆ.',
    'Oleksandr Molodchyk ಮುಖಪುಟ',
    'ಮುಖ್ಯ ನ್ಯಾವಿಗೇಶನ್',
    'ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು',
    'ಈಗ',
    'ಬಗ್ಗೆ',
    'ಸಂಪರ್ಕ',
    'ವಿಸ್ತರಣೆಯನ್ನು ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡಿ',
    'YouTube Mix Blocker ನಿಮ್ಮ ನಿರೀಕ್ಷೆ ತಲುಪದಿದ್ದರೆ, ಚಿಕ್ಕ ಟಿಪ್ಪಣಿ ಸಾಕು. ಈ ಫಾರ್ಮ್ ಐಚ್ಛಿಕವಾಗಿದ್ದು ಸಂಪರ್ಕ ಮಾಹಿತಿಯನ್ನು ಬೇಡುವುದಿಲ್ಲ.',
    'ವಿಸ್ತರಣೆ ಅನ್‌ಇನ್‌ಸ್ಟಾಲ್ ಆದ ನಂತರ ಈ ಪುಟವನ್ನು ಮೂಲ, ಆವೃತ್ತಿ ಮತ್ತು ಬ್ರೌಸರ್ ಭಾಷೆಯ ಸಾಮಾನ್ಯ ಪರಾಮೀಟರ್‌ಗಳೊಂದಿಗೆ ಮಾತ್ರ ತೆರೆಯುತ್ತದೆ. ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಹಂಚಿಕೊಳ್ಳಲು ಬಯಸದೇ ಇದ್ದರೆ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಸೇರಿಸಬೇಡಿ.',
    'ನೀವು ಏಕೆ ಅನ್‌ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿದ್ದೀರಿ?',
    'ಒಂದನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'ಸಾಕಷ್ಟು YouTube Mixes ಅನ್ನು ತಡೆಗಟ್ಟಲಿಲ್ಲ',
    'ಏನನ್ನಾದರೂ ತಪ್ಪಾಗಿ ತಡೆಗಟ್ಟಿತು ಅಥವಾ ಬದಲಾಯಿಸಿತು',
    'ನನ್ನ YouTube ವಿನ್ಯಾಸ ಅಥವಾ ಭಾಷೆಯಲ್ಲಿ ಕೆಲಸ ಮಾಡಲಿಲ್ಲ',
    'ಕಾನ್ಫಿಗರ್ ಮಾಡುವುದು ಗೊಂದಲಕರವಾಗಿತ್ತು',
    'ದೋಷ, ನಿಧಾನಗತಿ ಅಥವಾ ಹೊಂದಾಣಿಕೆ ಸಮಸ್ಯೆ ಉಂಟುಮಾಡಿತು',
    'ಇದು ಇನ್ನು ನನಗೆ ಬೇಕಿಲ್ಲ',
    'ಗೌಪ್ಯತೆ ಅಥವಾ ಅನುಮತಿ ಕುರಿತು ಕಳವಳ',
    'ಇತರೆ',
    'ಏನು ಸಂಭವಿಸಿತು ಅಥವಾ ಬದಲು ನೀವು ಏನು ನಿರೀಕ್ಷಿಸಿದ್ದೀರಿ?',
    'ಐಚ್ಛಿಕ. ಒಂದು ಅಥವಾ ಎರಡು ವಾಕ್ಯ ಸಾಕು.',
    'ಯಾವ ವೈಶಿಷ್ಟ್ಯ ಇದನ್ನು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಲು ನಿಮಗೆ ಪ್ರೇರಣೆ ನೀಡುತ್ತದೆ?',
    'ಐಚ್ಛಿಕ.',
    'ಉತ್ತರ ವಿಳಾಸ',
    'ಐಚ್ಛಿಕ. ಉತ್ತರ ಬೇಕಿದ್ದರೆ ಮಾತ್ರ ಸೇರಿಸಿ.',
    'ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ',
    'ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು Formspree ಸಂಸ್ಕರಿಸುತ್ತದೆ.',
    'ಮೂಲ'
  ]),
  lt: makeCopy([
    'Atsiliepimai apie YouTube Mix Blocker',
    'Pasirenkamas atsiliepimas pašalinus YouTube Mix Blocker.',
    'Oleksandr Molodchyk pradžia',
    'Pagrindinė navigacija',
    'Projektai',
    'Dabar',
    'Apie',
    'Kontaktai',
    'Padėkite patobulinti plėtinį',
    'Jei YouTube Mix Blocker nepateisino lūkesčių, pakanka trumpos pastabos. Ši forma neprivaloma ir nereikalauja kontaktinės informacijos.',
    'Pašalinus plėtinį, šis puslapis atidaromas tik su bendrais šaltinio, versijos ir naršyklės kalbos parametrais. Neįtraukite asmens duomenų, nebent sąmoningai norite jais pasidalyti.',
    'Kodėl pašalinote?',
    'Pasirinkite vieną',
    'Jis neužblokavo pakankamai YouTube Mixes',
    'Jis ką nors neteisingai užblokavo arba pakeitė',
    'Jis neveikė su mano YouTube išdėstymu ar kalba',
    'Jį buvo painu konfigūruoti',
    'Jis sukėlė klaidą, sulėtėjimą ar suderinamumo problemą',
    'Man jo nebereikia',
    'Privatumo arba leidimų susirūpinimas',
    'Kita',
    'Kas nutiko arba ko tikėjotės vietoj to?',
    'Neprivaloma. Pakanka vieno ar dviejų sakinių.',
    'Kokia funkcija paskatintų išbandyti dar kartą?',
    'Neprivaloma.',
    'Atsakymo adresas',
    'Neprivaloma. Įrašykite tik jei norite atsakymo.',
    'Siųsti atsiliepimą',
    'Atsiliepimą apdoroja Formspree.',
    'Šaltinis'
  ]),
  lv: makeCopy([
    'Atsauksmes par YouTube Mix Blocker',
    'Neobligāta atsauksme pēc YouTube Mix Blocker atinstalēšanas.',
    'Oleksandr Molodchyk sākumlapa',
    'Galvenā navigācija',
    'Projekti',
    'Tagad',
    'Par',
    'Kontakti',
    'Palīdziet uzlabot paplašinājumu',
    'Ja YouTube Mix Blocker neatbilda gaidītajam, pietiek ar īsu piezīmi. Šī veidlapa ir neobligāta un neprasa kontaktinformāciju.',
    'Pēc atinstalēšanas paplašinājums atver šo lapu tikai ar vispārīgiem avota, versijas un pārlūka valodas parametriem. Neiekļaujiet personas datus, ja vien apzināti nevēlaties tos kopīgot.',
    'Kāpēc atinstalējāt?',
    'Izvēlieties vienu',
    'Tas nebloķēja pietiekami daudz YouTube Mixes',
    'Tas kaut ko bloķēja vai mainīja nepareizi',
    'Tas nedarbojās ar manu YouTube izkārtojumu vai valodu',
    'To bija mulsinoši konfigurēt',
    'Tas izraisīja kļūdu, palēninājumu vai saderības problēmu',
    'Man tas vairs nav vajadzīgs',
    'Bažas par privātumu vai atļaujām',
    'Cits',
    'Kas notika vai ko gaidījāt tā vietā?',
    'Neobligāti. Pietiek ar vienu vai diviem teikumiem.',
    'Kāda funkcija liktu jums to izmēģināt vēlreiz?',
    'Neobligāti.',
    'Atbildes adrese',
    'Neobligāti. Norādiet tikai tad, ja vēlaties atbildi.',
    'Sūtīt atsauksmi',
    'Atsauksmi apstrādā Formspree.',
    'Avots'
  ]),
  mk: makeCopy([
    'Повратни информации за YouTube Mix Blocker',
    'Изборни повратни информации по деинсталирање на YouTube Mix Blocker.',
    'Почетна страница на Oleksandr Molodchyk',
    'Главна навигација',
    'Проекти',
    'Сега',
    'За',
    'Контакт',
    'Помогнете да се подобри проширувањето',
    'Ако YouTube Mix Blocker не ги исполни очекувањата, доволна е кратка белешка. Овој формулар е изборен и не бара контакт-информации.',
    'Проширувањето ја отвора оваа страница по деинсталирање само со општи параметри за извор, верзија и јазик на прелистувачот. Не внесувајте лични податоци освен ако намерно сакате да ги споделите.',
    'Зошто го деинсталиравте?',
    'Изберете едно',
    'Не блокираше доволно YouTube Mixes',
    'Погрешно блокираше или промени нешто',
    'Не работеше со мојот YouTube распоред или јазик',
    'Беше збунувачко за конфигурирање',
    'Предизвика грешка, забавување или проблем со компатибилност',
    'Повеќе не ми треба',
    'Загриженост за приватност или дозволи',
    'Друго',
    'Што се случи или што очекувавте наместо тоа?',
    'Изборно. Доволни се една или две реченици.',
    'Која функција би ве натерала повторно да го пробате?',
    'Изборно.',
    'Адреса за одговор',
    'Изборно. Внесете само ако сакате одговор.',
    'Испрати повратни информации',
    'Повратните информации ги обработува Formspree.',
    'Извор'
  ]),
  ml: makeCopy([
    'YouTube Mix Blocker ഫീഡ്‌ബാക്ക്',
    'YouTube Mix Blocker അൺഇൻസ്റ്റാൾ ചെയ്തതിന് ശേഷമുള്ള ഐച്ഛിക ഫീഡ്‌ബാക്ക്.',
    'Oleksandr Molodchyk ഹോം',
    'പ്രധാന നാവിഗേഷൻ',
    'പ്രോജക്റ്റുകൾ',
    'ഇപ്പോൾ',
    'കുറിച്ച്',
    'ബന്ധപ്പെടുക',
    'എക്സ്റ്റൻഷൻ മെച്ചപ്പെടുത്താൻ സഹായിക്കുക',
    'YouTube Mix Blocker പ്രതീക്ഷിച്ചതുപോലെ പ്രവർത്തിച്ചില്ലെങ്കിൽ, ഒരു ചെറിയ കുറിപ്പ് മതി. ഈ ഫോം ഐച്ഛികമാണ്, ബന്ധപ്പെടാനുള്ള വിവരം ആവശ്യമില്ല.',
    'എക്സ്റ്റൻഷൻ അൺഇൻസ്റ്റാൾ ചെയ്തതിന് ശേഷം ഈ പേജ് പൊതുവായ source, version, browser-language പരാമീറ്ററുകളോടെ മാത്രമാണ് തുറക്കുന്നത്. വ്യക്തിപരമായ ഡാറ്റ മനപ്പൂർവ്വം പങ്കിടാൻ ആഗ്രഹിക്കുന്നില്ലെങ്കിൽ ഉൾപ്പെടുത്തരുത്.',
    'എന്തുകൊണ്ടാണ് അൺഇൻസ്റ്റാൾ ചെയ്തത്?',
    'ഒന്ന് തിരഞ്ഞെടുക്കുക',
    'മതിയായ YouTube Mixes ബ്ലോക്ക് ചെയ്തില്ല',
    'എന്തെങ്കിലും തെറ്റായി ബ്ലോക്ക് ചെയ്യുകയോ മാറ്റുകയോ ചെയ്തു',
    'എന്റെ YouTube ലേഔട്ടിലോ ഭാഷയിലോ പ്രവർത്തിച്ചില്ല',
    'കോൺഫിഗർ ചെയ്യുന്നത് ആശയക്കുഴപ്പമായിരുന്നു',
    'ബഗ്, മന്ദഗതി, അല്ലെങ്കിൽ അനുയോജ്യത പ്രശ്നം ഉണ്ടാക്കി',
    'ഇനി ആവശ്യമില്ല',
    'സ്വകാര്യതയോ അനുമതികളോ സംബന്ധിച്ച ആശങ്ക',
    'മറ്റുള്ളവ',
    'എന്താണ് സംഭവിച്ചത്, അല്ലെങ്കിൽ പകരം എന്താണ് പ്രതീക്ഷിച്ചത്?',
    'ഐച്ഛികം. ഒരു രണ്ടുവാക്യം മതി.',
    'ഏത് സവിശേഷതയാണെങ്കിൽ വീണ്ടും പരീക്ഷിക്കും?',
    'ഐച്ഛികം.',
    'മറുപടി വിലാസം',
    'ഐച്ഛികം. മറുപടി വേണമെങ്കിൽ മാത്രം ചേർക്കുക.',
    'ഫീഡ്‌ബാക്ക് അയയ്ക്കുക',
    'ഫീഡ്‌ബാക്ക് Formspree പ്രോസസ് ചെയ്യുന്നു.',
    'ഉറവിടം'
  ]),
  mr: makeCopy([
    'YouTube Mix Blocker अभिप्राय',
    'YouTube Mix Blocker अनइन्स्टॉल केल्यानंतर ऐच्छिक अभिप्राय.',
    'Oleksandr Molodchyk मुख्यपृष्ठ',
    'मुख्य नेव्हिगेशन',
    'प्रकल्प',
    'आता',
    'बद्दल',
    'संपर्क',
    'एक्स्टेंशन सुधारण्यास मदत करा',
    'YouTube Mix Blocker अपेक्षेप्रमाणे नसेल तर एक छोटी नोंद पुरेशी आहे. हा फॉर्म ऐच्छिक आहे आणि संपर्क माहिती मागत नाही.',
    'एक्स्टेंशन अनइन्स्टॉल झाल्यानंतर हे पृष्ठ फक्त सामान्य source, version आणि browser-language पॅरामीटर्ससह उघडते. तुम्हाला जाणीवपूर्वक शेअर करायचे नसल्यास वैयक्तिक माहिती देऊ नका.',
    'तुम्ही ते का अनइन्स्टॉल केले?',
    'एक निवडा',
    'पुरेसे YouTube Mixes ब्लॉक केले नाहीत',
    'काहीतरी चुकीचे ब्लॉक केले किंवा बदलले',
    'माझ्या YouTube लेआउट किंवा भाषेत काम केले नाही',
    'कॉन्फिगर करणे गोंधळात टाकणारे होते',
    'बग, मंदी किंवा सुसंगतता समस्या निर्माण झाली',
    'आता मला त्याची गरज नाही',
    'गोपनीयता किंवा परवानग्यांबद्दल चिंता',
    'इतर',
    'काय झाले किंवा त्याऐवजी तुम्हाला काय अपेक्षित होते?',
    'ऐच्छिक. एक-दोन वाक्ये पुरेशी आहेत.',
    'कोणते वैशिष्ट्य तुम्हाला पुन्हा प्रयत्न करायला लावेल?',
    'ऐच्छिक.',
    'उत्तराचा पत्ता',
    'ऐच्छिक. उत्तर हवे असल्यासच जोडा.',
    'अभिप्राय पाठवा',
    'अभिप्राय Formspree द्वारे प्रक्रिया केला जातो.',
    'स्रोत'
  ]),
  ne: makeCopy([
    'YouTube Mix Blocker प्रतिक्रिया',
    'YouTube Mix Blocker अनइन्स्टल गरेपछि वैकल्पिक प्रतिक्रिया।',
    'Oleksandr Molodchyk गृहपृष्ठ',
    'मुख्य नेभिगेसन',
    'परियोजनाहरू',
    'अहिले',
    'बारेमा',
    'सम्पर्क',
    'एक्सटेन्सन सुधार गर्न मद्दत गर्नुहोस्',
    'YouTube Mix Blocker ले अपेक्षा पूरा गरेन भने छोटो नोट पर्याप्त हुन्छ। यो फारम वैकल्पिक हो र सम्पर्क जानकारी आवश्यक पर्दैन।',
    'एक्सटेन्सन अनइन्स्टल भएपछि यो पृष्ठ स्रोत, संस्करण र ब्राउजर भाषाका सामान्य प्यारामिटरहरू मात्र लिएर खुल्छ। जानाजानी साझा गर्न नचाहनुहुन्छ भने व्यक्तिगत डेटा नराख्नुहोस्।',
    'किन अनइन्स्टल गर्नुभयो?',
    'एउटा छान्नुहोस्',
    'यसले पर्याप्त YouTube Mixes ब्लक गरेन',
    'केही गलत रूपमा ब्लक वा परिवर्तन गर्‍यो',
    'मेरो YouTube लेआउट वा भाषामा काम गरेन',
    'कन्फिगर गर्न अलमलिलो थियो',
    'बग, ढिलाइ वा अनुकूलता समस्या ल्यायो',
    'अब मलाई यसको आवश्यकता छैन',
    'गोपनीयता वा अनुमति सम्बन्धी चिन्ता',
    'अन्य',
    'के भयो वा त्यसको सट्टा के अपेक्षा गर्नुभएको थियो?',
    'वैकल्पिक। एक-दुई वाक्य पर्याप्त हुन्छ।',
    'कुन सुविधाले तपाईंलाई फेरि प्रयास गर्न लगाउँथ्यो?',
    'वैकल्पिक।',
    'जवाफ ठेगाना',
    'वैकल्पिक। जवाफ चाहनुहुन्छ भने मात्र राख्नुहोस्।',
    'प्रतिक्रिया पठाउनुहोस्',
    'प्रतिक्रिया Formspree द्वारा प्रशोधन गरिन्छ।',
    'स्रोत'
  ]),
  no: makeCopy([
    'Tilbakemelding for YouTube Mix Blocker',
    'Valgfri tilbakemelding etter avinstallering av YouTube Mix Blocker.',
    'Oleksandr Molodchyk startside',
    'Hovednavigasjon',
    'Prosjekter',
    'Nå',
    'Om',
    'Kontakt',
    'Hjelp med å forbedre utvidelsen',
    'Hvis YouTube Mix Blocker ikke traff forventningene, holder det med en kort merknad. Dette skjemaet er valgfritt og krever ikke kontaktinformasjon.',
    'Utvidelsen åpner denne siden etter avinstallering bare med generelle parametere for kilde, versjon og nettleserspråk. Ikke inkluder personopplysninger med mindre du bevisst vil dele dem.',
    'Hvorfor avinstallerte du?',
    'Velg én',
    'Den blokkerte ikke nok YouTube Mixes',
    'Den blokkerte eller endret noe feil',
    'Den fungerte ikke med YouTube-oppsettet eller språket mitt',
    'Den var forvirrende å konfigurere',
    'Den forårsaket en feil, treghet eller kompatibilitetsproblem',
    'Jeg trenger den ikke lenger',
    'Bekymring for personvern eller tillatelser',
    'Annet',
    'Hva skjedde, eller hva forventet du i stedet?',
    'Valgfritt. En eller to setninger er nok.',
    'Hvilken funksjon ville fått deg til å prøve den igjen?',
    'Valgfritt.',
    'Svaradresse',
    'Valgfritt. Legg den bare inn hvis du vil ha svar.',
    'Send tilbakemelding',
    'Tilbakemeldingen behandles av Formspree.',
    'Kilde'
  ])
};
