export const LOCALE_COPY_GROUP_5 = {
  "it": {
    "pageTitle": "Feedback su YouTube Mix Blocker",
    "metaDescription": "Feedback facoltativo dopo la disinstallazione di YouTube Mix Blocker.",
    "brandHomeLabel": "Home di Oleksandr Molodchyk",
    "navLabel": "Navigazione principale",
    "navProjects": "Progetti",
    "navNow": "Ora",
    "navAbout": "Informazioni",
    "navContact": "Contatto",
    "headline": "Aiuta a migliorare l'estensione",
    "intro": "Se YouTube Mix Blocker non ha soddisfatto le aspettative, basta una breve nota. Questo modulo è facoltativo e non richiede informazioni di contatto.",
    "privacyNote": "L'estensione apre questa pagina dopo la disinstallazione solo con parametri generici di origine, versione e lingua del browser. Non inserire dati personali a meno che tu voglia condividerli intenzionalmente.",
    "reasonLabel": "Perché hai disinstallato?",
    "chooseOne": "Scegli un'opzione",
    "reasonNotEnough": "Non bloccava abbastanza YouTube Mixes",
    "reasonBlockedIncorrectly": "Bloccava o modificava qualcosa in modo errato",
    "reasonLayoutLanguage": "Non funzionava con il mio layout o la mia lingua di YouTube",
    "reasonConfiguration": "Era confusa da configurare",
    "reasonBugSlowdown": "Causava bug, rallentamenti o problemi di compatibilità",
    "reasonNoLongerNeeded": "Non mi serve più",
    "reasonPrivacyPermissions": "Preoccupazione per privacy o autorizzazioni",
    "reasonOther": "Altro",
    "detailsLabel": "Che cosa è successo o che cosa ti aspettavi?",
    "detailsHelp": "Facoltativo. Bastano una o due frasi.",
    "featureLabel": "Quale funzione ti farebbe riprovare?",
    "featureHelp": "Facoltativo.",
    "contactLabel": "Indirizzo per la risposta",
    "contactHelp": "Facoltativo. Inseriscilo solo se vuoi una risposta.",
    "submit": "Invia feedback",
    "status": "Il feedback viene gestito da Formspree.",
    "footerSource": "Sorgente"
  },
  "ja": {
    "pageTitle": "YouTube Mix Blocker フィードバック",
    "metaDescription": "YouTube Mix Blocker のアンインストール後に送れる任意のフィードバックです。",
    "brandHomeLabel": "Oleksandr Molodchyk ホーム",
    "navLabel": "メインナビゲーション",
    "navProjects": "プロジェクト",
    "navNow": "現在",
    "navAbout": "概要",
    "navContact": "連絡先",
    "headline": "拡張機能の改善にご協力ください",
    "intro": "YouTube Mix Blocker が期待どおりでなかった場合は、短いメモだけでも十分です。このフォームは任意で、連絡先情報は不要です。",
    "privacyNote": "拡張機能はアンインストール後、このページを source、version、ブラウザ言語の一般的なパラメータだけで開きます。意図して共有する場合を除き、個人情報は入力しないでください。",
    "reasonLabel": "アンインストールした理由は何ですか？",
    "chooseOne": "1つ選択",
    "reasonNotEnough": "十分な数の YouTube Mix をブロックしなかった",
    "reasonBlockedIncorrectly": "何かを誤ってブロックまたは変更した",
    "reasonLayoutLanguage": "自分の YouTube レイアウトまたは言語で動作しなかった",
    "reasonConfiguration": "設定が分かりにくかった",
    "reasonBugSlowdown": "バグ、遅延、互換性の問題が発生した",
    "reasonNoLongerNeeded": "もう必要ない",
    "reasonPrivacyPermissions": "プライバシーまたは権限が気になった",
    "reasonOther": "その他",
    "detailsLabel": "何が起きましたか、または何を期待していましたか？",
    "detailsHelp": "任意です。1、2文で十分です。",
    "featureLabel": "どの機能があればもう一度試したいですか？",
    "featureHelp": "任意です。",
    "contactLabel": "返信先",
    "contactHelp": "任意です。返信を希望する場合のみ入力してください。",
    "submit": "フィードバックを送信",
    "status": "フィードバックは Formspree によって処理されます。",
    "footerSource": "ソース"
  },
  "ms": {
    "pageTitle": "Maklum balas YouTube Mix Blocker",
    "metaDescription": "Maklum balas pilihan selepas menyahpasang YouTube Mix Blocker.",
    "brandHomeLabel": "Laman utama Oleksandr Molodchyk",
    "navLabel": "Navigasi utama",
    "navProjects": "Projek",
    "navNow": "Kini",
    "navAbout": "Tentang",
    "navContact": "Hubungi",
    "headline": "Bantu perbaiki sambungan ini",
    "intro": "Jika YouTube Mix Blocker tidak menepati jangkaan, satu nota ringkas sudah memadai. Borang ini pilihan dan tidak memerlukan maklumat hubungan.",
    "privacyNote": "Sambungan membuka halaman ini selepas dinyahpasang dengan hanya parameter umum sumber, versi dan bahasa pelayar. Jangan sertakan data peribadi kecuali anda sengaja mahu berkongsinya.",
    "reasonLabel": "Mengapa anda menyahpasang?",
    "chooseOne": "Pilih satu",
    "reasonNotEnough": "Ia tidak menyekat cukup banyak YouTube Mix",
    "reasonBlockedIncorrectly": "Ia menyekat atau mengubah sesuatu dengan salah",
    "reasonLayoutLanguage": "Ia tidak berfungsi dengan susun atur atau bahasa YouTube saya",
    "reasonConfiguration": "Ia mengelirukan untuk dikonfigurasi",
    "reasonBugSlowdown": "Ia menyebabkan pepijat, kelembapan atau isu keserasian",
    "reasonNoLongerNeeded": "Saya tidak memerlukannya lagi",
    "reasonPrivacyPermissions": "Kebimbangan privasi atau kebenaran",
    "reasonOther": "Lain-lain",
    "detailsLabel": "Apa yang berlaku atau apa yang anda jangkakan?",
    "detailsHelp": "Pilihan. Satu atau dua ayat sudah mencukupi.",
    "featureLabel": "Ciri apakah yang akan membuat anda mencubanya lagi?",
    "featureHelp": "Pilihan.",
    "contactLabel": "Alamat balasan",
    "contactHelp": "Pilihan. Sertakan hanya jika anda mahu balasan.",
    "submit": "Hantar maklum balas",
    "status": "Maklum balas diproses oleh Formspree.",
    "footerSource": "Sumber"
  },
  "nl": {
    "pageTitle": "Feedback over YouTube Mix Blocker",
    "metaDescription": "Optionele feedback na het verwijderen van YouTube Mix Blocker.",
    "brandHomeLabel": "Startpagina van Oleksandr Molodchyk",
    "navLabel": "Hoofdnavigatie",
    "navProjects": "Projecten",
    "navNow": "Nu",
    "navAbout": "Over",
    "navContact": "Contact",
    "headline": "Help de extensie verbeteren",
    "intro": "Als YouTube Mix Blocker niet voldeed, is een korte opmerking genoeg. Dit formulier is optioneel en vraagt geen contactgegevens.",
    "privacyNote": "De extensie opent deze pagina na verwijdering alleen met algemene parameters voor bron, versie en browsertaal. Vul geen persoonlijke gegevens in tenzij je die bewust wilt delen.",
    "reasonLabel": "Waarom heb je de extensie verwijderd?",
    "chooseOne": "Kies een optie",
    "reasonNotEnough": "Er werden niet genoeg YouTube Mixes geblokkeerd",
    "reasonBlockedIncorrectly": "Er werd iets onterecht geblokkeerd of gewijzigd",
    "reasonLayoutLanguage": "Het werkte niet met mijn YouTube-indeling of taal",
    "reasonConfiguration": "Het was verwarrend om in te stellen",
    "reasonBugSlowdown": "Het veroorzaakte een fout, vertraging of compatibiliteitsprobleem",
    "reasonNoLongerNeeded": "Ik heb het niet meer nodig",
    "reasonPrivacyPermissions": "Zorgen over privacy of machtigingen",
    "reasonOther": "Anders",
    "detailsLabel": "Wat gebeurde er of wat verwachtte je?",
    "detailsHelp": "Optioneel. Een of twee zinnen is genoeg.",
    "featureLabel": "Welke functie zou je opnieuw laten proberen?",
    "featureHelp": "Optioneel.",
    "contactLabel": "Antwoordadres",
    "contactHelp": "Optioneel. Alleen invullen als je een antwoord wilt.",
    "submit": "Feedback verzenden",
    "status": "Feedback wordt verwerkt door Formspree.",
    "footerSource": "Bron"
  },
  "ro": {
    "pageTitle": "Feedback pentru YouTube Mix Blocker",
    "metaDescription": "Feedback opțional după dezinstalarea YouTube Mix Blocker.",
    "brandHomeLabel": "Pagina principală Oleksandr Molodchyk",
    "navLabel": "Navigare principală",
    "navProjects": "Proiecte",
    "navNow": "Acum",
    "navAbout": "Despre",
    "navContact": "Contact",
    "headline": "Ajută la îmbunătățirea extensiei",
    "intro": "Dacă YouTube Mix Blocker nu a fost ce te așteptai, o notă scurtă este suficientă. Formularul este opțional și nu necesită date de contact.",
    "privacyNote": "Extensia deschide această pagină după dezinstalare doar cu parametri generici pentru sursă, versiune și limba browserului. Nu include date personale decât dacă vrei intenționat să le distribui.",
    "reasonLabel": "De ce ai dezinstalat?",
    "chooseOne": "Alege o opțiune",
    "reasonNotEnough": "Nu a blocat suficiente YouTube Mixes",
    "reasonBlockedIncorrectly": "A blocat sau a schimbat ceva incorect",
    "reasonLayoutLanguage": "Nu a funcționat cu aspectul sau limba mea YouTube",
    "reasonConfiguration": "A fost confuz de configurat",
    "reasonBugSlowdown": "A cauzat o eroare, încetinire sau problemă de compatibilitate",
    "reasonNoLongerNeeded": "Nu mai am nevoie de el",
    "reasonPrivacyPermissions": "Îngrijorare privind confidențialitatea sau permisiunile",
    "reasonOther": "Altceva",
    "detailsLabel": "Ce s-a întâmplat sau ce te așteptai să se întâmple?",
    "detailsHelp": "Opțional. Una sau două propoziții sunt suficiente.",
    "featureLabel": "Ce funcție te-ar face să îl încerci din nou?",
    "featureHelp": "Opțional.",
    "contactLabel": "Adresă pentru răspuns",
    "contactHelp": "Opțional. Include-o doar dacă vrei un răspuns.",
    "submit": "Trimite feedback",
    "status": "Feedbackul este procesat prin Formspree.",
    "footerSource": "Sursă"
  }
};
