export const LOCALE_COPY_GROUP_3 = {
  "pt_BR": {
    "pageTitle": "Feedback do YouTube Mix Blocker",
    "metaDescription": "Feedback opcional após desinstalar o YouTube Mix Blocker.",
    "brandHomeLabel": "Página inicial de Oleksandr Molodchyk",
    "navLabel": "Navegação principal",
    "navProjects": "Projetos",
    "navNow": "Agora",
    "navAbout": "Sobre",
    "navContact": "Contato",
    "headline": "Ajude a melhorar a extensão",
    "intro": "Se o YouTube Mix Blocker não atendeu às suas expectativas, uma nota curta já ajuda. Este formulário é opcional e não exige informações de contato.",
    "privacyNote": "A extensão abre esta página após a desinstalação apenas com parâmetros genéricos de origem, versão e idioma do navegador. Não inclua dados pessoais, a menos que queira compartilhá-los intencionalmente.",
    "reasonLabel": "Por que você desinstalou?",
    "chooseOne": "Escolha uma opção",
    "reasonNotEnough": "Não bloqueou YouTube Mixes suficientes",
    "reasonBlockedIncorrectly": "Bloqueou ou alterou algo incorretamente",
    "reasonLayoutLanguage": "Não funcionou no meu layout ou idioma do YouTube",
    "reasonConfiguration": "Era confuso de configurar",
    "reasonBugSlowdown": "Causou bug, lentidão ou problema de compatibilidade",
    "reasonNoLongerNeeded": "Não preciso mais",
    "reasonPrivacyPermissions": "Preocupação com privacidade ou permissões",
    "reasonOther": "Outro",
    "detailsLabel": "O que aconteceu ou o que você esperava?",
    "detailsHelp": "Opcional. Uma ou duas frases bastam.",
    "featureLabel": "Qual recurso faria você tentar de novo?",
    "featureHelp": "Opcional.",
    "contactLabel": "Endereço para resposta",
    "contactHelp": "Opcional. Inclua apenas se quiser uma resposta.",
    "submit": "Enviar feedback",
    "status": "O feedback é processado pelo Formspree.",
    "footerSource": "Código-fonte"
  },
  "pt_PT": {
    "pageTitle": "Feedback do YouTube Mix Blocker",
    "metaDescription": "Feedback opcional após desinstalar o YouTube Mix Blocker.",
    "brandHomeLabel": "Página inicial de Oleksandr Molodchyk",
    "navLabel": "Navegação principal",
    "navProjects": "Projetos",
    "navNow": "Agora",
    "navAbout": "Sobre",
    "navContact": "Contacto",
    "headline": "Ajude a melhorar a extensão",
    "intro": "Se o YouTube Mix Blocker não correspondeu às suas expectativas, uma nota curta é suficiente. Este formulário é opcional e não exige dados de contacto.",
    "privacyNote": "A extensão abre esta página após a desinstalação apenas com parâmetros genéricos de origem, versão e idioma do navegador. Não inclua dados pessoais, a menos que os queira partilhar intencionalmente.",
    "reasonLabel": "Porque desinstalou?",
    "chooseOne": "Escolha uma opção",
    "reasonNotEnough": "Não bloqueou YouTube Mixes suficientes",
    "reasonBlockedIncorrectly": "Bloqueou ou alterou algo incorretamente",
    "reasonLayoutLanguage": "Não funcionou com o meu esquema ou idioma do YouTube",
    "reasonConfiguration": "Era confuso de configurar",
    "reasonBugSlowdown": "Causou um erro, lentidão ou problema de compatibilidade",
    "reasonNoLongerNeeded": "Já não preciso",
    "reasonPrivacyPermissions": "Preocupação com privacidade ou permissões",
    "reasonOther": "Outro",
    "detailsLabel": "O que aconteceu ou o que esperava?",
    "detailsHelp": "Opcional. Uma ou duas frases chegam.",
    "featureLabel": "Que funcionalidade o faria experimentar de novo?",
    "featureHelp": "Opcional.",
    "contactLabel": "Endereço para resposta",
    "contactHelp": "Opcional. Inclua apenas se quiser uma resposta.",
    "submit": "Enviar feedback",
    "status": "O feedback é processado pelo Formspree.",
    "footerSource": "Código-fonte"
  },
  "ru": {
    "pageTitle": "Отзыв о YouTube Mix Blocker",
    "metaDescription": "Необязательный отзыв после удаления YouTube Mix Blocker.",
    "brandHomeLabel": "Главная страница Oleksandr Molodchyk",
    "navLabel": "Основная навигация",
    "navProjects": "Проекты",
    "navNow": "Сейчас",
    "navAbout": "О проекте",
    "navContact": "Контакт",
    "headline": "Помогите улучшить расширение",
    "intro": "Если YouTube Mix Blocker не оправдал ожиданий, достаточно короткой заметки. Эта форма необязательна и не требует контактных данных.",
    "privacyNote": "Расширение открывает эту страницу после удаления только с общими параметрами источника, версии и языка браузера. Не указывайте персональные данные, если не хотите намеренно ими поделиться.",
    "reasonLabel": "Почему вы удалили расширение?",
    "chooseOne": "Выберите вариант",
    "reasonNotEnough": "Оно блокировало недостаточно YouTube Mixes",
    "reasonBlockedIncorrectly": "Оно ошибочно блокировало или изменяло что-то",
    "reasonLayoutLanguage": "Оно не работало с моим интерфейсом или языком YouTube",
    "reasonConfiguration": "Настройка была непонятной",
    "reasonBugSlowdown": "Оно вызывало ошибку, замедление или проблему совместимости",
    "reasonNoLongerNeeded": "Оно мне больше не нужно",
    "reasonPrivacyPermissions": "Вопросы приватности или разрешений",
    "reasonOther": "Другое",
    "detailsLabel": "Что произошло или чего вы ожидали?",
    "detailsHelp": "Необязательно. Достаточно одного-двух предложений.",
    "featureLabel": "Какая функция заставила бы вас попробовать снова?",
    "featureHelp": "Необязательно.",
    "contactLabel": "Адрес для ответа",
    "contactHelp": "Необязательно. Укажите только если хотите получить ответ.",
    "submit": "Отправить отзыв",
    "status": "Отзыв обрабатывается через Formspree.",
    "footerSource": "Источник"
  },
  "sv": {
    "pageTitle": "Feedback för YouTube Mix Blocker",
    "metaDescription": "Frivillig feedback efter avinstallation av YouTube Mix Blocker.",
    "brandHomeLabel": "Oleksandr Molodchyks startsida",
    "navLabel": "Huvudnavigering",
    "navProjects": "Projekt",
    "navNow": "Nu",
    "navAbout": "Om",
    "navContact": "Kontakt",
    "headline": "Hjälp till att förbättra tillägget",
    "intro": "Om YouTube Mix Blocker inte träffade rätt räcker en kort kommentar. Formuläret är frivilligt och kräver inga kontaktuppgifter.",
    "privacyNote": "Tillägget öppnar den här sidan efter avinstallation med endast generiska parametrar för källa, version och webbläsarspråk. Ange inga personuppgifter om du inte avsiktligt vill dela dem.",
    "reasonLabel": "Varför avinstallerade du?",
    "chooseOne": "Välj ett alternativ",
    "reasonNotEnough": "Det blockerade inte tillräckligt många YouTube Mixes",
    "reasonBlockedIncorrectly": "Det blockerade eller ändrade något felaktigt",
    "reasonLayoutLanguage": "Det fungerade inte med min YouTube-layout eller mitt språk",
    "reasonConfiguration": "Det var förvirrande att konfigurera",
    "reasonBugSlowdown": "Det orsakade en bugg, långsamhet eller kompatibilitetsproblem",
    "reasonNoLongerNeeded": "Jag behöver det inte längre",
    "reasonPrivacyPermissions": "Integritets- eller behörighetsfråga",
    "reasonOther": "Annat",
    "detailsLabel": "Vad hände eller vad förväntade du dig i stället?",
    "detailsHelp": "Frivilligt. En eller två meningar räcker.",
    "featureLabel": "Vilken funktion skulle få dig att prova igen?",
    "featureHelp": "Frivilligt.",
    "contactLabel": "Svarsadress",
    "contactHelp": "Frivilligt. Ange bara om du vill ha ett svar.",
    "submit": "Skicka feedback",
    "status": "Feedback behandlas av Formspree.",
    "footerSource": "Källa"
  },
  "tr": {
    "pageTitle": "YouTube Mix Blocker geri bildirimi",
    "metaDescription": "YouTube Mix Blocker kaldırıldıktan sonra isteğe bağlı geri bildirim.",
    "brandHomeLabel": "Oleksandr Molodchyk ana sayfası",
    "navLabel": "Ana gezinme",
    "navProjects": "Projeler",
    "navNow": "Şimdi",
    "navAbout": "Hakkında",
    "navContact": "İletişim",
    "headline": "Uzantıyı geliştirmeye yardım edin",
    "intro": "YouTube Mix Blocker beklentinizi karşılamadıysa kısa bir not yeterlidir. Bu form isteğe bağlıdır ve iletişim bilgisi gerektirmez.",
    "privacyNote": "Uzantı, kaldırıldıktan sonra bu sayfayı yalnızca genel kaynak, sürüm ve tarayıcı dili parametreleriyle açar. Bilerek paylaşmak istemiyorsanız kişisel veri eklemeyin.",
    "reasonLabel": "Neden kaldırdınız?",
    "chooseOne": "Birini seçin",
    "reasonNotEnough": "Yeterince YouTube Mix engellemedi",
    "reasonBlockedIncorrectly": "Bir şeyi yanlış engelledi veya değiştirdi",
    "reasonLayoutLanguage": "YouTube düzenimde veya dilimde çalışmadı",
    "reasonConfiguration": "Yapılandırması kafa karıştırıcıydı",
    "reasonBugSlowdown": "Hata, yavaşlama veya uyumluluk sorunu oluşturdu",
    "reasonNoLongerNeeded": "Artık ihtiyacım yok",
    "reasonPrivacyPermissions": "Gizlilik veya izin endişesi",
    "reasonOther": "Diğer",
    "detailsLabel": "Ne oldu veya bunun yerine ne bekliyordunuz?",
    "detailsHelp": "İsteğe bağlı. Bir iki cümle yeterlidir.",
    "featureLabel": "Hangi özellik tekrar denemenizi sağlar?",
    "featureHelp": "İsteğe bağlı.",
    "contactLabel": "Yanıt adresi",
    "contactHelp": "İsteğe bağlı. Yalnızca yanıt istiyorsanız ekleyin.",
    "submit": "Geri bildirim gönder",
    "status": "Geri bildirim Formspree tarafından işlenir.",
    "footerSource": "Kaynak"
  }
};
