export const LOCALE_COPY_GROUP_6 = {
  "th": {
    "pageTitle": "ความคิดเห็นเกี่ยวกับ YouTube Mix Blocker",
    "metaDescription": "ความคิดเห็นแบบไม่บังคับหลังจากถอนการติดตั้ง YouTube Mix Blocker",
    "brandHomeLabel": "หน้าแรกของ Oleksandr Molodchyk",
    "navLabel": "การนำทางหลัก",
    "navProjects": "โปรเจกต์",
    "navNow": "ตอนนี้",
    "navAbout": "เกี่ยวกับ",
    "navContact": "ติดต่อ",
    "headline": "ช่วยปรับปรุงส่วนขยายนี้",
    "intro": "ถ้า YouTube Mix Blocker ยังไม่ตรงกับที่คุณคาดหวัง ข้อความสั้น ๆ ก็เพียงพอแล้ว แบบฟอร์มนี้เป็นทางเลือกและไม่ต้องใช้ข้อมูลติดต่อ",
    "privacyNote": "ส่วนขยายจะเปิดหน้านี้หลังถอนการติดตั้ง โดยมีเพียงพารามิเตอร์ทั่วไปของแหล่งที่มา เวอร์ชัน และภาษาของเบราว์เซอร์ อย่าใส่ข้อมูลส่วนตัวเว้นแต่คุณตั้งใจจะแชร์",
    "reasonLabel": "ทำไมคุณจึงถอนการติดตั้ง?",
    "chooseOne": "เลือกหนึ่งข้อ",
    "reasonNotEnough": "บล็อก YouTube Mix ได้ไม่มากพอ",
    "reasonBlockedIncorrectly": "บล็อกหรือเปลี่ยนบางอย่างผิดพลาด",
    "reasonLayoutLanguage": "ไม่ทำงานกับเลย์เอาต์หรือภาษาของ YouTube ที่ฉันใช้",
    "reasonConfiguration": "ตั้งค่ายากหรือสับสน",
    "reasonBugSlowdown": "ทำให้เกิดบั๊ก ช้า หรือปัญหาความเข้ากันได้",
    "reasonNoLongerNeeded": "ฉันไม่ต้องการใช้อีกแล้ว",
    "reasonPrivacyPermissions": "กังวลเรื่องความเป็นส่วนตัวหรือสิทธิ์",
    "reasonOther": "อื่น ๆ",
    "detailsLabel": "เกิดอะไรขึ้น หรือคุณคาดหวังอะไรแทน?",
    "detailsHelp": "ไม่บังคับ หนึ่งหรือสองประโยคก็พอ",
    "featureLabel": "ฟีเจอร์ใดที่จะทำให้คุณลองใช้อีกครั้ง?",
    "featureHelp": "ไม่บังคับ",
    "contactLabel": "ที่อยู่สำหรับตอบกลับ",
    "contactHelp": "ไม่บังคับ ใส่เฉพาะเมื่อคุณต้องการคำตอบ",
    "submit": "ส่งความคิดเห็น",
    "status": "ความคิดเห็นจะถูกประมวลผลโดย Formspree",
    "footerSource": "ซอร์ส"
  },
  "uk": {
    "pageTitle": "Відгук про YouTube Mix Blocker",
    "metaDescription": "Необов'язковий відгук після видалення YouTube Mix Blocker.",
    "brandHomeLabel": "Головна сторінка Oleksandr Molodchyk",
    "navLabel": "Основна навігація",
    "navProjects": "Проєкти",
    "navNow": "Зараз",
    "navAbout": "Про мене",
    "navContact": "Контакт",
    "headline": "Допоможіть покращити розширення",
    "intro": "Якщо YouTube Mix Blocker не виправдав очікувань, достатньо короткої нотатки. Ця форма необов'язкова і не потребує контактних даних.",
    "privacyNote": "Розширення відкриває цю сторінку після видалення лише із загальними параметрами джерела, версії та мови браузера. Не вказуйте персональні дані, якщо не хочете свідомо ними поділитися.",
    "reasonLabel": "Чому ви видалили розширення?",
    "chooseOne": "Оберіть варіант",
    "reasonNotEnough": "Воно блокувало недостатньо YouTube Mixes",
    "reasonBlockedIncorrectly": "Воно помилково блокувало або змінювало щось",
    "reasonLayoutLanguage": "Воно не працювало з моїм макетом або мовою YouTube",
    "reasonConfiguration": "Налаштування було незрозумілим",
    "reasonBugSlowdown": "Воно спричиняло помилку, уповільнення або проблему сумісності",
    "reasonNoLongerNeeded": "Воно мені більше не потрібне",
    "reasonPrivacyPermissions": "Питання приватності або дозволів",
    "reasonOther": "Інше",
    "detailsLabel": "Що сталося або чого ви очікували?",
    "detailsHelp": "Необов'язково. Достатньо одного-двох речень.",
    "featureLabel": "Яка функція змусила б вас спробувати знову?",
    "featureHelp": "Необов'язково.",
    "contactLabel": "Адреса для відповіді",
    "contactHelp": "Необов'язково. Додайте лише якщо хочете отримати відповідь.",
    "submit": "Надіслати відгук",
    "status": "Відгук обробляється через Formspree.",
    "footerSource": "Джерело"
  }
};
