const keys = [
  'pageTitle',
  'metaDescription',
  'brandHomeLabel',
  'navLabel',
  'navProjects',
  'navNow',
  'navAbout',
  'navContact',
  'headline',
  'intro',
  'privacyNote',
  'reasonLabel',
  'chooseOne',
  'reasonNotEnough',
  'reasonBlockedIncorrectly',
  'reasonLayoutLanguage',
  'reasonConfiguration',
  'reasonBugSlowdown',
  'reasonNoLongerNeeded',
  'reasonPrivacyPermissions',
  'reasonOther',
  'detailsLabel',
  'detailsHelp',
  'featureLabel',
  'featureHelp',
  'contactLabel',
  'contactHelp',
  'submit',
  'status',
  'footerSource'
];

function makeCopy(values) {
  return Object.fromEntries(keys.map((key, index) => [key, values[index]]));
}

export const LOCALE_COPY_GROUP_9 = {
  pa: makeCopy([
    'YouTube Mix Blocker ਫੀਡਬੈਕ',
    'YouTube Mix Blocker ਅਣਇੰਸਟਾਲ ਕਰਨ ਤੋਂ ਬਾਅਦ ਵਿਕਲਪਿਕ ਫੀਡਬੈਕ।',
    'Oleksandr Molodchyk ਹੋਮ',
    'ਮੁੱਖ ਨੇਵੀਗੇਸ਼ਨ',
    'ਪ੍ਰੋਜੈਕਟ',
    'ਹੁਣ',
    'ਬਾਰੇ',
    'ਸੰਪਰਕ',
    'ਐਕਸਟੈਂਸ਼ਨ ਨੂੰ ਸੁਧਾਰਨ ਵਿੱਚ ਮਦਦ ਕਰੋ',
    'ਜੇ YouTube Mix Blocker ਉਮੀਦਾਂ ਤੇ ਖਰਾ ਨਹੀਂ ਉਤਰਾ, ਤਾਂ ਇੱਕ ਛੋਟੀ ਟਿੱਪਣੀ ਕਾਫ਼ੀ ਹੈ। ਇਹ ਫਾਰਮ ਵਿਕਲਪਿਕ ਹੈ ਅਤੇ ਸੰਪਰਕ ਜਾਣਕਾਰੀ ਨਹੀਂ ਮੰਗਦਾ।',
    'ਐਕਸਟੈਂਸ਼ਨ ਅਣਇੰਸਟਾਲ ਹੋਣ ਤੋਂ ਬਾਅਦ ਇਹ ਪੰਨਾ ਸਿਰਫ਼ ਆਮ source, version ਅਤੇ browser-language ਪੈਰਾਮੀਟਰਾਂ ਨਾਲ ਖੋਲ੍ਹਦਾ ਹੈ। ਨਿੱਜੀ ਡਾਟਾ ਨਾ ਸ਼ਾਮਲ ਕਰੋ ਜਦ ਤੱਕ ਤੁਸੀਂ ਜਾਣਬੁੱਝ ਕੇ ਸਾਂਝਾ ਨਹੀਂ ਕਰਨਾ ਚਾਹੁੰਦੇ।',
    'ਤੁਸੀਂ ਇਸਨੂੰ ਕਿਉਂ ਅਣਇੰਸਟਾਲ ਕੀਤਾ?',
    'ਇੱਕ ਚੁਣੋ',
    'ਇਸਨੇ ਕਾਫ਼ੀ YouTube Mixes ਬਲਾਕ ਨਹੀਂ ਕੀਤੇ',
    'ਇਸਨੇ ਕੁਝ ਗਲਤ ਤਰੀਕੇ ਨਾਲ ਬਲਾਕ ਜਾਂ ਬਦਲਿਆ',
    'ਇਹ ਮੇਰੇ YouTube ਲੇਆਉਟ ਜਾਂ ਭਾਸ਼ਾ ਨਾਲ ਕੰਮ ਨਹੀਂ ਕਰਦਾ ਸੀ',
    'ਇਸਨੂੰ ਕਨਫਿਗਰ ਕਰਨਾ ਗੁੰਝਲਦਾਰ ਸੀ',
    'ਇਸਨੇ ਬੱਗ, ਸੁਸਤੀ ਜਾਂ ਅਨੁਕੂਲਤਾ ਸਮੱਸਿਆ ਪੈਦਾ ਕੀਤੀ',
    'ਹੁਣ ਮੈਨੂੰ ਇਸਦੀ ਲੋੜ ਨਹੀਂ',
    'ਗੋਪਨੀਯਤਾ ਜਾਂ ਇਜਾਜ਼ਤਾਂ ਬਾਰੇ ਚਿੰਤਾ',
    'ਹੋਰ',
    'ਕੀ ਹੋਇਆ ਜਾਂ ਤੁਸੀਂ ਇਸਦੀ ਥਾਂ ਕੀ ਉਮੀਦ ਕੀਤੀ ਸੀ?',
    'ਵਿਕਲਪਿਕ। ਇੱਕ-ਦੋ ਵਾਕ ਕਾਫ਼ੀ ਹਨ।',
    'ਕਿਹੜੀ ਵਿਸ਼ੇਸ਼ਤਾ ਤੁਹਾਨੂੰ ਇਸਨੂੰ ਮੁੜ ਅਜ਼ਮਾਉਣ ਲਈ ਮਜਬੂਰ ਕਰੇਗੀ?',
    'ਵਿਕਲਪਿਕ।',
    'ਜਵਾਬ ਦਾ ਪਤਾ',
    'ਵਿਕਲਪਿਕ। ਜਵਾਬ ਚਾਹੀਦਾ ਹੋਵੇ ਤਾਂ ਹੀ ਸ਼ਾਮਲ ਕਰੋ।',
    'ਫੀਡਬੈਕ ਭੇਜੋ',
    'ਫੀਡਬੈਕ Formspree ਦੁਆਰਾ ਪ੍ਰਕਿਰਿਆ ਕੀਤਾ ਜਾਂਦਾ ਹੈ।',
    'ਸਰੋਤ'
  ]),
  si: makeCopy([
    'YouTube Mix Blocker ප්‍රතිචාර',
    'YouTube Mix Blocker අස්ථාපනය කළ පසු විකල්ප ප්‍රතිචාර.',
    'Oleksandr Molodchyk මුල් පිටුව',
    'ප්‍රධාන සංචාලනය',
    'ව්‍යාපෘති',
    'දැන්',
    'පිළිබඳ',
    'සම්බන්ධ වන්න',
    'දිගුව වැඩිදියුණු කිරීමට උදව් කරන්න',
    'YouTube Mix Blocker ඔබ බලාපොරොත්තු වූ ලෙස නොවුණේ නම්, කෙටි සටහනක් ප්‍රමාණවත්ය. මෙම පෝරමය විකල්ප වන අතර සම්බන්ධතා තොරතුරු අවශ්‍ය නොවේ.',
    'දිගුව අස්ථාපනය කළ පසු මෙම පිටුව විවෘත කරන්නේ source, version සහ browser-language යන සාමාන්‍ය පරාමිතීන් පමණක් සමඟය. ඔබ අදහස් කරමින් බෙදාගැනීමට කැමති නැත්නම් පුද්ගලික දත්ත ඇතුළත් නොකරන්න.',
    'ඔබ එය අස්ථාපනය කළේ ඇයි?',
    'එකක් තෝරන්න',
    'ප්‍රමාණවත් YouTube Mixes අවහිර කළේ නැත',
    'යමක් වැරදි ලෙස අවහිර කළේ හෝ වෙනස් කළේය',
    'මගේ YouTube සැකැස්ම හෝ භාෂාව සමඟ ක්‍රියා කළේ නැත',
    'වින්‍යාස කිරීම අවුල් සහගත විය',
    'දෝෂයක්, මන්දගාමී වීමක් හෝ අනුකූලතා ගැටලුවක් ඇති කළේය',
    'මට එය තවදුරටත් අවශ්‍ය නැත',
    'පෞද්ගලිකත්වය හෝ අවසර පිළිබඳ සැලකිල්ල',
    'වෙනත්',
    'කුමක් සිදු වුණාද, නැතහොත් ඒ වෙනුවට ඔබ බලාපොරොත්තු වූයේ කුමක්ද?',
    'විකල්ප. වාක්‍යයක් දෙකක් ප්‍රමාණවත්ය.',
    'කුමන විශේෂාංගයක් තිබුණා නම් ඔබ නැවත උත්සාහ කරයිද?',
    'විකල්ප.',
    'පිළිතුරු ලිපිනය',
    'විකල්ප. පිළිතුරක් අවශ්‍ය නම් පමණක් ඇතුළත් කරන්න.',
    'ප්‍රතිචාර යවන්න',
    'ප්‍රතිචාර Formspree මඟින් සකසනු ලැබේ.',
    'මූලාශ්‍රය'
  ]),
  sk: makeCopy([
    'Spätná väzba k YouTube Mix Blocker',
    'Voliteľná spätná väzba po odinštalovaní YouTube Mix Blocker.',
    'Domovská stránka Oleksandra Molodchyka',
    'Hlavná navigácia',
    'Projekty',
    'Teraz',
    'O mne',
    'Kontakt',
    'Pomôžte zlepšiť rozšírenie',
    'Ak YouTube Mix Blocker nesplnil očakávania, stačí krátka poznámka. Tento formulár je voliteľný a nevyžaduje kontaktné údaje.',
    'Rozšírenie po odinštalovaní otvorí túto stránku iba so všeobecnými parametrami zdroja, verzie a jazyka prehliadača. Neuvádzajte osobné údaje, pokiaľ ich nechcete zámerne zdieľať.',
    'Prečo ste odinštalovali?',
    'Vyberte jednu možnosť',
    'Neblokovalo dosť YouTube Mixov',
    'Niečo blokovalo alebo menilo nesprávne',
    'Nefungovalo s mojím rozložením alebo jazykom YouTube',
    'Konfigurácia bola mätúca',
    'Spôsobovalo chybu, spomalenie alebo problém s kompatibilitou',
    'Už ho nepotrebujem',
    'Obava o súkromie alebo povolenia',
    'Iné',
    'Čo sa stalo alebo čo ste očakávali namiesto toho?',
    'Voliteľné. Stačí jedna alebo dve vety.',
    'Aká funkcia by vás prinútila vyskúšať ho znova?',
    'Voliteľné.',
    'Adresa na odpoveď',
    'Voliteľné. Uveďte ju iba vtedy, ak chcete odpoveď.',
    'Odoslať spätnú väzbu',
    'Spätnú väzbu spracúva Formspree.',
    'Zdroj'
  ]),
  sl: makeCopy([
    'Povratne informacije za YouTube Mix Blocker',
    'Neobvezne povratne informacije po odstranitvi YouTube Mix Blocker.',
    'Domača stran Oleksandra Molodchyka',
    'Glavna navigacija',
    'Projekti',
    'Zdaj',
    'O meni',
    'Kontakt',
    'Pomagajte izboljšati razširitev',
    'Če YouTube Mix Blocker ni izpolnil pričakovanj, je kratka opomba dovolj. Ta obrazec je neobvezen in ne zahteva kontaktnih podatkov.',
    'Razširitev po odstranitvi odpre to stran samo s splošnimi parametri vira, različice in jezika brskalnika. Ne vnašajte osebnih podatkov, razen če jih namenoma želite deliti.',
    'Zakaj ste jo odstranili?',
    'Izberite eno možnost',
    'Ni blokirala dovolj YouTube Mixes',
    'Nekaj je napačno blokirala ali spremenila',
    'Ni delovala z mojo postavitvijo ali jezikom YouTube',
    'Konfiguracija je bila zmedena',
    'Povzročila je napako, upočasnitev ali težavo z združljivostjo',
    'Ne potrebujem je več',
    'Skrb glede zasebnosti ali dovoljenj',
    'Drugo',
    'Kaj se je zgodilo ali kaj ste pričakovali namesto tega?',
    'Neobvezno. En ali dva stavka sta dovolj.',
    'Katera funkcija bi vas prepričala, da jo poskusite znova?',
    'Neobvezno.',
    'Naslov za odgovor',
    'Neobvezno. Dodajte ga samo, če želite odgovor.',
    'Pošlji povratne informacije',
    'Povratne informacije obdeluje Formspree.',
    'Vir'
  ]),
  sq: makeCopy([
    'Reagime për YouTube Mix Blocker',
    'Reagim opsional pas çinstalimit të YouTube Mix Blocker.',
    'Faqja kryesore e Oleksandr Molodchyk',
    'Navigimi kryesor',
    'Projektet',
    'Tani',
    'Rreth',
    'Kontakt',
    'Ndihmoni në përmirësimin e shtesës',
    'Nëse YouTube Mix Blocker nuk i përmbushi pritjet, mjafton një shënim i shkurtër. Ky formular është opsional dhe nuk kërkon të dhëna kontakti.',
    'Shtesa e hap këtë faqe pas çinstalimit vetëm me parametra të përgjithshëm për burimin, versionin dhe gjuhën e shfletuesit. Mos përfshini të dhëna personale nëse nuk doni t’i ndani me qëllim.',
    'Pse e çinstaluat?',
    'Zgjidhni një',
    'Nuk bllokoi mjaft YouTube Mixes',
    'Bllokoi ose ndryshoi diçka gabimisht',
    'Nuk punoi me paraqitjen ose gjuhën time të YouTube',
    'Konfigurimi ishte i paqartë',
    'Shkaktoi gabim, ngadalësim ose problem përputhshmërie',
    'Nuk më nevojitet më',
    'Shqetësim për privatësinë ose lejet',
    'Tjetër',
    'Çfarë ndodhi ose çfarë prisnit në vend të kësaj?',
    'Opsionale. Mjafton një ose dy fjali.',
    'Cila veçori do t’ju bënte ta provonit përsëri?',
    'Opsionale.',
    'Adresa për përgjigje',
    'Opsionale. Vendoseni vetëm nëse doni përgjigje.',
    'Dërgo reagim',
    'Reagimi përpunohet nga Formspree.',
    'Burimi'
  ]),
  sr: makeCopy([
    'Повратне информације за YouTube Mix Blocker',
    'Опционе повратне информације после деинсталације YouTube Mix Blocker-а.',
    'Почетна страница Oleksandr Molodchyk-а',
    'Главна навигација',
    'Пројекти',
    'Сада',
    'О мени',
    'Контакт',
    'Помозите да се проширење побољша',
    'Ако YouTube Mix Blocker није испунио очекивања, кратка напомена је довољна. Овај образац је опционалан и не захтева контакт податке.',
    'Проширење после деинсталације отвара ову страницу само са општим параметрима извора, верзије и језика прегледача. Не уносите личне податке осим ако намерно желите да их поделите.',
    'Зашто сте деинсталирали?',
    'Изаберите једно',
    'Није блокирао довољно YouTube Mixes',
    'Нешто је погрешно блокирао или променио',
    'Није радио са мојим YouTube распоредом или језиком',
    'Конфигурисање је било збуњујуће',
    'Изазвао је грешку, успоравање или проблем са компатибилношћу',
    'Више ми није потребан',
    'Забринутост за приватност или дозволе',
    'Друго',
    'Шта се догодило или шта сте очекивали уместо тога?',
    'Опционо. Једна или две реченице су довољне.',
    'Која функција би вас навела да га поново пробате?',
    'Опционо.',
    'Адреса за одговор',
    'Опционо. Наведите само ако желите одговор.',
    'Пошаљи повратне информације',
    'Повратне информације обрађује Formspree.',
    'Извор'
  ]),
  sw: makeCopy([
    'Maoni kuhusu YouTube Mix Blocker',
    'Maoni ya hiari baada ya kuondoa YouTube Mix Blocker.',
    'Nyumbani kwa Oleksandr Molodchyk',
    'Urambazaji mkuu',
    'Miradi',
    'Sasa',
    'Kuhusu',
    'Mawasiliano',
    'Saidia kuboresha kiendelezi',
    'Ikiwa YouTube Mix Blocker haikutimiza matarajio, dokezo fupi linatosha. Fomu hii ni ya hiari na haihitaji taarifa za mawasiliano.',
    'Kiendelezi hufungua ukurasa huu baada ya kuondolewa kikiwa na vigezo vya jumla tu vya chanzo, toleo na lugha ya kivinjari. Usiweke data binafsi isipokuwa unataka kuishiriki kwa makusudi.',
    'Kwa nini uliiondoa?',
    'Chagua moja',
    'Haikuzuia YouTube Mixes za kutosha',
    'Ilizuia au kubadilisha kitu kimakosa',
    'Haikufanya kazi na mpangilio au lugha yangu ya YouTube',
    'Ilikuwa inachanganya kusanidi',
    'Ilisababisha hitilafu, kupungua kasi au tatizo la uoanifu',
    'Sihitaji tena',
    'Wasiwasi wa faragha au ruhusa',
    'Nyingine',
    'Nini kilitokea au ulitarajia nini badala yake?',
    'Hiari. Sentensi moja au mbili zinatosha.',
    'Kipengele gani kingekufanya ujaribu tena?',
    'Hiari.',
    'Anwani ya kujibiwa',
    'Hiari. Weka tu ikiwa unataka jibu.',
    'Tuma maoni',
    'Maoni huchakatwa na Formspree.',
    'Chanzo'
  ]),
  ta: makeCopy([
    'YouTube Mix Blocker கருத்து',
    'YouTube Mix Blocker அகற்றப்பட்ட பிறகு விருப்பமான கருத்து.',
    'Oleksandr Molodchyk முகப்பு',
    'முதன்மை வழிசெலுத்தல்',
    'திட்டங்கள்',
    'இப்போது',
    'பற்றி',
    'தொடர்பு',
    'நீட்டிப்பை மேம்படுத்த உதவுங்கள்',
    'YouTube Mix Blocker எதிர்பார்ப்பை பூர்த்தி செய்யவில்லை என்றால், ஒரு குறுகிய குறிப்பே போதும். இந்தப் படிவம் விருப்பமானது; தொடர்பு தகவல் தேவையில்லை.',
    'நீட்டிப்பு அகற்றப்பட்ட பிறகு, இந்தப் பக்கம் source, version மற்றும் browser-language போன்ற பொதுவான அளவுருக்களுடன் மட்டும் திறக்கப்படுகிறது. நீங்கள் திட்டமிட்டு பகிர விரும்பினால் தவிர தனிப்பட்ட தரவை சேர்க்க வேண்டாம்.',
    'ஏன் அகற்றினீர்கள்?',
    'ஒன்றைத் தேர்ந்தெடுக்கவும்',
    'போதுமான YouTube Mixes-ஐ தடுக்கவில்லை',
    'ஏதாவது ஒன்றை தவறாக தடுத்தது அல்லது மாற்றியது',
    'என் YouTube அமைப்பு அல்லது மொழியில் வேலை செய்யவில்லை',
    'அமைப்பது குழப்பமாக இருந்தது',
    'பிழை, மந்தம் அல்லது பொருந்துதல் சிக்கலை ஏற்படுத்தியது',
    'இனி எனக்கு இது தேவையில்லை',
    'தனியுரிமை அல்லது அனுமதி குறித்த கவலை',
    'மற்றவை',
    'என்ன நடந்தது அல்லது அதற்கு பதிலாக என்ன எதிர்பார்த்தீர்கள்?',
    'விருப்பமானது. ஒரு அல்லது இரண்டு வாக்கியங்கள் போதும்.',
    'எந்த அம்சம் இருந்தால் மீண்டும் முயற்சிப்பீர்கள்?',
    'விருப்பமானது.',
    'பதில் முகவரி',
    'விருப்பமானது. பதில் வேண்டுமெனில் மட்டும் சேர்க்கவும்.',
    'கருத்தை அனுப்பு',
    'கருத்து Formspree மூலம் செயலாக்கப்படுகிறது.',
    'மூலம்'
  ]),
  te: makeCopy([
    'YouTube Mix Blocker అభిప్రాయం',
    'YouTube Mix Blocker అన్‌ఇన్‌స్టాల్ చేసిన తర్వాత ఐచ్ఛిక అభిప్రాయం.',
    'Oleksandr Molodchyk హోమ్',
    'ప్రధాన నావిగేషన్',
    'ప్రాజెక్టులు',
    'ఇప్పుడు',
    'గురించి',
    'సంప్రదింపు',
    'ఎక్స్‌టెన్షన్‌ను మెరుగుపరచడంలో సహాయపడండి',
    'YouTube Mix Blocker మీ అంచనాలకు సరిపోలకపోతే, చిన్న గమనిక చాలు. ఈ ఫారమ్ ఐచ్ఛికం మరియు సంప్రదింపు సమాచారం అవసరం లేదు.',
    'ఎక్స్‌టెన్షన్ అన్‌ఇన్‌స్టాల్ అయిన తర్వాత ఈ పేజీ source, version మరియు browser-language వంటి సాధారణ పరామితులతో మాత్రమే తెరుచుకుంటుంది. మీరు ఉద్దేశపూర్వకంగా పంచుకోవాలనుకుంటే తప్ప వ్యక్తిగత డేటాను చేర్చవద్దు.',
    'మీరు ఎందుకు అన్‌ఇన్‌స్టాల్ చేశారు?',
    'ఒకదాన్ని ఎంచుకోండి',
    'తగినంత YouTube Mixes‌ను బ్లాక్ చేయలేదు',
    'ఏదో ఒకదాన్ని తప్పుగా బ్లాక్ చేసింది లేదా మార్చింది',
    'నా YouTube లేఅవుట్ లేదా భాషలో పనిచేయలేదు',
    'కాన్ఫిగర్ చేయడం గందరగోళంగా ఉంది',
    'బగ్, మందగింపు లేదా అనుకూలత సమస్య కలిగించింది',
    'ఇక నాకు అవసరం లేదు',
    'గోప్యత లేదా అనుమతులపై ఆందోళన',
    'ఇతర',
    'ఏం జరిగింది లేదా దాని బదులు మీరు ఏమి ఆశించారు?',
    'ఐచ్ఛికం. ఒకటి రెండు వాక్యాలు చాలు.',
    'ఏ ఫీచర్ ఉంటే మీరు మళ్లీ ప్రయత్నిస్తారు?',
    'ఐచ్ఛికం.',
    'ప్రత్యుత్తర చిరునామా',
    'ఐచ్ఛికం. సమాధానం కావాలంటే మాత్రమే చేర్చండి.',
    'అభిప్రాయం పంపండి',
    'అభిప్రాయం Formspree ద్వారా ప్రాసెస్ చేయబడుతుంది.',
    'మూలం'
  ]),
  ur: makeCopy([
    'YouTube Mix Blocker رائے',
    'YouTube Mix Blocker اَن انسٹال کرنے کے بعد اختیاری رائے۔',
    'Oleksandr Molodchyk ہوم',
    'مرکزی نیویگیشن',
    'پروجیکٹس',
    'ابھی',
    'تعارف',
    'رابطہ',
    'ایکسٹینشن کو بہتر بنانے میں مدد کریں',
    'اگر YouTube Mix Blocker توقع کے مطابق نہ تھا تو ایک مختصر نوٹ کافی ہے۔ یہ فارم اختیاری ہے اور رابطہ معلومات ضروری نہیں۔',
    'ایکسٹینشن اَن انسٹال ہونے کے بعد یہ صفحہ صرف عمومی source، version اور browser-language پیرامیٹرز کے ساتھ کھلتا ہے۔ ذاتی ڈیٹا شامل نہ کریں جب تک آپ جان بوجھ کر اسے شیئر نہیں کرنا چاہتے۔',
    'آپ نے اَن انسٹال کیوں کیا؟',
    'ایک منتخب کریں',
    'اس نے کافی YouTube Mixes بلاک نہیں کیے',
    'اس نے کچھ غلط طور پر بلاک یا تبدیل کیا',
    'یہ میرے YouTube لے آؤٹ یا زبان کے ساتھ کام نہیں کر رہا تھا',
    'اسے کنفیگر کرنا الجھا ہوا تھا',
    'اس نے بگ، سست رفتاری یا مطابقت کا مسئلہ پیدا کیا',
    'اب مجھے اس کی ضرورت نہیں',
    'پرائیویسی یا اجازتوں کا خدشہ',
    'دیگر',
    'کیا ہوا یا آپ اس کے بجائے کیا توقع کر رہے تھے؟',
    'اختیاری۔ ایک یا دو جملے کافی ہیں۔',
    'کون سی خصوصیت آپ کو دوبارہ آزمانے پر آمادہ کرے گی؟',
    'اختیاری۔',
    'جواب کا پتہ',
    'اختیاری۔ صرف اس صورت میں شامل کریں اگر آپ جواب چاہتے ہیں۔',
    'رائے بھیجیں',
    'رائے Formspree کے ذریعے پراسیس ہوتی ہے۔',
    'ماخذ'
  ]),
  uz: makeCopy([
    'YouTube Mix Blocker fikr-mulohazasi',
    'YouTube Mix Blocker olib tashlangandan keyingi ixtiyoriy fikr-mulohaza.',
    'Oleksandr Molodchyk bosh sahifasi',
    'Asosiy navigatsiya',
    'Loyihalar',
    'Hozir',
    'Haqida',
    'Aloqa',
    'Kengaytmani yaxshilashga yordam bering',
    'YouTube Mix Blocker kutganingizga mos kelmagan bo‘lsa, qisqa izoh yetarli. Bu forma ixtiyoriy va aloqa ma’lumotini talab qilmaydi.',
    'Kengaytma olib tashlangandan keyin bu sahifani faqat manba, versiya va brauzer tili haqidagi umumiy parametrlar bilan ochadi. Shaxsiy ma’lumotlarni faqat ataylab ulashmoqchi bo‘lsangiz kiriting.',
    'Nega olib tashladingiz?',
    'Bittasini tanlang',
    'Yetarlicha YouTube Mixes bloklamadi',
    'Nimadirni noto‘g‘ri blokladi yoki o‘zgartirdi',
    'Mening YouTube ko‘rinishim yoki tilimda ishlamadi',
    'Sozlash chalkash edi',
    'Xato, sekinlashish yoki moslik muammosini keltirdi',
    'Endi menga kerak emas',
    'Maxfiylik yoki ruxsatlar bo‘yicha xavotir',
    'Boshqa',
    'Nima bo‘ldi yoki buning o‘rniga nimani kutgan edingiz?',
    'Ixtiyoriy. Bir-ikki gap yetarli.',
    'Qaysi funksiya sizni yana sinab ko‘rishga undaydi?',
    'Ixtiyoriy.',
    'Javob uchun manzil',
    'Ixtiyoriy. Faqat javob olishni istasangiz kiriting.',
    'Fikr yuborish',
    'Fikr Formspree tomonidan qayta ishlanadi.',
    'Manba'
  ])
};
