export const LOCALE_COPY_GROUP_1 = {
  "ar": {
    "pageTitle": "ملاحظات YouTube Mix Blocker",
    "metaDescription": "ملاحظات اختيارية بعد إلغاء تثبيت YouTube Mix Blocker.",
    "brandHomeLabel": "الصفحة الرئيسية لأوليكساندر مولودتشيك",
    "navLabel": "التنقل الرئيسي",
    "navProjects": "المشاريع",
    "navNow": "الآن",
    "navAbout": "حول",
    "navContact": "تواصل",
    "headline": "ساعد في تحسين الإضافة",
    "intro": "إذا لم يلب YouTube Mix Blocker توقعاتك، تكفي ملاحظة قصيرة. هذا النموذج اختياري ولا يتطلب معلومات تواصل.",
    "privacyNote": "تفتح الإضافة هذه الصفحة بعد إلغاء التثبيت مع معلمات عامة فقط: المصدر والإصدار ولغة المتصفح. لا تدرج بيانات شخصية إلا إذا كنت تريد مشاركتها عمدا.",
    "reasonLabel": "لماذا ألغيت التثبيت؟",
    "chooseOne": "اختر سببا",
    "reasonNotEnough": "لم يحظر ما يكفي من YouTube Mixes",
    "reasonBlockedIncorrectly": "حظر أو غيّر شيئا بشكل غير صحيح",
    "reasonLayoutLanguage": "لم يعمل مع تخطيط YouTube أو لغتي",
    "reasonConfiguration": "كان ضبطه مربكا",
    "reasonBugSlowdown": "سبب خللا أو بطئا أو مشكلة توافق",
    "reasonNoLongerNeeded": "لم أعد بحاجة إليه",
    "reasonPrivacyPermissions": "مشكلة خصوصية أو أذونات",
    "reasonOther": "غير ذلك",
    "detailsLabel": "ماذا حدث، أو ماذا كنت تتوقع بدلا من ذلك؟",
    "detailsHelp": "اختياري. تكفي جملة أو جملتان.",
    "featureLabel": "ما الميزة التي قد تجعلك تجربه مرة أخرى؟",
    "featureHelp": "اختياري.",
    "contactLabel": "عنوان للرد",
    "contactHelp": "اختياري. أضفه فقط إذا كنت تريد ردا.",
    "submit": "إرسال الملاحظات",
    "status": "تتم معالجة الملاحظات عبر Formspree.",
    "footerSource": "المصدر"
  },
  "ca": {
    "pageTitle": "Comentaris de YouTube Mix Blocker",
    "metaDescription": "Comentaris opcionals després de desinstal·lar YouTube Mix Blocker.",
    "brandHomeLabel": "Inici d'Oleksandr Molodchyk",
    "navLabel": "Navegació principal",
    "navProjects": "Projectes",
    "navNow": "Ara",
    "navAbout": "Sobre mi",
    "navContact": "Contacte",
    "headline": "Ajuda a millorar l'extensió",
    "intro": "Si YouTube Mix Blocker no ha complert les expectatives, una nota breu és suficient. Aquest formulari és opcional i no requereix dades de contacte.",
    "privacyNote": "L'extensió obre aquesta pàgina després de desinstal·lar-la només amb paràmetres genèrics de font, versió i idioma del navegador. No incloguis dades personals tret que les vulguis compartir.",
    "reasonLabel": "Per què l'has desinstal·lada?",
    "chooseOne": "Tria una opció",
    "reasonNotEnough": "No bloquejava prou YouTube Mixes",
    "reasonBlockedIncorrectly": "Bloquejava o canviava alguna cosa incorrectament",
    "reasonLayoutLanguage": "No funcionava amb el meu disseny o idioma de YouTube",
    "reasonConfiguration": "Era confusa de configurar",
    "reasonBugSlowdown": "Causava un error, lentitud o problemes de compatibilitat",
    "reasonNoLongerNeeded": "Ja no la necessito",
    "reasonPrivacyPermissions": "Preocupació de privadesa o permisos",
    "reasonOther": "Altres",
    "detailsLabel": "Què ha passat o què esperaves en lloc d'això?",
    "detailsHelp": "Opcional. Una o dues frases són suficients.",
    "featureLabel": "Quina funció et faria provar-la de nou?",
    "featureHelp": "Opcional.",
    "contactLabel": "Adreça de resposta",
    "contactHelp": "Opcional. Inclou-la només si vols una resposta.",
    "submit": "Envia els comentaris",
    "status": "Els comentaris es processen amb Formspree.",
    "footerSource": "Codi font"
  },
  "cs": {
    "pageTitle": "Zpětná vazba k YouTube Mix Blocker",
    "metaDescription": "Volitelná zpětná vazba po odinstalování YouTube Mix Blocker.",
    "brandHomeLabel": "Domovská stránka Oleksandra Molodchyka",
    "navLabel": "Hlavní navigace",
    "navProjects": "Projekty",
    "navNow": "Teď",
    "navAbout": "O mně",
    "navContact": "Kontakt",
    "headline": "Pomozte rozšíření zlepšit",
    "intro": "Pokud YouTube Mix Blocker nesplnil očekávání, stačí krátká poznámka. Formulář je volitelný a nevyžaduje kontaktní údaje.",
    "privacyNote": "Rozšíření po odinstalování otevře tuto stránku pouze s obecnými parametry zdroje, verze a jazyka prohlížeče. Neuvádějte osobní údaje, pokud je nechcete záměrně sdílet.",
    "reasonLabel": "Proč jste rozšíření odinstalovali?",
    "chooseOne": "Vyberte jednu možnost",
    "reasonNotEnough": "Nefiltrovalo dost YouTube Mixů",
    "reasonBlockedIncorrectly": "Něco blokovalo nebo měnilo nesprávně",
    "reasonLayoutLanguage": "Nefungovalo v mém rozložení nebo jazyce YouTube",
    "reasonConfiguration": "Nastavení bylo matoucí",
    "reasonBugSlowdown": "Způsobovalo chybu, zpomalení nebo problém s kompatibilitou",
    "reasonNoLongerNeeded": "Už ho nepotřebuji",
    "reasonPrivacyPermissions": "Obava o soukromí nebo oprávnění",
    "reasonOther": "Jiné",
    "detailsLabel": "Co se stalo nebo co jste očekávali místo toho?",
    "detailsHelp": "Volitelné. Stačí jedna nebo dvě věty.",
    "featureLabel": "Jaká funkce by vás přiměla rozšíření zkusit znovu?",
    "featureHelp": "Volitelné.",
    "contactLabel": "Adresa pro odpověď",
    "contactHelp": "Volitelné. Uveďte ji jen tehdy, pokud chcete odpověď.",
    "submit": "Odeslat zpětnou vazbu",
    "status": "Zpětnou vazbu zpracovává Formspree.",
    "footerSource": "Zdroj"
  },
  "de": {
    "pageTitle": "Feedback zu YouTube Mix Blocker",
    "metaDescription": "Optionales Feedback nach der Deinstallation von YouTube Mix Blocker.",
    "brandHomeLabel": "Startseite von Oleksandr Molodchyk",
    "navLabel": "Hauptnavigation",
    "navProjects": "Projekte",
    "navNow": "Jetzt",
    "navAbout": "Über mich",
    "navContact": "Kontakt",
    "headline": "Hilf mit, die Erweiterung zu verbessern",
    "intro": "Wenn YouTube Mix Blocker deine Erwartungen nicht erfüllt hat, reicht eine kurze Notiz. Dieses Formular ist optional und erfordert keine Kontaktdaten.",
    "privacyNote": "Die Erweiterung öffnet diese Seite nach der Deinstallation nur mit allgemeinen Parametern für Quelle, Version und Browsersprache. Gib keine personenbezogenen Daten an, außer du möchtest sie bewusst teilen.",
    "reasonLabel": "Warum hast du deinstalliert?",
    "chooseOne": "Bitte auswählen",
    "reasonNotEnough": "Es wurden nicht genug YouTube Mixes blockiert",
    "reasonBlockedIncorrectly": "Es wurde etwas fälschlicherweise blockiert oder verändert",
    "reasonLayoutLanguage": "Es funktionierte nicht mit meinem YouTube-Layout oder meiner Sprache",
    "reasonConfiguration": "Die Konfiguration war verwirrend",
    "reasonBugSlowdown": "Es gab einen Fehler, eine Verlangsamung oder ein Kompatibilitätsproblem",
    "reasonNoLongerNeeded": "Ich brauche es nicht mehr",
    "reasonPrivacyPermissions": "Datenschutz- oder Berechtigungsbedenken",
    "reasonOther": "Sonstiges",
    "detailsLabel": "Was ist passiert oder was hast du stattdessen erwartet?",
    "detailsHelp": "Optional. Ein oder zwei Sätze reichen.",
    "featureLabel": "Welche Funktion würde dich dazu bringen, es erneut zu versuchen?",
    "featureHelp": "Optional.",
    "contactLabel": "Antwortadresse",
    "contactHelp": "Optional. Nur angeben, wenn du eine Antwort möchtest.",
    "submit": "Feedback senden",
    "status": "Feedback wird über Formspree verarbeitet.",
    "footerSource": "Quellcode"
  },
  "es": {
    "pageTitle": "Comentarios sobre YouTube Mix Blocker",
    "metaDescription": "Comentarios opcionales tras desinstalar YouTube Mix Blocker.",
    "brandHomeLabel": "Inicio de Oleksandr Molodchyk",
    "navLabel": "Navegación principal",
    "navProjects": "Proyectos",
    "navNow": "Ahora",
    "navAbout": "Acerca de",
    "navContact": "Contacto",
    "headline": "Ayuda a mejorar la extensión",
    "intro": "Si YouTube Mix Blocker no cumplió tus expectativas, una nota breve es suficiente. Este formulario es opcional y no requiere información de contacto.",
    "privacyNote": "La extensión abre esta página después de desinstalarse solo con parámetros genéricos de origen, versión e idioma del navegador. No incluyas datos personales salvo que quieras compartirlos intencionalmente.",
    "reasonLabel": "¿Por qué la desinstalaste?",
    "chooseOne": "Elige una opción",
    "reasonNotEnough": "No bloqueó suficientes YouTube Mixes",
    "reasonBlockedIncorrectly": "Bloqueó o cambió algo incorrectamente",
    "reasonLayoutLanguage": "No funcionó con mi diseño o idioma de YouTube",
    "reasonConfiguration": "Era confusa de configurar",
    "reasonBugSlowdown": "Causó un error, lentitud o problema de compatibilidad",
    "reasonNoLongerNeeded": "Ya no la necesito",
    "reasonPrivacyPermissions": "Preocupación por privacidad o permisos",
    "reasonOther": "Otro",
    "detailsLabel": "¿Qué pasó o qué esperabas en su lugar?",
    "detailsHelp": "Opcional. Una o dos frases son suficientes.",
    "featureLabel": "¿Qué función haría que la probaras de nuevo?",
    "featureHelp": "Opcional.",
    "contactLabel": "Dirección para responder",
    "contactHelp": "Opcional. Inclúyela solo si quieres una respuesta.",
    "submit": "Enviar comentarios",
    "status": "Los comentarios se procesan con Formspree.",
    "footerSource": "Código fuente"
  }
};
