const keys = [
  'pageTitle',
  'metaDescription',
  'brandHomeLabel',
  'navLabel',
  'navProjects',
  'navNow',
  'navAbout',
  'navContact',
  'headline',
  'intro',
  'privacyNote',
  'reasonLabel',
  'chooseOne',
  'reasonNotEnough',
  'reasonBlockedIncorrectly',
  'reasonLayoutLanguage',
  'reasonConfiguration',
  'reasonBugSlowdown',
  'reasonNoLongerNeeded',
  'reasonPrivacyPermissions',
  'reasonOther',
  'detailsLabel',
  'detailsHelp',
  'featureLabel',
  'featureHelp',
  'contactLabel',
  'contactHelp',
  'submit',
  'status',
  'footerSource'
];

function makeCopy(values) {
  return Object.fromEntries(keys.map((key, index) => [key, values[index]]));
}

export const LOCALE_COPY_GROUP_7 = {
  am: makeCopy([
    'የYouTube Mix Blocker አስተያየት',
    'YouTube Mix Blockerን ካስወገዱ በኋላ አማራጭ አስተያየት።',
    'የOleksandr Molodchyk መነሻ ገጽ',
    'ዋና አሰሳ',
    'ፕሮጀክቶች',
    'አሁን',
    'ስለ',
    'እውቂያ',
    'ቅጥያውን ለማሻሻል ይርዱ',
    'YouTube Mix Blocker የጠበቁትን ካላሟላ፣ አጭር ማስታወሻ በቂ ነው። ይህ ቅጽ አማራጭ ነው እና የእውቂያ መረጃ አይጠይቅም።',
    'ቅጥያው ከተወገደ በኋላ ይህን ገጽ የሚከፍተው የምንጭ፣ የስሪት እና የአሳሽ ቋንቋ አጠቃላይ መለኪያዎችን ብቻ በመጠቀም ነው። ሆን ብለው ማጋራት ካልፈለጉ የግል መረጃ አያስገቡ።',
    'ለምን አስወገዱት?',
    'አንዱን ይምረጡ',
    'በቂ YouTube Mixes አላገደም',
    'አንድ ነገር በስህተት አገደ ወይም ቀየረ',
    'በእኔ YouTube አቀማመጥ ወይም ቋንቋ ላይ አልሰራም',
    'ማዋቀሩ ግራ የሚያጋባ ነበር',
    'ስህተት፣ መቀዝቀዝ ወይም የተኳኋኝነት ችግኝ ፈጠረ',
    'ከእንግዲህ አልፈልገውም',
    'የግላዊነት ወይም የፍቃድ ጭንቀት',
    'ሌላ',
    'ምን ተፈጠረ ወይም በምትኩ ምን ጠበቁ?',
    'አማራጭ። አንድ ወይም ሁለት ዓረፍተ ነገር በቂ ነው።',
    'እንደገና እንዲሞክሩት የሚያደርግ ምን ባህሪ ነው?',
    'አማራጭ።',
    'የመልስ አድራሻ',
    'አማራጭ። መልስ ከፈለጉ ብቻ ያክሉት።',
    'አስተያየት ላክ',
    'አስተያየት በFormspree ይሰራል።',
    'ምንጭ'
  ]),
  az: makeCopy([
    'YouTube Mix Blocker rəyi',
    'YouTube Mix Blocker silindikdən sonra istəyə bağlı rəy.',
    'Oleksandr Molodchyk ana səhifəsi',
    'Əsas naviqasiya',
    'Layihələr',
    'İndi',
    'Haqqında',
    'Əlaqə',
    'Genişlənməni yaxşılaşdırmağa kömək edin',
    'YouTube Mix Blocker gözləntilərinizi qarşılamadısa, qısa bir qeyd kifayətdir. Bu forma istəyə bağlıdır və əlaqə məlumatı tələb etmir.',
    'Genişlənmə silindikdən sonra bu səhifəni yalnız ümumi mənbə, versiya və brauzer dili parametrləri ilə açır. Şəxsi məlumatları yalnız bilərəkdən paylaşmaq istəyirsinizsə daxil edin.',
    'Niyə sildiniz?',
    'Birini seçin',
    'Kifayət qədər YouTube Mixes bloklamadı',
    'Nəyisə səhv blokladı və ya dəyişdi',
    'Mənim YouTube düzənimdə və ya dilimdə işləmədi',
    'Quraşdırmaq çaşdırıcı idi',
    'Xəta, yavaşlama və ya uyğunluq problemi yaratdı',
    'Artıq ehtiyacım yoxdur',
    'Məxfilik və ya icazə narahatlığı',
    'Digər',
    'Nə baş verdi və ya əvəzində nə gözləyirdiniz?',
    'İstəyə bağlıdır. Bir-iki cümlə kifayətdir.',
    'Hansı xüsusiyyət sizi yenidən sınamağa vadar edərdi?',
    'İstəyə bağlıdır.',
    'Cavab ünvanı',
    'İstəyə bağlıdır. Yalnız cavab istəyirsinizsə əlavə edin.',
    'Rəy göndər',
    'Rəy Formspree tərəfindən emal olunur.',
    'Mənbə'
  ]),
  bg: makeCopy([
    'Обратна връзка за YouTube Mix Blocker',
    'Незадължителна обратна връзка след деинсталиране на YouTube Mix Blocker.',
    'Начална страница на Oleksandr Molodchyk',
    'Основна навигация',
    'Проекти',
    'Сега',
    'За мен',
    'Контакт',
    'Помогнете за подобряване на разширението',
    'Ако YouTube Mix Blocker не отговори на очакванията ви, кратка бележка е достатъчна. Този формуляр е незадължителен и не изисква данни за контакт.',
    'Разширението отваря тази страница след деинсталиране само с общи параметри за източник, версия и език на браузъра. Не включвайте лични данни, освен ако умишлено искате да ги споделите.',
    'Защо деинсталирахте?',
    'Изберете едно',
    'Не блокира достатъчно YouTube Mixes',
    'Блокира или промени нещо неправилно',
    'Не работеше с моя изглед или език в YouTube',
    'Беше объркващо за настройване',
    'Причини грешка, забавяне или проблем със съвместимостта',
    'Вече не ми трябва',
    'Притеснение за поверителност или разрешения',
    'Друго',
    'Какво се случи или какво очаквахте вместо това?',
    'Незадължително. Едно-две изречения са достатъчни.',
    'Коя функция би ви накарала да го пробвате отново?',
    'Незадължително.',
    'Адрес за отговор',
    'Незадължително. Добавете го само ако искате отговор.',
    'Изпрати обратна връзка',
    'Обратната връзка се обработва чрез Formspree.',
    'Изходен код'
  ]),
  bn: makeCopy([
    'YouTube Mix Blocker প্রতিক্রিয়া',
    'YouTube Mix Blocker আনইনস্টল করার পর ঐচ্ছিক প্রতিক্রিয়া।',
    'Oleksandr Molodchyk হোম',
    'প্রধান নেভিগেশন',
    'প্রকল্প',
    'এখন',
    'সম্পর্কে',
    'যোগাযোগ',
    'এক্সটেনশনটি উন্নত করতে সাহায্য করুন',
    'YouTube Mix Blocker প্রত্যাশা পূরণ না করলে একটি ছোট নোটই যথেষ্ট। এই ফর্মটি ঐচ্ছিক এবং যোগাযোগের তথ্য চায় না।',
    'এক্সটেনশন আনইনস্টল হওয়ার পর এই পৃষ্ঠাটি শুধু সাধারণ source, version এবং browser-language প্যারামিটার নিয়ে খোলে। আপনি ইচ্ছাকৃতভাবে শেয়ার করতে না চাইলে ব্যক্তিগত তথ্য দেবেন না।',
    'কেন আনইনস্টল করলেন?',
    'একটি বেছে নিন',
    'যথেষ্ট YouTube Mixes ব্লক করেনি',
    'ভুলভাবে কিছু ব্লক বা পরিবর্তন করেছে',
    'আমার YouTube layout বা ভাষায় কাজ করেনি',
    'কনফিগার করা বিভ্রান্তিকর ছিল',
    'বাগ, ধীরগতি বা সামঞ্জস্য সমস্যা তৈরি করেছে',
    'এখন আর প্রয়োজন নেই',
    'গোপনীয়তা বা অনুমতি নিয়ে উদ্বেগ',
    'অন্যান্য',
    'কি ঘটেছে বা আপনি কী আশা করেছিলেন?',
    'ঐচ্ছিক। এক-দুইটি বাক্যই যথেষ্ট।',
    'কোন বৈশিষ্ট্য থাকলে আপনি আবার চেষ্টা করতেন?',
    'ঐচ্ছিক।',
    'উত্তরের ঠিকানা',
    'ঐচ্ছিক। উত্তর চাইলে তবেই দিন।',
    'প্রতিক্রিয়া পাঠান',
    'প্রতিক্রিয়া Formspree দ্বারা প্রক্রিয়া করা হয়।',
    'উৎস'
  ]),
  da: makeCopy([
    'Feedback til YouTube Mix Blocker',
    'Valgfri feedback efter afinstallation af YouTube Mix Blocker.',
    'Oleksandr Molodchyks startside',
    'Hovednavigation',
    'Projekter',
    'Nu',
    'Om',
    'Kontakt',
    'Hjælp med at forbedre udvidelsen',
    'Hvis YouTube Mix Blocker ikke levede op til forventningerne, er en kort note nok. Formularen er valgfri og kræver ikke kontaktoplysninger.',
    'Udvidelsen åbner denne side efter afinstallation kun med generelle parametre for kilde, version og browsersprog. Medtag ikke personlige oplysninger, medmindre du bevidst vil dele dem.',
    'Hvorfor afinstallerede du?',
    'Vælg én',
    'Den blokerede ikke nok YouTube Mixes',
    'Den blokerede eller ændrede noget forkert',
    'Den virkede ikke med mit YouTube-layout eller sprog',
    'Den var forvirrende at konfigurere',
    'Den forårsagede en fejl, forsinkelse eller kompatibilitetsproblem',
    'Jeg har ikke længere brug for den',
    'Bekymring om privatliv eller tilladelser',
    'Andet',
    'Hvad skete der, eller hvad forventede du i stedet?',
    'Valgfrit. En eller to sætninger er nok.',
    'Hvilken funktion ville få dig til at prøve den igen?',
    'Valgfrit.',
    'Svaradresse',
    'Valgfrit. Angiv den kun, hvis du ønsker et svar.',
    'Send feedback',
    'Feedback behandles af Formspree.',
    'Kilde'
  ]),
  el: makeCopy([
    'Σχόλια για το YouTube Mix Blocker',
    'Προαιρετικά σχόλια μετά την απεγκατάσταση του YouTube Mix Blocker.',
    'Αρχική σελίδα Oleksandr Molodchyk',
    'Κύρια πλοήγηση',
    'Έργα',
    'Τώρα',
    'Σχετικά',
    'Επικοινωνία',
    'Βοηθήστε να βελτιωθεί η επέκταση',
    'Αν το YouTube Mix Blocker δεν κάλυψε τις προσδοκίες σας, αρκεί ένα σύντομο σχόλιο. Αυτή η φόρμα είναι προαιρετική και δεν απαιτεί στοιχεία επικοινωνίας.',
    'Η επέκταση ανοίγει αυτή τη σελίδα μετά την απεγκατάσταση μόνο με γενικές παραμέτρους πηγής, έκδοσης και γλώσσας προγράμματος περιήγησης. Μην συμπεριλάβετε προσωπικά δεδομένα εκτός αν θέλετε σκόπιμα να τα μοιραστείτε.',
    'Γιατί κάνατε απεγκατάσταση;',
    'Επιλέξτε ένα',
    'Δεν απέκλειε αρκετά YouTube Mixes',
    'Απέκλεισε ή άλλαξε κάτι λανθασμένα',
    'Δεν λειτουργούσε με τη διάταξη ή τη γλώσσα μου στο YouTube',
    'Ήταν μπερδεμένο στη ρύθμιση',
    'Προκάλεσε σφάλμα, καθυστέρηση ή πρόβλημα συμβατότητας',
    'Δεν το χρειάζομαι πλέον',
    'Ανησυχία για ιδιωτικότητα ή δικαιώματα',
    'Άλλο',
    'Τι συνέβη ή τι περιμένατε αντί γι’ αυτό;',
    'Προαιρετικό. Μία ή δύο προτάσεις αρκούν.',
    'Ποια λειτουργία θα σας έκανε να το δοκιμάσετε ξανά;',
    'Προαιρετικό.',
    'Διεύθυνση απάντησης',
    'Προαιρετικό. Συμπληρώστε το μόνο αν θέλετε απάντηση.',
    'Αποστολή σχολίων',
    'Τα σχόλια επεξεργάζονται από το Formspree.',
    'Πηγή'
  ]),
  et: makeCopy([
    'YouTube Mix Blockeri tagasiside',
    'Valikuline tagasiside pärast YouTube Mix Blockeri eemaldamist.',
    'Oleksandr Molodchyki avaleht',
    'Põhinavigeerimine',
    'Projektid',
    'Praegu',
    'Teave',
    'Kontakt',
    'Aita laiendust paremaks teha',
    'Kui YouTube Mix Blocker ei vastanud ootustele, piisab lühikesest märkusest. See vorm on valikuline ega nõua kontaktandmeid.',
    'Laiendus avab selle lehe pärast eemaldamist ainult üldiste allika, versiooni ja brauseri keele parameetritega. Ärge lisage isikuandmeid, välja arvatud juhul, kui soovite neid teadlikult jagada.',
    'Miks eemaldasite laienduse?',
    'Valige üks',
    'See ei blokeerinud piisavalt YouTube Mixe',
    'See blokeeris või muutis midagi valesti',
    'See ei töötanud minu YouTube’i paigutuse või keelega',
    'Seda oli segane seadistada',
    'See põhjustas vea, aeglustumise või ühilduvusprobleemi',
    'Ma ei vaja seda enam',
    'Privaatsuse või lubade mure',
    'Muu',
    'Mis juhtus või mida ootasite selle asemel?',
    'Valikuline. Ühest või kahest lausest piisab.',
    'Milline funktsioon paneks teid seda uuesti proovima?',
    'Valikuline.',
    'Vastuse aadress',
    'Valikuline. Lisage ainult siis, kui soovite vastust.',
    'Saada tagasiside',
    'Tagasisidet töötleb Formspree.',
    'Allikas'
  ]),
  eu: makeCopy([
    'YouTube Mix Blocker-i iritzia',
    'YouTube Mix Blocker desinstalatu ondorengo aukerako iritzia.',
    'Oleksandr Molodchyk-en hasiera',
    'Nabigazio nagusia',
    'Proiektuak',
    'Orain',
    'Honi buruz',
    'Kontaktua',
    'Lagundu luzapena hobetzen',
    'YouTube Mix Blocker-ek espero zenuena bete ez badu, ohar labur bat nahikoa da. Inprimaki hau aukerakoa da eta ez du kontaktu-informaziorik eskatzen.',
    'Luzapenak orri hau desinstalatu ondoren irekitzen du, iturburuaren, bertsioaren eta nabigatzaile-hizkuntzaren parametro orokorrekin bakarrik. Ez sartu datu pertsonalik, berariaz partekatu nahi ez badituzu.',
    'Zergatik desinstalatu duzu?',
    'Aukeratu bat',
    'Ez zituen nahikoa YouTube Mixes blokeatu',
    'Zerbait gaizki blokeatu edo aldatu zuen',
    'Ez zuen nire YouTube diseinuarekin edo hizkuntzarekin funtzionatu',
    'Konfiguratzea nahasgarria zen',
    'Errore bat, moteltzea edo bateragarritasun-arazo bat eragin zuen',
    'Ez dut gehiago behar',
    'Pribatutasun edo baimenen kezka',
    'Beste bat',
    'Zer gertatu zen edo zer espero zenuen horren ordez?',
    'Aukerakoa. Esaldi bat edo bi nahikoa dira.',
    'Zein funtziok bultzatuko zintuzke berriro probatzera?',
    'Aukerakoa.',
    'Erantzuteko helbidea',
    'Aukerakoa. Jarri soilik erantzuna nahi baduzu.',
    'Bidali iritzia',
    'Iritzia Formspree-k prozesatzen du.',
    'Iturburua'
  ]),
  fa: makeCopy([
    'بازخورد YouTube Mix Blocker',
    'بازخورد اختیاری پس از حذف YouTube Mix Blocker.',
    'خانه Oleksandr Molodchyk',
    'ناوبری اصلی',
    'پروژه‌ها',
    'اکنون',
    'درباره',
    'تماس',
    'به بهبود افزونه کمک کنید',
    'اگر YouTube Mix Blocker انتظارتان را برآورده نکرد، یک یادداشت کوتاه کافی است. این فرم اختیاری است و به اطلاعات تماس نیاز ندارد.',
    'افزونه پس از حذف، این صفحه را فقط با پارامترهای عمومی منبع، نسخه و زبان مرورگر باز می‌کند. داده شخصی وارد نکنید مگر اینکه عمداً بخواهید آن را به اشتراک بگذارید.',
    'چرا حذف کردید؟',
    'یکی را انتخاب کنید',
    'به اندازه کافی YouTube Mixes را مسدود نکرد',
    'چیزی را اشتباه مسدود یا تغییر داد',
    'با چیدمان یا زبان YouTube من کار نکرد',
    'پیکربندی آن گیج‌کننده بود',
    'باعث خطا، کندی یا مشکل سازگاری شد',
    'دیگر به آن نیاز ندارم',
    'نگرانی درباره حریم خصوصی یا مجوزها',
    'سایر',
    'چه اتفاقی افتاد یا به جای آن چه انتظاری داشتید؟',
    'اختیاری. یک یا دو جمله کافی است.',
    'چه قابلیتی باعث می‌شود دوباره آن را امتحان کنید؟',
    'اختیاری.',
    'نشانی برای پاسخ',
    'اختیاری. فقط اگر پاسخ می‌خواهید وارد کنید.',
    'ارسال بازخورد',
    'بازخورد توسط Formspree پردازش می‌شود.',
    'منبع'
  ]),
  fi: makeCopy([
    'YouTube Mix Blocker -palaute',
    'Valinnainen palaute YouTube Mix Blockerin poistamisen jälkeen.',
    'Oleksandr Molodchykin etusivu',
    'Päänavigaatio',
    'Projektit',
    'Nyt',
    'Tietoa',
    'Yhteys',
    'Auta parantamaan laajennusta',
    'Jos YouTube Mix Blocker ei vastannut odotuksiasi, lyhyt huomautus riittää. Lomake on valinnainen eikä vaadi yhteystietoja.',
    'Laajennus avaa tämän sivun poistamisen jälkeen vain yleisillä lähde-, versio- ja selaimen kieliparametreilla. Älä lisää henkilötietoja, ellet tarkoituksella halua jakaa niitä.',
    'Miksi poistit sen?',
    'Valitse yksi',
    'Se ei estänyt tarpeeksi YouTube Mixejä',
    'Se esti tai muutti jotain virheellisesti',
    'Se ei toiminut YouTuben asettelullani tai kielelläni',
    'Sen määrittäminen oli sekavaa',
    'Se aiheutti virheen, hidastumisen tai yhteensopivuusongelman',
    'En tarvitse sitä enää',
    'Yksityisyys- tai käyttöoikeushuoli',
    'Muu',
    'Mitä tapahtui tai mitä odotit sen sijaan?',
    'Valinnainen. Yksi tai kaksi lausetta riittää.',
    'Mikä ominaisuus saisi sinut kokeilemaan sitä uudelleen?',
    'Valinnainen.',
    'Vastausosoite',
    'Valinnainen. Lisää vain, jos haluat vastauksen.',
    'Lähetä palaute',
    'Palaute käsitellään Formspreen kautta.',
    'Lähde'
  ]),
  gu: makeCopy([
    'YouTube Mix Blocker પ્રતિસાદ',
    'YouTube Mix Blocker અનઇન્સ્ટોલ કર્યા પછી વૈકલ્પિક પ્રતિસાદ.',
    'Oleksandr Molodchyk હોમ',
    'મુખ્ય નેવિગેશન',
    'પ્રોજેક્ટ્સ',
    'હમણાં',
    'વિશે',
    'સંપર્ક',
    'એક્સ્ટેન્શન સુધારવામાં મદદ કરો',
    'જો YouTube Mix Blocker તમારી અપેક્ષાઓ પર ખરો ન ઉતર્યો હોય, તો ટૂંકી નોંધ પૂરતી છે. આ ફોર્મ વૈકલ્પિક છે અને સંપર્ક માહિતી જરૂરી નથી.',
    'એક્સ્ટેન્શન અનઇન્સ્ટોલ થયા પછી આ પૃષ્ઠ માત્ર સામાન્ય source, version અને browser-language પરિમાણો સાથે ખોલે છે. તમે જાણબૂઝીને શેર કરવા ન માંગતા હોવ તો વ્યક્તિગત માહિતી ન આપો.',
    'તમે તેને શા માટે અનઇન્સ્ટોલ કર્યું?',
    'એક પસંદ કરો',
    'તે પૂરતા YouTube Mixes બ્લોક કરતું નહોતું',
    'તે કંઈક ખોટી રીતે બ્લોક અથવા બદલતું હતું',
    'તે મારા YouTube લેઆઉટ અથવા ભાષા સાથે કામ કરતું નહોતું',
    'તે ગોઠવવું ગૂંચવણભર્યું હતું',
    'તેના કારણે બગ, ધીમું પડવું અથવા સુસંગતતા સમસ્યા થઈ',
    'હવે મને તેની જરૂર નથી',
    'ગોપનીયતા અથવા પરવાનગીઓ અંગે ચિંતા',
    'અન્ય',
    'શું થયું અથવા તેના બદલે તમે શું અપેક્ષા રાખી હતી?',
    'વૈકલ્પિક. એક કે બે વાક્ય પૂરતા છે.',
    'કઈ સુવિધા તમને તેને ફરી અજમાવવા પ્રેરિત કરશે?',
    'વૈકલ્પિક.',
    'જવાબ માટેનું સરનામું',
    'વૈકલ્પિક. જવાબ જોઈએ તો જ ઉમેરો.',
    'પ્રતિસાદ મોકલો',
    'પ્રતિસાદ Formspree દ્વારા પ્રક્રિયા થાય છે.',
    'સ્ત્રોત'
  ]),
  he: makeCopy([
    'משוב על YouTube Mix Blocker',
    'משוב אופציונלי לאחר הסרת YouTube Mix Blocker.',
    'דף הבית של Oleksandr Molodchyk',
    'ניווט ראשי',
    'פרויקטים',
    'עכשיו',
    'אודות',
    'יצירת קשר',
    'עזרו לשפר את התוסף',
    'אם YouTube Mix Blocker לא עמד בציפיות, מספיקה הערה קצרה. הטופס הזה אופציונלי ואינו דורש פרטי קשר.',
    'התוסף פותח את הדף הזה לאחר ההסרה רק עם פרמטרים כלליים של מקור, גרסה ושפת הדפדפן. אל תכללו מידע אישי אלא אם אתם רוצים לשתף אותו במכוון.',
    'למה הסרתם?',
    'בחרו אפשרות אחת',
    'הוא לא חסם מספיק YouTube Mixes',
    'הוא חסם או שינה משהו בטעות',
    'הוא לא עבד עם פריסת YouTube או השפה שלי',
    'ההגדרה שלו הייתה מבלבלת',
    'הוא גרם לתקלה, האטה או בעיית תאימות',
    'אני כבר לא צריך אותו',
    'חשש מפרטיות או מהרשאות',
    'אחר',
    'מה קרה או מה ציפיתם במקום זאת?',
    'אופציונלי. משפט או שניים מספיקים.',
    'איזו תכונה תגרום לכם לנסות אותו שוב?',
    'אופציונלי.',
    'כתובת לתשובה',
    'אופציונלי. הוסיפו רק אם אתם רוצים תשובה.',
    'שליחת משוב',
    'המשוב מעובד באמצעות Formspree.',
    'מקור'
  ])
};
