export const LOCALE_COPY_GROUP_4 = {
  "vi": {
    "pageTitle": "Phản hồi về YouTube Mix Blocker",
    "metaDescription": "Phản hồi tùy chọn sau khi gỡ cài đặt YouTube Mix Blocker.",
    "brandHomeLabel": "Trang chủ Oleksandr Molodchyk",
    "navLabel": "Điều hướng chính",
    "navProjects": "Dự án",
    "navNow": "Hiện tại",
    "navAbout": "Giới thiệu",
    "navContact": "Liên hệ",
    "headline": "Giúp cải thiện tiện ích",
    "intro": "Nếu YouTube Mix Blocker chưa đáp ứng kỳ vọng, một ghi chú ngắn là đủ. Biểu mẫu này là tùy chọn và không yêu cầu thông tin liên hệ.",
    "privacyNote": "Tiện ích mở trang này sau khi gỡ cài đặt chỉ với các tham số chung về nguồn, phiên bản và ngôn ngữ trình duyệt. Đừng gửi dữ liệu cá nhân trừ khi bạn chủ động muốn chia sẻ.",
    "reasonLabel": "Vì sao bạn gỡ cài đặt?",
    "chooseOne": "Chọn một lý do",
    "reasonNotEnough": "Không chặn đủ YouTube Mix",
    "reasonBlockedIncorrectly": "Chặn hoặc thay đổi nhầm thứ gì đó",
    "reasonLayoutLanguage": "Không hoạt động với bố cục hoặc ngôn ngữ YouTube của tôi",
    "reasonConfiguration": "Khó cấu hình",
    "reasonBugSlowdown": "Gây lỗi, chậm hoặc vấn đề tương thích",
    "reasonNoLongerNeeded": "Tôi không còn cần nữa",
    "reasonPrivacyPermissions": "Lo ngại về quyền riêng tư hoặc quyền truy cập",
    "reasonOther": "Khác",
    "detailsLabel": "Điều gì đã xảy ra hoặc bạn mong đợi điều gì?",
    "detailsHelp": "Tùy chọn. Một hoặc hai câu là đủ.",
    "featureLabel": "Tính năng nào sẽ khiến bạn thử lại?",
    "featureHelp": "Tùy chọn.",
    "contactLabel": "Địa chỉ nhận trả lời",
    "contactHelp": "Tùy chọn. Chỉ điền nếu bạn muốn nhận phản hồi.",
    "submit": "Gửi phản hồi",
    "status": "Phản hồi được xử lý bởi Formspree.",
    "footerSource": "Mã nguồn"
  },
  "zh_TW": {
    "pageTitle": "YouTube Mix Blocker 意見回饋",
    "metaDescription": "解除安裝 YouTube Mix Blocker 後的選填回饋。",
    "brandHomeLabel": "Oleksandr Molodchyk 首頁",
    "navLabel": "主要導覽",
    "navProjects": "專案",
    "navNow": "近況",
    "navAbout": "關於",
    "navContact": "聯絡",
    "headline": "協助改進這個擴充功能",
    "intro": "如果 YouTube Mix Blocker 沒有符合你的期待，留下一段簡短說明就很有幫助。此表單為選填，不需要聯絡資訊。",
    "privacyNote": "擴充功能會在解除安裝後開啟此頁，只附上來源、版本和瀏覽器語言等一般參數。除非你有意分享，請不要填寫個人資料。",
    "reasonLabel": "你為什麼解除安裝？",
    "chooseOne": "選擇一項",
    "reasonNotEnough": "沒有封鎖足夠多的 YouTube Mix",
    "reasonBlockedIncorrectly": "錯誤封鎖或變更了某些內容",
    "reasonLayoutLanguage": "無法在我的 YouTube 版面或語言中運作",
    "reasonConfiguration": "設定方式令人困惑",
    "reasonBugSlowdown": "造成錯誤、變慢或相容性問題",
    "reasonNoLongerNeeded": "我不再需要它",
    "reasonPrivacyPermissions": "隱私或權限疑慮",
    "reasonOther": "其他",
    "detailsLabel": "發生了什麼事，或你原本期待什麼？",
    "detailsHelp": "選填。一兩句話即可。",
    "featureLabel": "什麼功能會讓你願意再試一次？",
    "featureHelp": "選填。",
    "contactLabel": "回覆地址",
    "contactHelp": "選填。只有在你想收到回覆時才填寫。",
    "submit": "送出回饋",
    "status": "回饋由 Formspree 處理。",
    "footerSource": "原始碼"
  },
  "zh_CN": {
    "pageTitle": "YouTube Mix Blocker 反馈",
    "metaDescription": "卸载 YouTube Mix Blocker 后的可选反馈。",
    "brandHomeLabel": "Oleksandr Molodchyk 主页",
    "navLabel": "主导航",
    "navProjects": "项目",
    "navNow": "近况",
    "navAbout": "关于",
    "navContact": "联系",
    "headline": "帮助改进这个扩展",
    "intro": "如果 YouTube Mix Blocker 没有达到预期，留下一条简短说明就足够了。此表单为可选项，不需要联系方式。",
    "privacyNote": "扩展会在卸载后打开此页面，只带有来源、版本和浏览器语言等通用参数。除非你有意分享，请不要填写个人数据。",
    "reasonLabel": "你为什么卸载？",
    "chooseOne": "选择一项",
    "reasonNotEnough": "没有屏蔽足够多的 YouTube Mix",
    "reasonBlockedIncorrectly": "错误地屏蔽或更改了某些内容",
    "reasonLayoutLanguage": "不适用于我的 YouTube 布局或语言",
    "reasonConfiguration": "配置起来令人困惑",
    "reasonBugSlowdown": "导致错误、变慢或兼容性问题",
    "reasonNoLongerNeeded": "我不再需要它",
    "reasonPrivacyPermissions": "隐私或权限方面的担忧",
    "reasonOther": "其他",
    "detailsLabel": "发生了什么，或者你原本期待什么？",
    "detailsHelp": "可选。一两句话就够了。",
    "featureLabel": "什么功能会让你愿意再试一次？",
    "featureHelp": "可选。",
    "contactLabel": "回复地址",
    "contactHelp": "可选。只有在你想收到回复时才填写。",
    "submit": "发送反馈",
    "status": "反馈由 Formspree 处理。",
    "footerSource": "源代码"
  },
  "fil": {
    "pageTitle": "Feedback para sa YouTube Mix Blocker",
    "metaDescription": "Opsyonal na feedback pagkatapos i-uninstall ang YouTube Mix Blocker.",
    "brandHomeLabel": "Home ni Oleksandr Molodchyk",
    "navLabel": "Pangunahing nabigasyon",
    "navProjects": "Mga proyekto",
    "navNow": "Ngayon",
    "navAbout": "Tungkol",
    "navContact": "Contact",
    "headline": "Tumulong pagandahin ang extension",
    "intro": "Kung hindi tumama ang YouTube Mix Blocker sa inaasahan mo, sapat na ang maikling tala. Opsyonal ang form na ito at hindi nangangailangan ng contact information.",
    "privacyNote": "Binubuksan ng extension ang pahinang ito pagkatapos i-uninstall gamit lang ang pangkalahatang source, version, at browser-language parameters. Huwag maglagay ng personal data maliban kung sinasadya mong ibahagi ito.",
    "reasonLabel": "Bakit mo ito in-uninstall?",
    "chooseOne": "Pumili ng isa",
    "reasonNotEnough": "Hindi sapat ang na-block na YouTube Mixes",
    "reasonBlockedIncorrectly": "May maling na-block o nabago",
    "reasonLayoutLanguage": "Hindi gumana sa aking YouTube layout o wika",
    "reasonConfiguration": "Nakakalito itong i-configure",
    "reasonBugSlowdown": "Nagdulot ito ng bug, pagbagal, o compatibility issue",
    "reasonNoLongerNeeded": "Hindi ko na ito kailangan",
    "reasonPrivacyPermissions": "Alalahanin sa privacy o permissions",
    "reasonOther": "Iba pa",
    "detailsLabel": "Ano ang nangyari o ano ang inaasahan mo?",
    "detailsHelp": "Opsyonal. Sapat na ang isa o dalawang pangungusap.",
    "featureLabel": "Anong feature ang magpapasubok sa iyo ulit?",
    "featureHelp": "Opsyonal.",
    "contactLabel": "Address para sa reply",
    "contactHelp": "Opsyonal. Ilagay lang ito kung gusto mo ng reply.",
    "submit": "Ipadala ang feedback",
    "status": "Pinoproseso ang feedback sa Formspree.",
    "footerSource": "Source"
  },
  "hi": {
    "pageTitle": "YouTube Mix Blocker प्रतिक्रिया",
    "metaDescription": "YouTube Mix Blocker हटाने के बाद वैकल्पिक प्रतिक्रिया।",
    "brandHomeLabel": "Oleksandr Molodchyk होम",
    "navLabel": "मुख्य नेविगेशन",
    "navProjects": "प्रोजेक्ट",
    "navNow": "अभी",
    "navAbout": "परिचय",
    "navContact": "संपर्क",
    "headline": "एक्सटेंशन को बेहतर बनाने में मदद करें",
    "intro": "अगर YouTube Mix Blocker आपकी अपेक्षा पर खरा नहीं उतरा, तो एक छोटा नोट काफी है। यह फ़ॉर्म वैकल्पिक है और संपर्क जानकारी की आवश्यकता नहीं है।",
    "privacyNote": "एक्सटेंशन अनइंस्टॉल होने के बाद यह पेज केवल सामान्य source, version और browser-language पैरामीटर के साथ खोलता है। व्यक्तिगत डेटा शामिल न करें, जब तक आप जानबूझकर उसे साझा नहीं करना चाहते।",
    "reasonLabel": "आपने इसे क्यों हटाया?",
    "chooseOne": "एक विकल्प चुनें",
    "reasonNotEnough": "इसने पर्याप्त YouTube Mixes ब्लॉक नहीं किए",
    "reasonBlockedIncorrectly": "इसने कुछ गलत तरीके से ब्लॉक या बदल दिया",
    "reasonLayoutLanguage": "यह मेरे YouTube लेआउट या भाषा पर काम नहीं किया",
    "reasonConfiguration": "इसे कॉन्फ़िगर करना उलझनभरा था",
    "reasonBugSlowdown": "इससे बग, धीमापन या compatibility समस्या हुई",
    "reasonNoLongerNeeded": "अब मुझे इसकी जरूरत नहीं है",
    "reasonPrivacyPermissions": "गोपनीयता या permission की चिंता",
    "reasonOther": "अन्य",
    "detailsLabel": "क्या हुआ या आप क्या अपेक्षा कर रहे थे?",
    "detailsHelp": "वैकल्पिक। एक या दो वाक्य काफी हैं।",
    "featureLabel": "कौन-सा फीचर आपको इसे फिर आजमाने के लिए प्रेरित करेगा?",
    "featureHelp": "वैकल्पिक।",
    "contactLabel": "उत्तर के लिए पता",
    "contactHelp": "वैकल्पिक। केवल तभी जोड़ें जब आप उत्तर चाहते हैं।",
    "submit": "प्रतिक्रिया भेजें",
    "status": "प्रतिक्रिया Formspree द्वारा संसाधित की जाती है।",
    "footerSource": "स्रोत"
  }
};
