export const LOCALE_COPY_GROUP_2 = {
  "fr": {
    "pageTitle": "Retour sur YouTube Mix Blocker",
    "metaDescription": "Retour facultatif après la désinstallation de YouTube Mix Blocker.",
    "brandHomeLabel": "Accueil d'Oleksandr Molodchyk",
    "navLabel": "Navigation principale",
    "navProjects": "Projets",
    "navNow": "Maintenant",
    "navAbout": "À propos",
    "navContact": "Contact",
    "headline": "Aidez à améliorer l'extension",
    "intro": "Si YouTube Mix Blocker n'a pas répondu à vos attentes, une courte note suffit. Ce formulaire est facultatif et ne demande pas de coordonnées.",
    "privacyNote": "L'extension ouvre cette page après la désinstallation avec uniquement des paramètres génériques de source, de version et de langue du navigateur. N'indiquez pas de données personnelles sauf si vous voulez les partager volontairement.",
    "reasonLabel": "Pourquoi l'avez-vous désinstallée ?",
    "chooseOne": "Choisir une option",
    "reasonNotEnough": "Elle ne bloquait pas assez de YouTube Mixes",
    "reasonBlockedIncorrectly": "Elle bloquait ou modifiait quelque chose à tort",
    "reasonLayoutLanguage": "Elle ne fonctionnait pas avec ma mise en page ou ma langue YouTube",
    "reasonConfiguration": "Elle était confuse à configurer",
    "reasonBugSlowdown": "Elle causait un bug, un ralentissement ou un problème de compatibilité",
    "reasonNoLongerNeeded": "Je n'en ai plus besoin",
    "reasonPrivacyPermissions": "Préoccupation liée à la confidentialité ou aux autorisations",
    "reasonOther": "Autre",
    "detailsLabel": "Que s'est-il passé ou qu'attendiez-vous à la place ?",
    "detailsHelp": "Facultatif. Une ou deux phrases suffisent.",
    "featureLabel": "Quelle fonctionnalité vous ferait réessayer ?",
    "featureHelp": "Facultatif.",
    "contactLabel": "Adresse de réponse",
    "contactHelp": "Facultatif. À inclure uniquement si vous souhaitez une réponse.",
    "submit": "Envoyer le retour",
    "status": "Le retour est traité par Formspree.",
    "footerSource": "Source"
  },
  "hr": {
    "pageTitle": "Povratne informacije za YouTube Mix Blocker",
    "metaDescription": "Neobavezne povratne informacije nakon deinstalacije YouTube Mix Blockera.",
    "brandHomeLabel": "Početna stranica Oleksandra Molodchyka",
    "navLabel": "Glavna navigacija",
    "navProjects": "Projekti",
    "navNow": "Sada",
    "navAbout": "O meni",
    "navContact": "Kontakt",
    "headline": "Pomozite poboljšati proširenje",
    "intro": "Ako YouTube Mix Blocker nije ispunio očekivanja, dovoljna je kratka napomena. Ovaj je obrazac neobavezan i ne traži kontaktne podatke.",
    "privacyNote": "Proširenje otvara ovu stranicu nakon deinstalacije samo s općim parametrima izvora, verzije i jezika preglednika. Nemojte unositi osobne podatke osim ako ih namjerno želite podijeliti.",
    "reasonLabel": "Zašto ste deinstalirali?",
    "chooseOne": "Odaberite jednu opciju",
    "reasonNotEnough": "Nije blokiralo dovoljno YouTube Mixeva",
    "reasonBlockedIncorrectly": "Nešto je pogrešno blokiralo ili promijenilo",
    "reasonLayoutLanguage": "Nije radilo s mojim YouTube rasporedom ili jezikom",
    "reasonConfiguration": "Konfiguracija je bila zbunjujuća",
    "reasonBugSlowdown": "Uzrokovalo je grešku, usporenje ili problem kompatibilnosti",
    "reasonNoLongerNeeded": "Više mi ne treba",
    "reasonPrivacyPermissions": "Briga oko privatnosti ili dopuštenja",
    "reasonOther": "Ostalo",
    "detailsLabel": "Što se dogodilo ili što ste očekivali umjesto toga?",
    "detailsHelp": "Neobavezno. Dovoljna je jedna ili dvije rečenice.",
    "featureLabel": "Koja bi vas značajka navela da pokušate ponovno?",
    "featureHelp": "Neobavezno.",
    "contactLabel": "Adresa za odgovor",
    "contactHelp": "Neobavezno. Uključite samo ako želite odgovor.",
    "submit": "Pošalji povratne informacije",
    "status": "Povratne informacije obrađuje Formspree.",
    "footerSource": "Izvor"
  },
  "id": {
    "pageTitle": "Masukan YouTube Mix Blocker",
    "metaDescription": "Masukan opsional setelah menghapus YouTube Mix Blocker.",
    "brandHomeLabel": "Beranda Oleksandr Molodchyk",
    "navLabel": "Navigasi utama",
    "navProjects": "Proyek",
    "navNow": "Sekarang",
    "navAbout": "Tentang",
    "navContact": "Kontak",
    "headline": "Bantu tingkatkan ekstensi",
    "intro": "Jika YouTube Mix Blocker belum sesuai harapan, satu catatan singkat sudah cukup. Formulir ini opsional dan tidak memerlukan informasi kontak.",
    "privacyNote": "Ekstensi membuka halaman ini setelah dihapus hanya dengan parameter umum sumber, versi, dan bahasa browser. Jangan sertakan data pribadi kecuali Anda memang ingin membagikannya.",
    "reasonLabel": "Mengapa Anda menghapusnya?",
    "chooseOne": "Pilih satu",
    "reasonNotEnough": "Tidak memblokir cukup banyak YouTube Mix",
    "reasonBlockedIncorrectly": "Memblokir atau mengubah sesuatu secara keliru",
    "reasonLayoutLanguage": "Tidak berfungsi pada tata letak atau bahasa YouTube saya",
    "reasonConfiguration": "Konfigurasinya membingungkan",
    "reasonBugSlowdown": "Menyebabkan bug, perlambatan, atau masalah kompatibilitas",
    "reasonNoLongerNeeded": "Saya tidak membutuhkannya lagi",
    "reasonPrivacyPermissions": "Kekhawatiran privasi atau izin",
    "reasonOther": "Lainnya",
    "detailsLabel": "Apa yang terjadi atau apa yang Anda harapkan?",
    "detailsHelp": "Opsional. Satu atau dua kalimat sudah cukup.",
    "featureLabel": "Fitur apa yang akan membuat Anda mencobanya lagi?",
    "featureHelp": "Opsional.",
    "contactLabel": "Alamat balasan",
    "contactHelp": "Opsional. Isi hanya jika Anda ingin mendapat balasan.",
    "submit": "Kirim masukan",
    "status": "Masukan diproses oleh Formspree.",
    "footerSource": "Sumber"
  },
  "ko": {
    "pageTitle": "YouTube Mix Blocker 피드백",
    "metaDescription": "YouTube Mix Blocker 제거 후 선택적으로 남기는 피드백입니다.",
    "brandHomeLabel": "Oleksandr Molodchyk 홈",
    "navLabel": "기본 탐색",
    "navProjects": "프로젝트",
    "navNow": "현재",
    "navAbout": "소개",
    "navContact": "연락처",
    "headline": "확장 프로그램 개선에 도움을 주세요",
    "intro": "YouTube Mix Blocker가 기대에 맞지 않았다면 짧은 메모만으로도 충분합니다. 이 양식은 선택 사항이며 연락처 정보가 필요하지 않습니다.",
    "privacyNote": "확장 프로그램은 제거 후 출처, 버전, 브라우저 언어라는 일반 매개변수만 포함해 이 페이지를 엽니다. 의도적으로 공유하려는 경우가 아니라면 개인 정보를 포함하지 마세요.",
    "reasonLabel": "왜 제거하셨나요?",
    "chooseOne": "하나 선택",
    "reasonNotEnough": "YouTube Mix를 충분히 차단하지 못했습니다",
    "reasonBlockedIncorrectly": "무언가를 잘못 차단하거나 변경했습니다",
    "reasonLayoutLanguage": "내 YouTube 레이아웃이나 언어에서 작동하지 않았습니다",
    "reasonConfiguration": "설정하기 어려웠습니다",
    "reasonBugSlowdown": "버그, 속도 저하 또는 호환성 문제가 있었습니다",
    "reasonNoLongerNeeded": "더 이상 필요하지 않습니다",
    "reasonPrivacyPermissions": "개인정보 또는 권한이 걱정됩니다",
    "reasonOther": "기타",
    "detailsLabel": "무슨 일이 있었거나 무엇을 기대하셨나요?",
    "detailsHelp": "선택 사항입니다. 한두 문장이면 충분합니다.",
    "featureLabel": "어떤 기능이 있으면 다시 사용해 보시겠어요?",
    "featureHelp": "선택 사항입니다.",
    "contactLabel": "답장 받을 주소",
    "contactHelp": "선택 사항입니다. 답장을 원할 때만 입력하세요.",
    "submit": "피드백 보내기",
    "status": "피드백은 Formspree에서 처리됩니다.",
    "footerSource": "소스"
  },
  "pl": {
    "pageTitle": "Opinia o YouTube Mix Blocker",
    "metaDescription": "Opcjonalna opinia po odinstalowaniu YouTube Mix Blocker.",
    "brandHomeLabel": "Strona główna Oleksandra Molodchyka",
    "navLabel": "Główna nawigacja",
    "navProjects": "Projekty",
    "navNow": "Teraz",
    "navAbout": "O mnie",
    "navContact": "Kontakt",
    "headline": "Pomóż ulepszyć rozszerzenie",
    "intro": "Jeśli YouTube Mix Blocker nie spełnił oczekiwań, wystarczy krótka notatka. Ten formularz jest opcjonalny i nie wymaga danych kontaktowych.",
    "privacyNote": "Rozszerzenie otwiera tę stronę po odinstalowaniu tylko z ogólnymi parametrami źródła, wersji i języka przeglądarki. Nie podawaj danych osobowych, chyba że świadomie chcesz je udostępnić.",
    "reasonLabel": "Dlaczego odinstalowano rozszerzenie?",
    "chooseOne": "Wybierz jedną opcję",
    "reasonNotEnough": "Nie blokowało wystarczająco wielu YouTube Mixów",
    "reasonBlockedIncorrectly": "Coś było błędnie blokowane lub zmieniane",
    "reasonLayoutLanguage": "Nie działało z moim układem lub językiem YouTube",
    "reasonConfiguration": "Konfiguracja była myląca",
    "reasonBugSlowdown": "Powodowało błąd, spowolnienie lub problem ze zgodnością",
    "reasonNoLongerNeeded": "Nie jest mi już potrzebne",
    "reasonPrivacyPermissions": "Obawy dotyczące prywatności lub uprawnień",
    "reasonOther": "Inne",
    "detailsLabel": "Co się stało albo czego oczekiwano?",
    "detailsHelp": "Opcjonalnie. Wystarczy jedno lub dwa zdania.",
    "featureLabel": "Jaka funkcja zachęciłaby do ponownej próby?",
    "featureHelp": "Opcjonalnie.",
    "contactLabel": "Adres do odpowiedzi",
    "contactHelp": "Opcjonalnie. Podaj tylko, jeśli chcesz otrzymać odpowiedź.",
    "submit": "Wyślij opinię",
    "status": "Opinia jest obsługiwana przez Formspree.",
    "footerSource": "Źródło"
  }
};
