export const translations = {
  en: {
    navProjects: 'Projects',
    navNow: 'Now',
    navAbout: 'About',
    navContact: 'Contact',
    themeSystem: 'System',
    themeBright: 'Bright',
    themeDark: 'Dark',
    heroEyebrow: 'Software builder',
    heroTitle: 'I love building things.',
    heroIntro: 'I build practical software, browser tools, and local-first systems for making digital environments easier to control.',
    heroGithub: 'GitHub',
    heroProjects: 'View projects',
    heroContact: 'Contact',
    heroImageCaption: 'Workspace image for now. Replace with a real desk photo later.',
    signalLabel: 'Currently building',
    signalText: 'Browser-level protection against distraction, intent drift, and hostile attention design.',
    projectsEyebrow: 'Projects',
    projectsTitle: 'Things I am building',
    projectsIntro: 'Browser extensions and supporting systems built from 2023 to 2026.',
    projectsSnapshot: 'Store status snapshot: June 10, 2026.',
    projectStatusActive: 'Active',
    projectStatusPublished: 'Published',
    projectStatusPending: 'Pending review',
    projectStatusApproved: 'Approved',
    projectStatusPrototype: 'Prototype',
    projectStatusPlanned: 'Planned',
    projectStatusThis: 'This site',
    dadDescription: 'A browser-level protection system for plans, schedules, Pomodoro, UI cleanup, usage diagnostics, and intent-coherence protection.',
    dadUsers: '38 users',
    dadCreated: 'Created Dec 28, 2023',
    dadPointOne: 'Local-first protection model',
    dadPointTwo: 'Drift and distraction diagnostics',
    dadPointThree: 'Plans, schedules, Pomodoro, and UI rules',
    youtubeMixDescription: 'Blocks YouTube Mix recommendations and cleans Mix watch URLs so videos open as ordinary video links.',
    youtubeMixUsers: '1,121 Chrome users',
    motionBlockDescription: 'Stops GIFs, GIFV, autoplay video, hover previews, and distracting motion with per-site controls.',
    motionBlockStatus: 'Public Chrome listing',
    discordGifDescription: 'Blocks animated GIFs on Discord to reduce visual noise and make the web app calmer.',
    discordGifUsers: '64 users',
    discordGifRating: '5.0 rating',
    discordSearchDescription: 'Hides Discord\'s in-channel search field so intentionally avoided channels are harder to reopen through search.',
    discordSearchUsers: '46 users',
    discordSearchRating: '5.0 rating',
    storePilotDescription: 'Automates Chrome Web Store listing work: field autofill, screenshots, descriptions, and privacy form text.',
    storePilotDownloads: '3 weekly downloads',
    storePilotUsers: '1 active user',
    lockscreenDescription: 'Stops browser audio when the computer locks and prevents lock-screen media controls from resuming sound.',
    lockscreenCreated: 'Created Jun 9, 2026',
    consentBlurDescription: 'A local-first media safety prototype that progressively blurs risky or unwanted image previews.',
    dadWindowsDescription: 'A planned native Windows companion for system idle, lock, app, and Pomodoro signals that a browser extension cannot own alone.',
    siteDescription: 'A public home base for current work, project notes, and GitHub-visible activity.',
    nowEyebrow: 'Now',
    nowTitle: 'Current focus',
    nowOneLabel: 'Product',
    nowOneTitle: 'Defense Against Distractions release readiness',
    nowOneText: 'Tightening the browser extension around plans, diagnostics, Pomodoro, and intent-coherence behavior.',
    nowTwoLabel: 'Research',
    nowTwoTitle: 'Attention control systems',
    nowTwoText: 'Exploring practical defenses against drift, recommender capture, and destructive browsing trajectories.',
    githubEyebrow: 'GitHub',
    githubTitle: 'Public activity',
    githubIntro: 'Recent public repositories from GitHub. This uses the public GitHub API in the browser with no token and no backend.',
    githubLoading: 'Loading public repositories...',
    githubFallback: 'GitHub activity could not be loaded right now.',
    aboutEyebrow: 'About',
    aboutTitle: 'Practical software, direct feedback loops',
    aboutTextOne: 'I like software that earns its place by reducing friction, preserving attention, or making a system easier to understand.',
    aboutTextTwo: 'My current focus is Defense Against Distractions: a local-first protection system that treats distraction as more than a list of bad websites.',
    contactEyebrow: 'Contact',
    contactTitle: 'Send a direct signal',
    footerSource: 'Source'
  },
  de: {
    navProjects: 'Projekte',
    navNow: 'Jetzt',
    navAbout: 'Über mich',
    navContact: 'Kontakt',
    themeSystem: 'System',
    themeBright: 'Hell',
    themeDark: 'Dunkel',
    heroEyebrow: 'Softwareentwickler',
    heroTitle: 'Ich liebe es, Dinge zu bauen.',
    heroIntro: 'Ich baue praktische Software, Browser-Werkzeuge und lokale Systeme, die digitale Umgebungen kontrollierbarer machen.',
    heroGithub: 'GitHub',
    heroProjects: 'Projekte ansehen',
    heroContact: 'Kontakt',
    heroImageCaption: 'Arbeitsplatzbild für den Moment. Später durch ein echtes Foto ersetzen.',
    signalLabel: 'Aktuell baue ich',
    signalText: 'Browser-Schutz gegen Ablenkung, Intent-Drift und feindliches Aufmerksamkeitsdesign.',
    projectsEyebrow: 'Projekte',
    projectsTitle: 'Dinge, die ich baue',
    projectsIntro: 'Browser-Erweiterungen und unterstützende Systeme, gebaut von 2023 bis 2026.',
    projectsSnapshot: 'Store-Status-Snapshot: 10. Juni 2026.',
    projectStatusActive: 'Aktiv',
    projectStatusPublished: 'Veröffentlicht',
    projectStatusPending: 'In Prüfung',
    projectStatusApproved: 'Freigegeben',
    projectStatusPrototype: 'Prototyp',
    projectStatusPlanned: 'Geplant',
    projectStatusThis: 'Diese Seite',
    dadDescription: 'Ein browsernahes Schutzsystem für Pläne, Zeitpläne, Pomodoro, UI-Bereinigung, Nutzungsdiagnostik und Intent-Kohärenz.',
    dadUsers: '38 Nutzer',
    dadCreated: 'Erstellt am 28. Dez. 2023',
    dadPointOne: 'Lokales Schutzmodell',
    dadPointTwo: 'Diagnostik für Drift und Ablenkung',
    dadPointThree: 'Pläne, Zeitpläne, Pomodoro und UI-Regeln',
    youtubeMixDescription: 'Blockiert YouTube-Mix-Empfehlungen und bereinigt Mix-Watch-URLs, damit Videos als normale Videolinks geöffnet werden.',
    youtubeMixUsers: '1.121 Chrome-Nutzer',
    motionBlockDescription: 'Stoppt GIFs, GIFV, Autoplay-Videos, Hover-Vorschauen und ablenkende Bewegung mit Einstellungen pro Website.',
    motionBlockStatus: 'Öffentlicher Chrome-Eintrag',
    discordGifDescription: 'Blockiert animierte GIFs in Discord, um visuelles Rauschen zu reduzieren und die Web-App ruhiger zu machen.',
    discordGifUsers: '64 Nutzer',
    discordGifRating: 'Bewertung 5,0',
    discordSearchDescription: 'Blendet das Suchfeld in Discord-Kanälen aus, damit bewusst gemiedene Kanäle schwerer über die Suche wieder geöffnet werden.',
    discordSearchUsers: '46 Nutzer',
    discordSearchRating: 'Bewertung 5,0',
    storePilotDescription: 'Automatisiert Chrome-Web-Store-Listings: Felder ausfüllen, Screenshots, Beschreibungen und Datenschutztexte.',
    storePilotDownloads: '3 wöchentliche Downloads',
    storePilotUsers: '1 aktiver Nutzer',
    lockscreenDescription: 'Stoppt Browser-Audio, wenn der Computer gesperrt wird, und verhindert, dass Sperrbildschirm-Mediensteuerungen Ton wieder starten.',
    lockscreenCreated: 'Erstellt am 9. Juni 2026',
    consentBlurDescription: 'Ein lokaler Prototyp für Mediensicherheit, der riskante oder unerwünschte Bildvorschauen schrittweise weichzeichnet.',
    dadWindowsDescription: 'Ein geplanter nativer Windows-Begleiter für Idle-, Sperr-, App- und Pomodoro-Signale, die eine Browser-Erweiterung allein nicht zuverlässig besitzen kann.',
    siteDescription: 'Ein öffentliches Zuhause für aktuelle Arbeit, Projektnotizen und GitHub-sichtbare Aktivität.',
    nowEyebrow: 'Jetzt',
    nowTitle: 'Aktueller Fokus',
    nowOneLabel: 'Produkt',
    nowOneTitle: 'Release-Bereitschaft von Defense Against Distractions',
    nowOneText: 'Die Browser-Erweiterung rund um Pläne, Diagnostik, Pomodoro und Intent-Kohärenz enger ziehen.',
    nowTwoLabel: 'Recherche',
    nowTwoTitle: 'Systeme für Aufmerksamkeitskontrolle',
    nowTwoText: 'Praktische Abwehr gegen Drift, Recommender-Capture und destruktive Browsing-Verläufe.',
    githubEyebrow: 'GitHub',
    githubTitle: 'Öffentliche Aktivität',
    githubIntro: 'Aktuelle öffentliche Repositories von GitHub. Das nutzt die öffentliche GitHub-API im Browser, ohne Token und ohne Backend.',
    githubLoading: 'Öffentliche Repositories werden geladen...',
    githubFallback: 'GitHub-Aktivität konnte gerade nicht geladen werden.',
    aboutEyebrow: 'Über mich',
    aboutTitle: 'Praktische Software, direkte Feedbackschleifen',
    aboutTextOne: 'Ich mag Software, die ihren Platz verdient, weil sie Reibung reduziert, Aufmerksamkeit schützt oder ein System verständlicher macht.',
    aboutTextTwo: 'Mein aktueller Fokus ist Defense Against Distractions: ein lokales Schutzsystem, das Ablenkung als mehr behandelt als eine Liste schlechter Websites.',
    contactEyebrow: 'Kontakt',
    contactTitle: 'Ein direktes Signal senden',
    footerSource: 'Quellcode'
  },
  uk: {
    navProjects: 'Проєкти',
    navNow: 'Зараз',
    navAbout: 'Про мене',
    navContact: 'Контакт',
    themeSystem: 'Система',
    themeBright: 'Світла',
    themeDark: 'Темна',
    heroEyebrow: 'Розробник ПЗ',
    heroTitle: 'Я люблю будувати речі.',
    heroIntro: 'Я створюю практичне програмне забезпечення, браузерні інструменти та локальні системи, які допомагають краще контролювати цифрове середовище.',
    heroGithub: 'GitHub',
    heroProjects: 'Переглянути проєкти',
    heroContact: 'Контакт',
    heroImageCaption: 'Зображення робочого простору на зараз. Пізніше замінити реальним фото.',
    signalLabel: 'Зараз будую',
    signalText: 'Браузерний захист від відволікань, втрати наміру та агресивного дизайну уваги.',
    projectsEyebrow: 'Проєкти',
    projectsTitle: 'Речі, які я будую',
    projectsIntro: 'Браузерні розширення та допоміжні системи, створені з 2023 до 2026 року.',
    projectsSnapshot: 'Зріз статусів у сторах: 10 червня 2026.',
    projectStatusActive: 'Активний',
    projectStatusPublished: 'Опубліковано',
    projectStatusPending: 'На перевірці',
    projectStatusApproved: 'Схвалено',
    projectStatusPrototype: 'Прототип',
    projectStatusPlanned: 'Заплановано',
    projectStatusThis: 'Цей сайт',
    dadDescription: 'Система браузерного захисту для планів, розкладів, Pomodoro, очищення UI, діагностики використання та захисту наміру.',
    dadUsers: '38 користувачів',
    dadCreated: 'Створено 28 груд. 2023',
    dadPointOne: 'Локальна модель захисту',
    dadPointTwo: 'Діагностика дрейфу та відволікань',
    dadPointThree: 'Плани, розклади, Pomodoro і правила UI',
    youtubeMixDescription: 'Блокує рекомендації YouTube Mix і очищає URL перегляду Mix, щоб відео відкривалися як звичайні посилання.',
    youtubeMixUsers: '1 121 користувач Chrome',
    motionBlockDescription: 'Зупиняє GIF, GIFV, autoplay-відео, hover-preview та відволікальний рух із налаштуваннями для кожного сайту.',
    motionBlockStatus: 'Публічна сторінка Chrome',
    discordGifDescription: 'Блокує анімовані GIF у Discord, щоб зменшити візуальний шум і зробити веб-застосунок спокійнішим.',
    discordGifUsers: '64 користувачі',
    discordGifRating: 'Рейтинг 5,0',
    discordSearchDescription: 'Ховає поле пошуку всередині каналів Discord, щоб навмисно уникані канали було складніше знову відкрити через пошук.',
    discordSearchUsers: '46 користувачів',
    discordSearchRating: 'Рейтинг 5,0',
    storePilotDescription: 'Автоматизує роботу зі сторінками Chrome Web Store: заповнення полів, скриншоти, описи та текст privacy-форми.',
    storePilotDownloads: '3 завантаження на тиждень',
    storePilotUsers: '1 активний користувач',
    lockscreenDescription: 'Зупиняє аудіо браузера, коли комп’ютер блокується, і не дає медіакнопкам на lock screen відновити звук.',
    lockscreenCreated: 'Створено 9 черв. 2026',
    consentBlurDescription: 'Локальний прототип медіабезпеки, який поступово розмиває ризиковані або небажані прев’ю зображень.',
    dadWindowsDescription: 'Запланований нативний Windows-супутник для сигналів idle, lock, застосунків і Pomodoro, які браузерне розширення не може надійно обробляти саме.',
    siteDescription: 'Публічна домашня база для поточної роботи, нотаток про проєкти та GitHub-активності.',
    nowEyebrow: 'Зараз',
    nowTitle: 'Поточний фокус',
    nowOneLabel: 'Продукт',
    nowOneTitle: 'Готовність Defense Against Distractions до релізу',
    nowOneText: 'Доведення браузерного розширення навколо планів, діагностики, Pomodoro та поведінки intent coherence.',
    nowTwoLabel: 'Дослідження',
    nowTwoTitle: 'Системи контролю уваги',
    nowTwoText: 'Практичний захист від дрейфу, захоплення рекомендаціями та деструктивних траєкторій браузингу.',
    githubEyebrow: 'GitHub',
    githubTitle: 'Публічна активність',
    githubIntro: 'Останні публічні репозиторії з GitHub. Це використовує публічний GitHub API у браузері без токена і без бекенду.',
    githubLoading: 'Завантажуються публічні репозиторії...',
    githubFallback: 'GitHub-активність зараз не вдалося завантажити.',
    aboutEyebrow: 'Про мене',
    aboutTitle: 'Практичне ПЗ і прямі цикли зворотного зв’язку',
    aboutTextOne: 'Мені подобається програмне забезпечення, яке заслуговує на своє місце: зменшує тертя, захищає увагу або робить систему зрозумілішою.',
    aboutTextTwo: 'Мій поточний фокус — Defense Against Distractions: локальна система захисту, яка дивиться на відволікання ширше, ніж просто список поганих сайтів.',
    contactEyebrow: 'Контакт',
    contactTitle: 'Надіслати прямий сигнал',
    footerSource: 'Код'
  }
};
