export const BASE_COPY = {
  "pageTitle": "MotionBlock Feedback",
  "metaDescription": "Optional uninstall feedback for MotionBlock.",
  "brandHomeLabel": "Oleksandr Molodchyk home",
  "navLabel": "Main navigation",
  "navProjects": "Projects",
  "navNow": "Now",
  "navAbout": "About",
  "navContact": "Contact",
  "headline": "Help improve the extension",
  "intro": "If MotionBlock missed the mark, one short note is enough. This form is optional and does not require contact information.",
  "privacyNote": "The extension opens this page after uninstall with only generic source, version, and browser-language parameters. Do not include personal data unless you intentionally want to share it.",
  "reasonLabel": "Why did you uninstall?",
  "chooseOne": "Choose one",
  "reasonNotEnough": "It did not block the motion or media I expected",
  "reasonBlockedIncorrectly": "It blocked or changed something incorrectly",
  "reasonSiteCompatibility": "It did not work on a website I needed",
  "reasonConfiguration": "It was confusing to configure",
  "reasonBugSlowdown": "It caused a bug, slowdown, or compatibility issue",
  "reasonNoLongerNeeded": "I no longer need it",
  "reasonPrivacyPermissions": "Privacy or permission concern",
  "reasonOther": "Other",
  "detailsLabel": "What happened or what did you expect instead?",
  "detailsHelp": "Optional. A sentence or two is enough.",
  "featureLabel": "What feature would make you try it again?",
  "featureHelp": "Optional.",
  "contactLabel": "Reply address",
  "contactHelp": "Optional. Only include this if you want a reply.",
  "submit": "Send feedback",
  "status": "Feedback is processed by Formspree.",
  "footerSource": "Source"
};
