export const LOCALE_COPY_GROUP_8 = {
 "fa": {
 "pageTitle": "MotionBlock بازخورد",
 "metaDescription": "بازخورد حذف نصب اختیاری برای MotionBlock.",
 "brandHomeLabel": "خانه Oleksandr Molodchyk",
 "navLabel": "ناوبری اصلی",
 "navProjects": "پروژه‌ها",
 "navNow": "اکنون",
 "navAbout": "درباره",
 "navContact": "تماس",
 "headline": "به بهبود افزونه کمک کنید",
 "intro": "اگر MotionBlock به هدف نرسیدی، یک نت کوتاه کافی است. این فرم اختیاری است و نیازی به اطلاعات تماس ندارد.",
 "privacyNote": "افزونه پس از حذف، این صفحه را فقط با پارامترهای عمومی منبع، نسخه و زبان مرورگر باز می‌کند. داده شخصی وارد نکنید مگر اینکه عمداً بخواهید آن را به اشتراک بگذارید.",
 "reasonLabel": "چرا حذف کردید؟",
 "chooseOne": "یکی را انتخاب کنید",
 "reasonNotEnough": "حرکت یا رسانه ای که انتظار داشتم را مسدود نکرد",
 "reasonBlockedIncorrectly": "چیزی را اشتباه مسدود یا تغییر داد",
 "reasonSiteCompatibility": "روی سایتی که نیاز داشتم کار نکرد",
 "reasonConfiguration": "پیکربندی آن گیج‌کننده بود",
 "reasonBugSlowdown": "باعث خطا، کندی یا مشکل سازگاری شد",
 "reasonNoLongerNeeded": "دیگر به آن نیاز ندارم",
 "reasonPrivacyPermissions": "نگرانی درباره حریم خصوصی یا مجوزها",
 "reasonOther": "سایر",
 "detailsLabel": "چه اتفاقی افتاد یا به جای آن چه انتظاری داشتید؟",
 "detailsHelp": "اختیاری. یک یا دو جمله کافی است.",
 "featureLabel": "چه قابلیتی باعث می‌شود دوباره آن را امتحان کنید؟",
 "featureHelp": "اختیاری.",
 "contactLabel": "نشانی برای پاسخ",
 "contactHelp": "اختیاری. فقط اگر پاسخ می‌خواهید وارد کنید.",
 "submit": "ارسال بازخورد",
 "status": "بازخورد توسط Formspree پردازش می‌شود.",
 "footerSource": "منبع"
 },
 "hu": {
 "pageTitle": "MotionBlock Visszajelzés",
 "metaDescription": "Opcionális eltávolítási visszacsatolás MotionBlock számára.",
 "brandHomeLabel": "Oleksandr Molodchyk kezdőlapja",
 "navLabel": "Fő navigáció",
 "navProjects": "Projektek",
 "navNow": "Most",
 "navAbout": "Névjegy",
 "navContact": "Kapcsolat",
 "headline": "Segíts javítani a bővítményt",
 "intro": "Ha MotionBlock nem sikerült, egy rövid hang elég. Ez az űrlap opcionális, és nem igényel elérhetőségi adatokat.",
 "privacyNote": "A bővítmény eltávolítás után csak általános forrás-, verzió- és böngészőnyelv-paraméterekkel nyitja meg ezt az oldalt. Ne adj meg személyes adatot, hacsak nem szándékosan szeretnéd megosztani.",
 "reasonLabel": "Miért távolítottad el?",
 "chooseOne": "Válassz egyet",
 "reasonNotEnough": "Nem blokkolta meg a várt mozgást vagy a médiát",
 "reasonBlockedIncorrectly": "Valamit tévesen blokkolt vagy módosított",
 "reasonSiteCompatibility": "Nem működött egy olyan weboldalon, amire szükségem volt",
 "reasonConfiguration": "Zavaros volt beállítani",
 "reasonBugSlowdown": "Hibát, lassulást vagy kompatibilitási problémát okozott",
 "reasonNoLongerNeeded": "Már nincs rá szükségem",
 "reasonPrivacyPermissions": "Adatvédelmi vagy engedélyezési aggály",
 "reasonOther": "Egyéb",
 "detailsLabel": "Mi történt, vagy mit vártál volna helyette?",
 "detailsHelp": "Opcionális. Egy-két mondat elég.",
 "featureLabel": "Milyen funkció miatt próbálnád ki újra?",
 "featureHelp": "Opcionális.",
 "contactLabel": "Válaszcím",
 "contactHelp": "Opcionális. Csak akkor add meg, ha választ szeretnél.",
 "submit": "Visszajelzés küldése",
 "status": "A visszajelzést a Formspree dolgozza fel.",
 "footerSource": "Forrás"
 },
 "hy": {
 "pageTitle": "MotionBlock հետադարձ կապ",
 "metaDescription": "Ընտրովի ապատեղադրման հետադարձ կապ MotionBlock-ի համար:",
 "brandHomeLabel": "Oleksandr Molodchyk-ի գլխավոր էջ",
 "navLabel": "Հիմնական նավարկում",
 "navProjects": "Նախագծեր",
 "navNow": "Հիմա",
 "navAbout": "Մասին",
 "navContact": "Կապ",
 "headline": "Օգնեք բարելավել ընդլայնումը",
 "intro": "Եթե MotionBlock բաց թողեց նշաձողը, բավական է մեկ կարճ նոտա։ Այս ձեւը ընտրովի է եւ չի պահանջում կոնտակտային տվյալներ:",
 "privacyNote": "Ընդլայնումը հեռացնելուց հետո այս էջը բացվում է միայն աղբյուրի, տարբերակի և դիտարկչի լեզվի ընդհանուր պարամետրերով։ Մի ներառեք անձնական տվյալներ, եթե հատուկ չեք ուզում դրանք կիսել։",
 "reasonLabel": "Ինչու՞ հեռացրեցիք։",
 "chooseOne": "Ընտրեք մեկը",
 "reasonNotEnough": "Այն չխոչընդոտեց այն շարժումը կամ լրատվամիջոցները, որոնք ես ակնկալում էի",
 "reasonBlockedIncorrectly": "Սխալմամբ ինչ-որ բան արգելափակում կամ փոխում էր",
 "reasonSiteCompatibility": "Այն չաշխատեց ինձ անհրաժեշտ վեբ կայքում",
 "reasonConfiguration": "Կարգավորելը շփոթեցնող էր",
 "reasonBugSlowdown": "Առաջացնում էր սխալ, դանդաղեցում կամ համատեղելիության խնդիր",
 "reasonNoLongerNeeded": "Այլևս պետք չէ",
 "reasonPrivacyPermissions": "Գաղտնիության կամ թույլտվությունների մտահոգություն",
 "reasonOther": "Այլ",
 "detailsLabel": "Ի՞նչ տեղի ունեցավ կամ ի՞նչ էիք սպասում փոխարենը։",
 "detailsHelp": "Ընտրովի։ Մեկ-երկու նախադասությունը բավական է։",
 "featureLabel": "Ո՞ր գործառույթը կստիպեր նորից փորձել։",
 "featureHelp": "Ընտրովի։",
 "contactLabel": "Պատասխանի հասցե",
 "contactHelp": "Ընտրովի։ Նշեք միայն եթե պատասխան եք ուզում։",
 "submit": "Ուղարկել կարծիք",
 "status": "Կարծիքը մշակվում է Formspree-ի միջոցով։",
 "footerSource": "Աղբյուր"
 },
 "zh_TW": {
 "pageTitle": "MotionBlock 回饋",
 "metaDescription": "MotionBlock 可選擇卸載回饋。",
 "brandHomeLabel": "Oleksandr Molodchyk 首頁",
 "navLabel": "主要導覽",
 "navProjects": "專案",
 "navNow": "近況",
 "navAbout": "關於",
 "navContact": "聯絡",
 "headline": "協助改進這個擴充功能",
 "intro": "如果沒達到目標，MotionBlock 一個短音就夠了。此表單為選填，無需提供聯絡資訊。",
 "privacyNote": "擴充功能會在解除安裝後開啟此頁，只附上來源、版本和瀏覽器語言等一般參數。除非你有意分享，請不要填寫個人資料。",
 "reasonLabel": "你為什麼解除安裝？",
 "chooseOne": "選擇一項",
 "reasonNotEnough": "它沒有阻擋我預期的動態或媒體",
 "reasonBlockedIncorrectly": "錯誤封鎖或變更了某些內容",
 "reasonSiteCompatibility": "它在我需要的網站上不行",
 "reasonConfiguration": "設定方式令人困惑",
 "reasonBugSlowdown": "造成錯誤、變慢或相容性問題",
 "reasonNoLongerNeeded": "我不再需要它",
 "reasonPrivacyPermissions": "隱私或權限疑慮",
 "reasonOther": "其他",
 "detailsLabel": "發生了什麼事，或你原本期待什麼？",
 "detailsHelp": "選填。一兩句話即可。",
 "featureLabel": "什麼功能會讓你願意再試一次？",
 "featureHelp": "選填。",
 "contactLabel": "回覆地址",
 "contactHelp": "選填。只有在你想收到回覆時才填寫。",
 "submit": "送出回饋",
 "status": "回饋由 Formspree 處理。",
 "footerSource": "原始碼"
 },
 "fr": {
 "pageTitle": "MotionBlock Retour d’information",
 "metaDescription": "Retour optionnel sur la désinstallation pour MotionBlock.",
 "brandHomeLabel": "Accueil d'Oleksandr Molodchyk",
 "navLabel": "Navigation principale",
 "navProjects": "Projets",
 "navNow": "Maintenant",
 "navAbout": "À propos",
 "navContact": "Contact",
 "headline": "Aidez à améliorer l'extension",
 "intro": "Si MotionBlock manqué la note, une courte note suffit. Ce formulaire est optionnel et ne nécessite pas d’informations de contact.",
 "privacyNote": "L'extension ouvre cette page après la désinstallation avec uniquement des paramètres génériques de source, de version et de langue du navigateur. N'indiquez pas de données personnelles sauf si vous voulez les partager volontairement.",
 "reasonLabel": "Pourquoi l'avez-vous désinstallée ?",
 "chooseOne": "Choisir une option",
 "reasonNotEnough": "Cela n’a pas bloqué le mouvement ni le média auquel je m’attendais",
 "reasonBlockedIncorrectly": "Elle bloquait ou modifiait quelque chose à tort",
 "reasonSiteCompatibility": "Ça n’a pas marché sur un site dont j’avais besoin",
 "reasonConfiguration": "Elle était confuse à configurer",
 "reasonBugSlowdown": "Elle causait un bug, un ralentissement ou un problème de compatibilité",
 "reasonNoLongerNeeded": "Je n'en ai plus besoin",
 "reasonPrivacyPermissions": "Préoccupation liée à la confidentialité ou aux autorisations",
 "reasonOther": "Autre",
 "detailsLabel": "Que s'est-il passé ou qu'attendiez-vous à la place ?",
 "detailsHelp": "Facultatif. Une ou deux phrases suffisent.",
 "featureLabel": "Quelle fonctionnalité vous ferait réessayer ?",
 "featureHelp": "Facultatif.",
 "contactLabel": "Adresse de réponse",
 "contactHelp": "Facultatif. À inclure uniquement si vous souhaitez une réponse.",
 "submit": "Envoyer le retour",
 "status": "Le retour est traité par Formspree.",
 "footerSource": "Source"
 },
 "bg": {
 "pageTitle": "MotionBlock Обратна връзка",
 "metaDescription": "Опционална обратна връзка за премахване на MotionBlock.",
 "brandHomeLabel": "Начална страница на Oleksandr Molodchyk",
 "navLabel": "Основна навигация",
 "navProjects": "Проекти",
 "navNow": "Сега",
 "navAbout": "За мен",
 "navContact": "Контакт",
 "headline": "Помогнете за подобряване на разширението",
 "intro": "Ако MotionBlock пропуснал целта, една кратка нота е достатъчна. Този формуляр е по избор и не изисква контактна информация.",
 "privacyNote": "Разширението отваря тази страница след деинсталиране само с общи параметри за източник, версия и език на браузъра. Не включвайте лични данни, освен ако умишлено искате да ги споделите.",
 "reasonLabel": "Защо деинсталирахте?",
 "chooseOne": "Изберете едно",
 "reasonNotEnough": "Не блокира движението или медията, които очаквах",
 "reasonBlockedIncorrectly": "Блокира или промени нещо неправилно",
 "reasonSiteCompatibility": "Не проработи на уебсайта, който ми трябваше",
 "reasonConfiguration": "Беше объркващо за настройване",
 "reasonBugSlowdown": "Причини грешка, забавяне или проблем със съвместимостта",
 "reasonNoLongerNeeded": "Вече не ми трябва",
 "reasonPrivacyPermissions": "Притеснение за поверителност или разрешения",
 "reasonOther": "Друго",
 "detailsLabel": "Какво се случи или какво очаквахте вместо това?",
 "detailsHelp": "Незадължително. Едно-две изречения са достатъчни.",
 "featureLabel": "Коя функция би ви накарала да го пробвате отново?",
 "featureHelp": "Незадължително.",
 "contactLabel": "Адрес за отговор",
 "contactHelp": "Незадължително. Добавете го само ако искате отговор.",
 "submit": "Изпрати обратна връзка",
 "status": "Обратната връзка се обработва чрез Formspree.",
 "footerSource": "Изходен код"
 }
};
