export const LOCALE_COPY_GROUP_4 = {
 "sq": {
 "pageTitle": "MotionBlock Komentet",
 "metaDescription": "Reagimet opsionale të çinstalimit për MotionBlock.",
 "brandHomeLabel": "Faqja kryesore e Oleksandr Molodchyk",
 "navLabel": "Navigimi kryesor",
 "navProjects": "Projektet",
 "navNow": "Tani",
 "navAbout": "Rreth",
 "navContact": "Kontakt",
 "headline": "Ndihmoni në përmirësimin e shtesës",
 "intro": "Nëse MotionBlock humbur shenjën, mjafton një shënim i shkurtër. Ky formular është opsional dhe nuk kërkon informacion kontakti.",
 "privacyNote": "Shtesa e hap këtë faqe pas çinstalimit vetëm me parametra të përgjithshëm për burimin, versionin dhe gjuhën e shfletuesit. Mos përfshini të dhëna personale nëse nuk doni t’i ndani me qëllim.",
 "reasonLabel": "Pse e çinstaluat?",
 "chooseOne": "Zgjidhni një",
 "reasonNotEnough": "Nuk e bllokoi lëvizjen ose mediat që prisja",
 "reasonBlockedIncorrectly": "Bllokoi ose ndryshoi diçka gabimisht",
 "reasonSiteCompatibility": "Nuk funksionoi në një faqe interneti që më duhej",
 "reasonConfiguration": "Konfigurimi ishte i paqartë",
 "reasonBugSlowdown": "Shkaktoi gabim, ngadalësim ose problem përputhshmërie",
 "reasonNoLongerNeeded": "Nuk më nevojitet më",
 "reasonPrivacyPermissions": "Shqetësim për privatësinë ose lejet",
 "reasonOther": "Tjetër",
 "detailsLabel": "Çfarë ndodhi ose çfarë prisnit në vend të kësaj?",
 "detailsHelp": "Opsionale. Mjafton një ose dy fjali.",
 "featureLabel": "Cila veçori do t’ju bënte ta provonit përsëri?",
 "featureHelp": "Opsionale.",
 "contactLabel": "Adresa për përgjigje",
 "contactHelp": "Opsionale. Vendoseni vetëm nëse doni përgjigje.",
 "submit": "Dërgo reagim",
 "status": "Reagimi përpunohet nga Formspree.",
 "footerSource": "Burimi"
 },
 "bn": {
 "pageTitle": "MotionBlock মতামত",
 "metaDescription": "MotionBlock জন্য ঐচ্ছিক প্রতিক্রিয়া আনইনস্টল করুন।",
 "brandHomeLabel": "Oleksandr Molodchyk হোম",
 "navLabel": "প্রধান নেভিগেশন",
 "navProjects": "প্রকল্প",
 "navNow": "এখন",
 "navAbout": "সম্পর্কে",
 "navContact": "যোগাযোগ",
 "headline": "এক্সটেনশনটি উন্নত করতে সাহায্য করুন",
 "intro": "যদি MotionBlock চিহ্নটি মিস করে থাকেন তবে একটি সংক্ষিপ্ত নোটই যথেষ্ট। এই ফর্মটি ঐচ্ছিক এবং যোগাযোগের তথ্যের প্রয়োজন হয় না।",
 "privacyNote": "এক্সটেনশন আনইনস্টল হওয়ার পর এই পৃষ্ঠাটি শুধু সাধারণ source, version এবং browser-language প্যারামিটার নিয়ে খোলে। আপনি ইচ্ছাকৃতভাবে শেয়ার করতে না চাইলে ব্যক্তিগত তথ্য দেবেন না।",
 "reasonLabel": "কেন আনইনস্টল করলেন?",
 "chooseOne": "একটি বেছে নিন",
 "reasonNotEnough": "এটি আমার প্রত্যাশিত গতিবিধি বা মিডিয়াকে অবরুদ্ধ করেনি।",
 "reasonBlockedIncorrectly": "ভুলভাবে কিছু ব্লক বা পরিবর্তন করেছে",
 "reasonSiteCompatibility": "এটি আমার প্রয়োজনীয় একটি ওয়েবসাইটে কাজ করে নি",
 "reasonConfiguration": "কনফিগার করা বিভ্রান্তিকর ছিল",
 "reasonBugSlowdown": "বাগ, ধীরগতি বা সামঞ্জস্য সমস্যা তৈরি করেছে",
 "reasonNoLongerNeeded": "এখন আর প্রয়োজন নেই",
 "reasonPrivacyPermissions": "গোপনীয়তা বা অনুমতি নিয়ে উদ্বেগ",
 "reasonOther": "অন্যান্য",
 "detailsLabel": "কি ঘটেছে বা আপনি কী আশা করেছিলেন?",
 "detailsHelp": "ঐচ্ছিক। এক-দুইটি বাক্যই যথেষ্ট।",
 "featureLabel": "কোন বৈশিষ্ট্য থাকলে আপনি আবার চেষ্টা করতেন?",
 "featureHelp": "ঐচ্ছিক।",
 "contactLabel": "উত্তরের ঠিকানা",
 "contactHelp": "ঐচ্ছিক। উত্তর চাইলে তবেই দিন।",
 "submit": "প্রতিক্রিয়া পাঠান",
 "status": "প্রতিক্রিয়া Formspree দ্বারা প্রক্রিয়া করা হয়।",
 "footerSource": "উৎস"
 },
 "id": {
 "pageTitle": "MotionBlock Umpan Balik",
 "metaDescription": "Umpan balik uninstall opsional untuk MotionBlock.",
 "brandHomeLabel": "Beranda Oleksandr Molodchyk",
 "navLabel": "Navigasi utama",
 "navProjects": "Proyek",
 "navNow": "Sekarang",
 "navAbout": "Tentang",
 "navContact": "Kontak",
 "headline": "Bantu tingkatkan ekstensi",
 "intro": "Jika MotionBlock meleset dari sasaran, satu nada pendek sudah cukup. Formulir ini bersifat opsional dan tidak memerlukan informasi kontak.",
 "privacyNote": "Ekstensi membuka halaman ini setelah dihapus hanya dengan parameter umum sumber, versi, dan bahasa browser. Jangan sertakan data pribadi kecuali Anda memang ingin membagikannya.",
 "reasonLabel": "Mengapa Anda menghapusnya?",
 "chooseOne": "Pilih satu",
 "reasonNotEnough": "Itu tidak menghalangi gerakan atau media yang saya harapkan",
 "reasonBlockedIncorrectly": "Memblokir atau mengubah sesuatu secara keliru",
 "reasonSiteCompatibility": "Itu tidak berfungsi di situs web yang saya butuhkan",
 "reasonConfiguration": "Konfigurasinya membingungkan",
 "reasonBugSlowdown": "Menyebabkan bug, perlambatan, atau masalah kompatibilitas",
 "reasonNoLongerNeeded": "Saya tidak membutuhkannya lagi",
 "reasonPrivacyPermissions": "Kekhawatiran privasi atau izin",
 "reasonOther": "Lainnya",
 "detailsLabel": "Apa yang terjadi atau apa yang Anda harapkan?",
 "detailsHelp": "Opsional. Satu atau dua kalimat sudah cukup.",
 "featureLabel": "Fitur apa yang akan membuat Anda mencobanya lagi?",
 "featureHelp": "Opsional.",
 "contactLabel": "Alamat balasan",
 "contactHelp": "Opsional. Isi hanya jika Anda ingin mendapat balasan.",
 "submit": "Kirim masukan",
 "status": "Masukan diproses oleh Formspree.",
 "footerSource": "Sumber"
 },
 "uz": {
 "pageTitle": "MotionBlock Fikr-mulohazalar",
 "metaDescription": "Ixtiyoriy o'chirish fikr-mulohazasini MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk bosh sahifasi",
 "navLabel": "Asosiy navigatsiya",
 "navProjects": "Loyihalar",
 "navNow": "Hozir",
 "navAbout": "Haqida",
 "navContact": "Aloqa",
 "headline": "Kengaytmani yaxshilashga yordam bering",
 "intro": "Agar MotionBlock maqsadga yetmasa, bitta qisqa nota yetarli. Ushbu shakl ixtiyoriy bo'lib, aloqa ma'lumotlarini talab qilmaydi.",
 "privacyNote": "Kengaytma olib tashlangandan keyin bu sahifani faqat manba, versiya va brauzer tili haqidagi umumiy parametrlar bilan ochadi. Shaxsiy ma’lumotlarni faqat ataylab ulashmoqchi bo‘lsangiz kiriting.",
 "reasonLabel": "Nega olib tashladingiz?",
 "chooseOne": "Bittasini tanlang",
 "reasonNotEnough": "U men kutgan harakat yoki media to'sib qo'ymadi",
 "reasonBlockedIncorrectly": "Nimadirni noto‘g‘ri blokladi yoki o‘zgartirdi",
 "reasonSiteCompatibility": "Bu menga kerak bo'lgan veb-saytda ishlamadi",
 "reasonConfiguration": "Sozlash chalkash edi",
 "reasonBugSlowdown": "Xato, sekinlashish yoki moslik muammosini keltirdi",
 "reasonNoLongerNeeded": "Endi menga kerak emas",
 "reasonPrivacyPermissions": "Maxfiylik yoki ruxsatlar bo‘yicha xavotir",
 "reasonOther": "Boshqa",
 "detailsLabel": "Nima bo‘ldi yoki buning o‘rniga nimani kutgan edingiz?",
 "detailsHelp": "Ixtiyoriy. Bir-ikki gap yetarli.",
 "featureLabel": "Qaysi funksiya sizni yana sinab ko‘rishga undaydi?",
 "featureHelp": "Ixtiyoriy.",
 "contactLabel": "Javob uchun manzil",
 "contactHelp": "Ixtiyoriy. Faqat javob olishni istasangiz kiriting.",
 "submit": "Fikr yuborish",
 "status": "Fikr Formspree tomonidan qayta ishlanadi.",
 "footerSource": "Manba"
 },
 "ur": {
 "pageTitle": "MotionBlock رائے",
 "metaDescription": "اختیاری ان انسٹال فیڈبیک MotionBlock کے لیے۔",
 "brandHomeLabel": "Oleksandr Molodchyk ہوم",
 "navLabel": "مرکزی نیویگیشن",
 "navProjects": "پروجیکٹس",
 "navNow": "ابھی",
 "navAbout": "تعارف",
 "navContact": "رابطہ",
 "headline": "ایکسٹینشن کو بہتر بنانے میں مدد کریں",
 "intro": "اگر MotionBlock نشانہ نہیں لگا تو ایک مختصر نوٹ کافی ہے۔ یہ فارم اختیاری ہے اور رابطے کی معلومات کی ضرورت نہیں رکھتا۔",
 "privacyNote": "ایکسٹینشن اَن انسٹال ہونے کے بعد یہ صفحہ صرف عمومی source، version اور browser-language پیرامیٹرز کے ساتھ کھلتا ہے۔ ذاتی ڈیٹا شامل نہ کریں جب تک آپ جان بوجھ کر اسے شیئر نہیں کرنا چاہتے۔",
 "reasonLabel": "آپ نے اَن انسٹال کیوں کیا؟",
 "chooseOne": "ایک منتخب کریں",
 "reasonNotEnough": "اس نے وہ تحریک یا میڈیا نہیں روکا جس کی میں توقع کر رہا تھا",
 "reasonBlockedIncorrectly": "اس نے کچھ غلط طور پر بلاک یا تبدیل کیا",
 "reasonSiteCompatibility": "یہ اس ویب سائٹ پر کام نہیں کر رہا تھا جس کی مجھے ضرورت تھی",
 "reasonConfiguration": "اسے کنفیگر کرنا الجھا ہوا تھا",
 "reasonBugSlowdown": "اس نے بگ، سست رفتاری یا مطابقت کا مسئلہ پیدا کیا",
 "reasonNoLongerNeeded": "اب مجھے اس کی ضرورت نہیں",
 "reasonPrivacyPermissions": "پرائیویسی یا اجازتوں کا خدشہ",
 "reasonOther": "دیگر",
 "detailsLabel": "کیا ہوا یا آپ اس کے بجائے کیا توقع کر رہے تھے؟",
 "detailsHelp": "اختیاری۔ ایک یا دو جملے کافی ہیں۔",
 "featureLabel": "کون سی خصوصیت آپ کو دوبارہ آزمانے پر آمادہ کرے گی؟",
 "featureHelp": "اختیاری۔",
 "contactLabel": "جواب کا پتہ",
 "contactHelp": "اختیاری۔ صرف اس صورت میں شامل کریں اگر آپ جواب چاہتے ہیں۔",
 "submit": "رائے بھیجیں",
 "status": "رائے Formspree کے ذریعے پراسیس ہوتی ہے۔",
 "footerSource": "ماخذ"
 },
 "ko": {
 "pageTitle": "MotionBlock 피드백",
 "metaDescription": "선택 사항으로 삭제 피드백 MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk 홈",
 "navLabel": "기본 탐색",
 "navProjects": "프로젝트",
 "navNow": "현재",
 "navAbout": "소개",
 "navContact": "연락처",
 "headline": "확장 프로그램 개선에 도움을 주세요",
 "intro": "만약 MotionBlock 빗나갔다면, 짧은 음 한 개면 충분합니다. 이 양식은 선택 사항이며 연락처 정보는 필요 없습니다.",
 "privacyNote": "확장 프로그램은 제거 후 출처, 버전, 브라우저 언어라는 일반 매개변수만 포함해 이 페이지를 엽니다. 의도적으로 공유하려는 경우가 아니라면 개인 정보를 포함하지 마세요.",
 "reasonLabel": "왜 제거하셨나요?",
 "chooseOne": "하나 선택",
 "reasonNotEnough": "제가 예상했던 움직임이나 미디어를 막지 못했습니다",
 "reasonBlockedIncorrectly": "무언가를 잘못 차단하거나 변경했습니다",
 "reasonSiteCompatibility": "제가 필요로 하는 웹사이트에서는 작동하지 않았습니다",
 "reasonConfiguration": "설정하기 어려웠습니다",
 "reasonBugSlowdown": "버그, 속도 저하 또는 호환성 문제가 있었습니다",
 "reasonNoLongerNeeded": "더 이상 필요하지 않습니다",
 "reasonPrivacyPermissions": "개인정보 또는 권한이 걱정됩니다",
 "reasonOther": "기타",
 "detailsLabel": "무슨 일이 있었거나 무엇을 기대하셨나요?",
 "detailsHelp": "선택 사항입니다. 한두 문장이면 충분합니다.",
 "featureLabel": "어떤 기능이 있으면 다시 사용해 보시겠어요?",
 "featureHelp": "선택 사항입니다.",
 "contactLabel": "답장 받을 주소",
 "contactHelp": "선택 사항입니다. 답장을 원할 때만 입력하세요.",
 "submit": "피드백 보내기",
 "status": "피드백은 Formspree 에서 처리됩니다.",
 "footerSource": "소스"
 },
 "ro": {
 "pageTitle": "MotionBlock Feedback",
 "metaDescription": "Feedback opțional pentru dezinstalare pentru MotionBlock.",
 "brandHomeLabel": "Pagina principală Oleksandr Molodchyk",
 "navLabel": "Navigare principală",
 "navProjects": "Proiecte",
 "navNow": "Acum",
 "navAbout": "Despre",
 "navContact": "Contact",
 "headline": "Ajută la îmbunătățirea extensiei",
 "intro": "Dacă MotionBlock ratat, o singură notă scurtă este suficientă. Acest formular este opțional și nu necesită informații de contact.",
 "privacyNote": "Extensia deschide această pagină după dezinstalare doar cu parametri generici pentru sursă, versiune și limba browserului. Nu include date personale decât dacă vrei intenționat să le distribui.",
 "reasonLabel": "De ce ai dezinstalat?",
 "chooseOne": "Alege o opțiune",
 "reasonNotEnough": "Nu a blocat mișcarea sau mediul pe care îl așteptam",
 "reasonBlockedIncorrectly": "A blocat sau a schimbat ceva incorect",
 "reasonSiteCompatibility": "Nu a funcționat pe un site de care aveam nevoie",
 "reasonConfiguration": "A fost confuz de configurat",
 "reasonBugSlowdown": "A cauzat o eroare, încetinire sau problemă de compatibilitate",
 "reasonNoLongerNeeded": "Nu mai am nevoie de el",
 "reasonPrivacyPermissions": "Îngrijorare privind confidențialitatea sau permisiunile",
 "reasonOther": "Altceva",
 "detailsLabel": "Ce s-a întâmplat sau ce te așteptai să se întâmple?",
 "detailsHelp": "Opțional. Una sau două propoziții sunt suficiente.",
 "featureLabel": "Ce funcție te-ar face să îl încerci din nou?",
 "featureHelp": "Opțional.",
 "contactLabel": "Adresă pentru răspuns",
 "contactHelp": "Opțional. Include-o doar dacă vrei un răspuns.",
 "submit": "Trimite feedback",
 "status": "Feedbackul este procesat prin Formspree.",
 "footerSource": "Sursă"
 }
};
