export const LOCALE_COPY_GROUP_9 = {
 "ca": {
 "pageTitle": "MotionBlock Comentaris",
 "metaDescription": "Comentaris opcionals de desinstal·lació per a MotionBlock.",
 "brandHomeLabel": "Inici d'Oleksandr Molodchyk",
 "navLabel": "Navegació principal",
 "navProjects": "Projectes",
 "navNow": "Ara",
 "navAbout": "Sobre mi",
 "navContact": "Contacte",
 "headline": "Ajuda a millorar l'extensió",
 "intro": "Si MotionBlock fallat, una nota curta és suficient. Aquest formulari és opcional i no requereix informació de contacte.",
 "privacyNote": "L'extensió obre aquesta pàgina després de desinstal·lar-la només amb paràmetres genèrics de font, versió i idioma del navegador. No incloguis dades personals tret que les vulguis compartir.",
 "reasonLabel": "Per què l'has desinstal·lada?",
 "chooseOne": "Tria una opció",
 "reasonNotEnough": "No va bloquejar el moviment ni els mitjans que esperava",
 "reasonBlockedIncorrectly": "Bloquejava o canviava alguna cosa incorrectament",
 "reasonSiteCompatibility": "No va funcionar en un lloc web que necessitava",
 "reasonConfiguration": "Era confusa de configurar",
 "reasonBugSlowdown": "Causava un error, lentitud o problemes de compatibilitat",
 "reasonNoLongerNeeded": "Ja no la necessito",
 "reasonPrivacyPermissions": "Preocupació de privadesa o permisos",
 "reasonOther": "Altres",
 "detailsLabel": "Què ha passat o què esperaves en lloc d'això?",
 "detailsHelp": "Opcional. Una o dues frases són suficients.",
 "featureLabel": "Quina funció et faria provar-la de nou?",
 "featureHelp": "Opcional.",
 "contactLabel": "Adreça de resposta",
 "contactHelp": "Opcional. Inclou-la només si vols una resposta.",
 "submit": "Envia els comentaris",
 "status": "Els comentaris es processen amb Formspree.",
 "footerSource": "Codi font"
 },
 "sl": {
 "pageTitle": "MotionBlock Povratne informacije",
 "metaDescription": "Neobvezne povratne informacije za odstranitev za MotionBlock.",
 "brandHomeLabel": "Domača stran Oleksandra Molodchyka",
 "navLabel": "Glavna navigacija",
 "navProjects": "Projekti",
 "navNow": "Zdaj",
 "navAbout": "O meni",
 "navContact": "Kontakt",
 "headline": "Pomagajte izboljšati razširitev",
 "intro": "Če MotionBlock zgrešili, je dovolj ena kratka nota. Ta obrazec je neobvezen in ne zahteva kontaktnih podatkov.",
 "privacyNote": "Razširitev po odstranitvi odpre to stran samo s splošnimi parametri vira, različice in jezika brskalnika. Ne vnašajte osebnih podatkov, razen če jih namenoma želite deliti.",
 "reasonLabel": "Zakaj ste jo odstranili?",
 "chooseOne": "Izberite eno možnost",
 "reasonNotEnough": "Niso blokirali gibanja ali medijev, ki sem jih pričakoval",
 "reasonBlockedIncorrectly": "Nekaj je napačno blokirala ali spremenila",
 "reasonSiteCompatibility": "Ni delovalo na spletni strani, ki sem jo potreboval",
 "reasonConfiguration": "Konfiguracija je bila zmedena",
 "reasonBugSlowdown": "Povzročila je napako, upočasnitev ali težavo z združljivostjo",
 "reasonNoLongerNeeded": "Ne potrebujem je več",
 "reasonPrivacyPermissions": "Skrb glede zasebnosti ali dovoljenj",
 "reasonOther": "Drugo",
 "detailsLabel": "Kaj se je zgodilo ali kaj ste pričakovali namesto tega?",
 "detailsHelp": "Neobvezno. En ali dva stavka sta dovolj.",
 "featureLabel": "Katera funkcija bi vas prepričala, da jo poskusite znova?",
 "featureHelp": "Neobvezno.",
 "contactLabel": "Naslov za odgovor",
 "contactHelp": "Neobvezno. Dodajte ga samo, če želite odgovor.",
 "submit": "Pošlji povratne informacije",
 "status": "Povratne informacije obdeluje Formspree.",
 "footerSource": "Vir"
 },
 "gu": {
 "pageTitle": "MotionBlock પ્રતિસાદ",
 "metaDescription": "MotionBlock માટે વૈકલ્પિક પ્રતિસાદ અનઇન્સ્ટોલ કરો.",
 "brandHomeLabel": "Oleksandr Molodchyk હોમ",
 "navLabel": "મુખ્ય નેવિગેશન",
 "navProjects": "પ્રોજેક્ટ્સ",
 "navNow": "હમણાં",
 "navAbout": "વિશે",
 "navContact": "સંપર્ક",
 "headline": "એક્સ્ટેન્શન સુધારવામાં મદદ કરો",
 "intro": "જો MotionBlock નિશાન ચૂકી ગયા હોય, તો એક ટૂંકી નોંધ પૂરતી છે. આ ફોર્મ વૈકલ્પિક છે અને સંપર્ક માહિતીની જરૂર નથી.",
 "privacyNote": "એક્સ્ટેન્શન અનઇન્સ્ટોલ થયા પછી આ પૃષ્ઠ માત્ર સામાન્ય source, version અને browser-language પરિમાણો સાથે ખોલે છે. તમે જાણબૂઝીને શેર કરવા ન માંગતા હોવ તો વ્યક્તિગત માહિતી ન આપો.",
 "reasonLabel": "તમે તેને શા માટે અનઇન્સ્ટોલ કર્યું?",
 "chooseOne": "એક પસંદ કરો",
 "reasonNotEnough": "તે મારી અપેક્ષા મુજબ ગતિ અથવા મીડિયાને અવરોધિત કરતું નથી",
 "reasonBlockedIncorrectly": "તે કંઈક ખોટી રીતે બ્લોક અથવા બદલતું હતું",
 "reasonSiteCompatibility": "તે મને જરૂરી વેબસાઇટ પર કામ કરતું ન હતું",
 "reasonConfiguration": "તે ગોઠવવું ગૂંચવણભર્યું હતું",
 "reasonBugSlowdown": "તેના કારણે બગ, ધીમું પડવું અથવા સુસંગતતા સમસ્યા થઈ",
 "reasonNoLongerNeeded": "હવે મને તેની જરૂર નથી",
 "reasonPrivacyPermissions": "ગોપનીયતા અથવા પરવાનગીઓ અંગે ચિંતા",
 "reasonOther": "અન્ય",
 "detailsLabel": "શું થયું અથવા તેના બદલે તમે શું અપેક્ષા રાખી હતી?",
 "detailsHelp": "વૈકલ્પિક. એક કે બે વાક્ય પૂરતા છે.",
 "featureLabel": "કઈ સુવિધા તમને તેને ફરી અજમાવવા પ્રેરિત કરશે?",
 "featureHelp": "વૈકલ્પિક.",
 "contactLabel": "જવાબ માટેનું સરનામું",
 "contactHelp": "વૈકલ્પિક. જવાબ જોઈએ તો જ ઉમેરો.",
 "submit": "પ્રતિસાદ મોકલો",
 "status": "પ્રતિસાદ Formspree દ્વારા પ્રક્રિયા થાય છે.",
 "footerSource": "સ્ત્રોત"
 },
 "ms": {
 "pageTitle": "MotionBlock Maklum Balas",
 "metaDescription": "Maklum balas nyahpasang pilihan untuk MotionBlock.",
 "brandHomeLabel": "Laman utama Oleksandr Molodchyk",
 "navLabel": "Navigasi utama",
 "navProjects": "Projek",
 "navNow": "Kini",
 "navAbout": "Tentang",
 "navContact": "Hubungi",
 "headline": "Bantu perbaiki sambungan ini",
 "intro": "Jika MotionBlock terlepas sasaran, satu nota pendek sudah memadai. Borang ini adalah pilihan dan tidak memerlukan maklumat hubungan.",
 "privacyNote": "Sambungan membuka halaman ini selepas dinyahpasang dengan hanya parameter umum sumber, versi dan bahasa pelayar. Jangan sertakan data peribadi kecuali anda sengaja mahu berkongsinya.",
 "reasonLabel": "Mengapa anda menyahpasang?",
 "chooseOne": "Pilih satu",
 "reasonNotEnough": "Ia tidak menyekat gerakan atau media yang saya jangkakan",
 "reasonBlockedIncorrectly": "Ia menyekat atau mengubah sesuatu dengan salah",
 "reasonSiteCompatibility": "Ia tidak berfungsi di laman web yang saya perlukan",
 "reasonConfiguration": "Ia mengelirukan untuk dikonfigurasi",
 "reasonBugSlowdown": "Ia menyebabkan pepijat, kelembapan atau isu keserasian",
 "reasonNoLongerNeeded": "Saya tidak memerlukannya lagi",
 "reasonPrivacyPermissions": "Kebimbangan privasi atau kebenaran",
 "reasonOther": "Lain-lain",
 "detailsLabel": "Apa yang berlaku atau apa yang anda jangkakan?",
 "detailsHelp": "Pilihan. Satu atau dua ayat sudah mencukupi.",
 "featureLabel": "Ciri apakah yang akan membuat anda mencubanya lagi?",
 "featureHelp": "Pilihan.",
 "contactLabel": "Alamat balasan",
 "contactHelp": "Pilihan. Sertakan hanya jika anda mahu balasan.",
 "submit": "Hantar maklum balas",
 "status": "Maklum balas diproses oleh Formspree.",
 "footerSource": "Sumber"
 },
 "pt_BR": {
 "pageTitle": "MotionBlock Feedback",
 "metaDescription": "Feedback opcional de desinstalação para MotionBlock.",
 "brandHomeLabel": "Página inicial de Oleksandr Molodchyk",
 "navLabel": "Navegação principal",
 "navProjects": "Projetos",
 "navNow": "Agora",
 "navAbout": "Sobre",
 "navContact": "Contato",
 "headline": "Ajude a melhorar a extensão",
 "intro": "Se MotionBlock errado, uma nota curta já é suficiente. Este formulário é opcional e não requer informações de contato.",
 "privacyNote": "A extensão abre esta página após a desinstalação apenas com parâmetros genéricos de origem, versão e idioma do navegador. Não inclua dados pessoais, a menos que queira compartilhá-los intencionalmente.",
 "reasonLabel": "Por que você desinstalou?",
 "chooseOne": "Escolha uma opção",
 "reasonNotEnough": "Não bloqueou o movimento nem a mídia que eu esperava",
 "reasonBlockedIncorrectly": "Bloqueou ou alterou algo incorretamente",
 "reasonSiteCompatibility": "Não funcionou em um site que eu precisava",
 "reasonConfiguration": "Era confuso de configurar",
 "reasonBugSlowdown": "Causou bug, lentidão ou problema de compatibilidade",
 "reasonNoLongerNeeded": "Não preciso mais",
 "reasonPrivacyPermissions": "Preocupação com privacidade ou permissões",
 "reasonOther": "Outro",
 "detailsLabel": "O que aconteceu ou o que você esperava?",
 "detailsHelp": "Opcional. Uma ou duas frases bastam.",
 "featureLabel": "Qual recurso faria você tentar de novo?",
 "featureHelp": "Opcional.",
 "contactLabel": "Endereço para resposta",
 "contactHelp": "Opcional. Inclua apenas se quiser uma resposta.",
 "submit": "Enviar feedback",
 "status": "O feedback é processado pelo Formspree.",
 "footerSource": "Código-fonte"
 },
 "ne": {
 "pageTitle": "MotionBlock प्रतिक्रिया",
 "metaDescription": "MotionBlock का लागि वैकल्पिक स्थापनाबाट हटाइएको पृष्ठपोषण ।",
 "brandHomeLabel": "Oleksandr Molodchyk गृहपृष्ठ",
 "navLabel": "मुख्य नेभिगेसन",
 "navProjects": "परियोजनाहरू",
 "navNow": "अहिले",
 "navAbout": "बारेमा",
 "navContact": "सम्पर्क",
 "headline": "एक्सटेन्सन सुधार गर्न मद्दत गर्नुहोस्",
 "intro": "यदि MotionBlock चिन्ह छुटेको छ भने, एउटा छोटो नोट पर्याप्त छ। यो फारम वैकल्पिक हो र सम्पर्क जानकारी आवश्यक पर्दैन।",
 "privacyNote": "एक्सटेन्सन अनइन्स्टल भएपछि यो पृष्ठ स्रोत, संस्करण र ब्राउजर भाषाका सामान्य प्यारामिटरहरू मात्र लिएर खुल्छ। जानाजानी साझा गर्न नचाहनुहुन्छ भने व्यक्तिगत डेटा नराख्नुहोस्।",
 "reasonLabel": "किन अनइन्स्टल गर्नुभयो?",
 "chooseOne": "एउटा छान्नुहोस्",
 "reasonNotEnough": "यसले मैले अपेक्षा गरेको प्रस्ताव वा मिडियालाई ब्लक गरेन",
 "reasonBlockedIncorrectly": "केही गलत रूपमा ब्लक वा परिवर्तन गर्‍यो",
 "reasonSiteCompatibility": "यो मलाई आवश्यक वेबसाइटमा काम गरेन",
 "reasonConfiguration": "कन्फिगर गर्न अलमलिलो थियो",
 "reasonBugSlowdown": "बग, ढिलाइ वा अनुकूलता समस्या ल्यायो",
 "reasonNoLongerNeeded": "अब मलाई यसको आवश्यकता छैन",
 "reasonPrivacyPermissions": "गोपनीयता वा अनुमति सम्बन्धी चिन्ता",
 "reasonOther": "अन्य",
 "detailsLabel": "के भयो वा त्यसको सट्टा के अपेक्षा गर्नुभएको थियो?",
 "detailsHelp": "वैकल्पिक। एक-दुई वाक्य पर्याप्त हुन्छ।",
 "featureLabel": "कुन सुविधाले तपाईंलाई फेरि प्रयास गर्न लगाउँथ्यो?",
 "featureHelp": "वैकल्पिक।",
 "contactLabel": "जवाफ ठेगाना",
 "contactHelp": "वैकल्पिक। जवाफ चाहनुहुन्छ भने मात्र राख्नुहोस्।",
 "submit": "प्रतिक्रिया पठाउनुहोस्",
 "status": "प्रतिक्रिया Formspree द्वारा प्रशोधन गरिन्छ।",
 "footerSource": "स्रोत"
 }
};
