export const LOCALE_COPY_GROUP_2 = {
 "az": {
 "pageTitle": "MotionBlock Rəy",
 "metaDescription": "MotionBlock üçün istəyə bağlı silinmə geribildirimi.",
 "brandHomeLabel": "Oleksandr Molodchyk ana səhifəsi",
 "navLabel": "Əsas naviqasiya",
 "navProjects": "Layihələr",
 "navNow": "İndi",
 "navAbout": "Haqqında",
 "navContact": "Əlaqə",
 "headline": "Genişlənməni yaxşılaşdırmağa kömək edin",
 "intro": "Əgər MotionBlock hədəfi qaçırıbsa, bir qısa not kifayətdir. Bu form seçimlidir və əlaqə məlumatı tələb etmir.",
 "privacyNote": "Genişlənmə silindikdən sonra bu səhifəni yalnız ümumi mənbə, versiya və brauzer dili parametrləri ilə açır. Şəxsi məlumatları yalnız bilərəkdən paylaşmaq istəyirsinizsə daxil edin.",
 "reasonLabel": "Niyə sildiniz?",
 "chooseOne": "Birini seçin",
 "reasonNotEnough": "Gözlədiyim hərəkəti və ya medianı bloklamadı",
 "reasonBlockedIncorrectly": "Nəyisə səhv blokladı və ya dəyişdi",
 "reasonSiteCompatibility": "Mənə lazım olan vebsaytda işləmədi",
 "reasonConfiguration": "Quraşdırmaq çaşdırıcı idi",
 "reasonBugSlowdown": "Xəta, yavaşlama və ya uyğunluq problemi yaratdı",
 "reasonNoLongerNeeded": "Artıq ehtiyacım yoxdur",
 "reasonPrivacyPermissions": "Məxfilik və ya icazə narahatlığı",
 "reasonOther": "Digər",
 "detailsLabel": "Nə baş verdi və ya əvəzində nə gözləyirdiniz?",
 "detailsHelp": "İstəyə bağlıdır. Bir-iki cümlə kifayətdir.",
 "featureLabel": "Hansı xüsusiyyət sizi yenidən sınamağa vadar edərdi?",
 "featureHelp": "İstəyə bağlıdır.",
 "contactLabel": "Cavab ünvanı",
 "contactHelp": "İstəyə bağlıdır. Yalnız cavab istəyirsinizsə əlavə edin.",
 "submit": "Rəy göndər",
 "status": "Rəy Formspree tərəfindən emal olunur.",
 "footerSource": "Mənbə"
 },
 "sk": {
 "pageTitle": "MotionBlock Spätná väzba",
 "metaDescription": "Voliteľná spätná väzba na odinštalovanie pre MotionBlock.",
 "brandHomeLabel": "Domovská stránka Oleksandra Molodchyka",
 "navLabel": "Hlavná navigácia",
 "navProjects": "Projekty",
 "navNow": "Teraz",
 "navAbout": "O mne",
 "navContact": "Kontakt",
 "headline": "Pomôžte zlepšiť rozšírenie",
 "intro": "Ak MotionBlock netrafili, stačí jeden krátky tón. Tento formulár je voliteľný a nevyžaduje kontaktné údaje.",
 "privacyNote": "Rozšírenie po odinštalovaní otvorí túto stránku iba so všeobecnými parametrami zdroja, verzie a jazyka prehliadača. Neuvádzajte osobné údaje, pokiaľ ich nechcete zámerne zdieľať.",
 "reasonLabel": "Prečo ste odinštalovali?",
 "chooseOne": "Vyberte jednu možnosť",
 "reasonNotEnough": "Nezastavilo to pohyb ani médiá, ktoré som očakával",
 "reasonBlockedIncorrectly": "Niečo blokovalo alebo menilo nesprávne",
 "reasonSiteCompatibility": "Nefungovalo to na stránke, ktorú som potreboval",
 "reasonConfiguration": "Konfigurácia bola mätúca",
 "reasonBugSlowdown": "Spôsobovalo chybu, spomalenie alebo problém s kompatibilitou",
 "reasonNoLongerNeeded": "Už ho nepotrebujem",
 "reasonPrivacyPermissions": "Obava o súkromie alebo povolenia",
 "reasonOther": "Iné",
 "detailsLabel": "Čo sa stalo alebo čo ste očakávali namiesto toho?",
 "detailsHelp": "Voliteľné. Stačí jedna alebo dve vety.",
 "featureLabel": "Aká funkcia by vás prinútila vyskúšať ho znova?",
 "featureHelp": "Voliteľné.",
 "contactLabel": "Adresa na odpoveď",
 "contactHelp": "Voliteľné. Uveďte ju iba vtedy, ak chcete odpoveď.",
 "submit": "Odoslať spätnú väzbu",
 "status": "Spätnú väzbu spracúva Formspree.",
 "footerSource": "Zdroj"
 },
 "pa": {
 "pageTitle": "MotionBlock ਫੀਡਬੈਕ",
 "metaDescription": "MotionBlock ਲਈ ਵਿਕਲਪਿਕ ਫੀਡਬੈਕ ਨੂੰ ਅਣਇੰਸਟਾਲ ਕਰੋ।",
 "brandHomeLabel": "Oleksandr Molodchyk ਹੋਮ",
 "navLabel": "ਮੁੱਖ ਨੇਵੀਗੇਸ਼ਨ",
 "navProjects": "ਪ੍ਰੋਜੈਕਟ",
 "navNow": "ਹੁਣ",
 "navAbout": "ਬਾਰੇ",
 "navContact": "ਸੰਪਰਕ",
 "headline": "ਐਕਸਟੈਂਸ਼ਨ ਨੂੰ ਸੁਧਾਰਨ ਵਿੱਚ ਮਦਦ ਕਰੋ",
 "intro": "ਜੇ MotionBlock ਨਿਸ਼ਾਨ ਤੋਂ ਖੁੰਝ ਗਏ ਹਨ, ਤਾਂ ਇੱਕ ਛੋਟਾ ਨੋਟ ਕਾਫ਼ੀ ਹੈ. ਇਹ ਫਾਰਮ ਵਿਕਲਪਕ ਹੈ ਅਤੇ ਇਸਨੂੰ ਸੰਪਰਕ ਜਾਣਕਾਰੀ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ।",
 "privacyNote": "ਐਕਸਟੈਂਸ਼ਨ ਅਣਇੰਸਟਾਲ ਹੋਣ ਤੋਂ ਬਾਅਦ ਇਹ ਪੰਨਾ ਸਿਰਫ਼ ਆਮ source, version ਅਤੇ browser-language ਪੈਰਾਮੀਟਰਾਂ ਨਾਲ ਖੋਲ੍ਹਦਾ ਹੈ। ਨਿੱਜੀ ਡਾਟਾ ਨਾ ਸ਼ਾਮਲ ਕਰੋ ਜਦ ਤੱਕ ਤੁਸੀਂ ਜਾਣਬੁੱਝ ਕੇ ਸਾਂਝਾ ਨਹੀਂ ਕਰਨਾ ਚਾਹੁੰਦੇ।",
 "reasonLabel": "ਤੁਸੀਂ ਇਸਨੂੰ ਕਿਉਂ ਅਣਇੰਸਟਾਲ ਕੀਤਾ?",
 "chooseOne": "ਇੱਕ ਚੁਣੋ",
 "reasonNotEnough": "ਇਸ ਨੇ ਉਸ ਮੋਸ਼ਨ ਜਾਂ ਮੀਡੀਆ ਨੂੰ ਬਲੌਕ ਨਹੀਂ ਕੀਤਾ ਜਿਸਦੀ ਮੈਂ ਉਮੀਦ ਕੀਤੀ ਸੀ",
 "reasonBlockedIncorrectly": "ਇਸਨੇ ਕੁਝ ਗਲਤ ਤਰੀਕੇ ਨਾਲ ਬਲਾਕ ਜਾਂ ਬਦਲਿਆ",
 "reasonSiteCompatibility": "ਇਹ ਉਸ ਵੈਬਸਾਈਟ 'ਤੇ ਕੰਮ ਨਹੀਂ ਕਰਦਾ ਜਿਸ ਦੀ ਮੈਨੂੰ ਲੋੜ ਸੀ",
 "reasonConfiguration": "ਇਸਨੂੰ ਕਨਫਿਗਰ ਕਰਨਾ ਗੁੰਝਲਦਾਰ ਸੀ",
 "reasonBugSlowdown": "ਇਸਨੇ ਬੱਗ, ਸੁਸਤੀ ਜਾਂ ਅਨੁਕੂਲਤਾ ਸਮੱਸਿਆ ਪੈਦਾ ਕੀਤੀ",
 "reasonNoLongerNeeded": "ਹੁਣ ਮੈਨੂੰ ਇਸਦੀ ਲੋੜ ਨਹੀਂ",
 "reasonPrivacyPermissions": "ਗੋਪਨੀਯਤਾ ਜਾਂ ਇਜਾਜ਼ਤਾਂ ਬਾਰੇ ਚਿੰਤਾ",
 "reasonOther": "ਹੋਰ",
 "detailsLabel": "ਕੀ ਹੋਇਆ ਜਾਂ ਤੁਸੀਂ ਇਸਦੀ ਥਾਂ ਕੀ ਉਮੀਦ ਕੀਤੀ ਸੀ?",
 "detailsHelp": "ਵਿਕਲਪਿਕ। ਇੱਕ-ਦੋ ਵਾਕ ਕਾਫ਼ੀ ਹਨ।",
 "featureLabel": "ਕਿਹੜੀ ਵਿਸ਼ੇਸ਼ਤਾ ਤੁਹਾਨੂੰ ਇਸਨੂੰ ਮੁੜ ਅਜ਼ਮਾਉਣ ਲਈ ਮਜਬੂਰ ਕਰੇਗੀ?",
 "featureHelp": "ਵਿਕਲਪਿਕ।",
 "contactLabel": "ਜਵਾਬ ਦਾ ਪਤਾ",
 "contactHelp": "ਵਿਕਲਪਿਕ। ਜਵਾਬ ਚਾਹੀਦਾ ਹੋਵੇ ਤਾਂ ਹੀ ਸ਼ਾਮਲ ਕਰੋ।",
 "submit": "ਫੀਡਬੈਕ ਭੇਜੋ",
 "status": "ਫੀਡਬੈਕ Formspree ਦੁਆਰਾ ਪ੍ਰਕਿਰਿਆ ਕੀਤਾ ਜਾਂਦਾ ਹੈ।",
 "footerSource": "ਸਰੋਤ"
 },
 "sw": {
 "pageTitle": "MotionBlock Maoni",
 "metaDescription": "Hiari ondoa maoni kwa MotionBlock.",
 "brandHomeLabel": "Nyumbani kwa Oleksandr Molodchyk",
 "navLabel": "Urambazaji mkuu",
 "navProjects": "Miradi",
 "navNow": "Sasa",
 "navAbout": "Kuhusu",
 "navContact": "Mawasiliano",
 "headline": "Saidia kuboresha kiendelezi",
 "intro": "Ikiwa MotionBlock umekosa alama, noti moja fupi inatosha. Fomu hii ni ya hiari na haihitaji maelezo ya mawasiliano.",
 "privacyNote": "Kiendelezi hufungua ukurasa huu baada ya kuondolewa kikiwa na vigezo vya jumla tu vya chanzo, toleo na lugha ya kivinjari. Usiweke data binafsi isipokuwa unataka kuishiriki kwa makusudi.",
 "reasonLabel": "Kwa nini uliiondoa?",
 "chooseOne": "Chagua moja",
 "reasonNotEnough": "Haikuzuia mwendo au media niliyotarajia",
 "reasonBlockedIncorrectly": "Ilizuia au kubadilisha kitu kimakosa",
 "reasonSiteCompatibility": "Haikufanya kazi kwenye wavuti niliyohitaji",
 "reasonConfiguration": "Ilikuwa inachanganya kusanidi",
 "reasonBugSlowdown": "Ilisababisha hitilafu, kupungua kasi au tatizo la uoanifu",
 "reasonNoLongerNeeded": "Sihitaji tena",
 "reasonPrivacyPermissions": "Wasiwasi wa faragha au ruhusa",
 "reasonOther": "Nyingine",
 "detailsLabel": "Nini kilitokea au ulitarajia nini badala yake?",
 "detailsHelp": "Hiari. Sentensi moja au mbili zinatosha.",
 "featureLabel": "Kipengele gani kingekufanya ujaribu tena?",
 "featureHelp": "Hiari.",
 "contactLabel": "Anwani ya kujibiwa",
 "contactHelp": "Hiari. Weka tu ikiwa unataka jibu.",
 "submit": "Tuma maoni",
 "status": "Maoni huchakatwa na Formspree.",
 "footerSource": "Chanzo"
 },
 "pl": {
 "pageTitle": "MotionBlock Opinie",
 "metaDescription": "Opcjonalna informacja zwrotna z instalacji dla MotionBlock.",
 "brandHomeLabel": "Strona główna Oleksandra Molodchyka",
 "navLabel": "Główna nawigacja",
 "navProjects": "Projekty",
 "navNow": "Teraz",
 "navAbout": "O mnie",
 "navContact": "Kontakt",
 "headline": "Pomóż ulepszyć rozszerzenie",
 "intro": "Jeśli MotionBlock nie trafił, wystarczy jedna krótka nuta. Ten formularz jest opcjonalny i nie wymaga danych kontaktowych.",
 "privacyNote": "Rozszerzenie otwiera tę stronę po odinstalowaniu tylko z ogólnymi parametrami źródła, wersji i języka przeglądarki. Nie podawaj danych osobowych, chyba że świadomie chcesz je udostępnić.",
 "reasonLabel": "Dlaczego odinstalowano rozszerzenie?",
 "chooseOne": "Wybierz jedną opcję",
 "reasonNotEnough": "Nie zablokowało to ruchu ani mediów, których się spodziewałem",
 "reasonBlockedIncorrectly": "Coś było błędnie blokowane lub zmieniane",
 "reasonSiteCompatibility": "Nie zadziałało na stronie, której potrzebowałem",
 "reasonConfiguration": "Konfiguracja była myląca",
 "reasonBugSlowdown": "Powodowało błąd, spowolnienie lub problem ze zgodnością",
 "reasonNoLongerNeeded": "Nie jest mi już potrzebne",
 "reasonPrivacyPermissions": "Obawy dotyczące prywatności lub uprawnień",
 "reasonOther": "Inne",
 "detailsLabel": "Co się stało albo czego oczekiwano?",
 "detailsHelp": "Opcjonalnie. Wystarczy jedno lub dwa zdania.",
 "featureLabel": "Jaka funkcja zachęciłaby do ponownej próby?",
 "featureHelp": "Opcjonalnie.",
 "contactLabel": "Adres do odpowiedzi",
 "contactHelp": "Opcjonalnie. Podaj tylko, jeśli chcesz otrzymać odpowiedź.",
 "submit": "Wyślij opinię",
 "status": "Opinia jest obsługiwana przez Formspree.",
 "footerSource": "Źródło"
 },
 "ar": {
 "pageTitle": "MotionBlock التعليقات",
 "metaDescription": "ملاحظات اختيارية لإزالة التثبيت MotionBlock.",
 "brandHomeLabel": "الصفحة الرئيسية لأوليكساندر مولودتشيك",
 "navLabel": "التنقل الرئيسي",
 "navProjects": "المشاريع",
 "navNow": "الآن",
 "navAbout": "حول",
 "navContact": "تواصل",
 "headline": "ساعد في تحسين الإضافة",
 "intro": "إذا أخطأت MotionBlock الهدف، تكفي نغمة قصيرة واحدة. هذا النموذج اختياري ولا يتطلب معلومات اتصال.",
 "privacyNote": "تفتح الإضافة هذه الصفحة بعد إلغاء التثبيت مع معلمات عامة فقط: المصدر والإصدار ولغة المتصفح. لا تدرج بيانات شخصية إلا إذا كنت تريد مشاركتها عمدا.",
 "reasonLabel": "لماذا ألغيت التثبيت؟",
 "chooseOne": "اختر سببا",
 "reasonNotEnough": "لم يمنع الحركة أو الوسائط التي توقعتها",
 "reasonBlockedIncorrectly": "حظر أو غيّر شيئا بشكل غير صحيح",
 "reasonSiteCompatibility": "لم يعمل على موقع إلكتروني كنت بحاجة إليه",
 "reasonConfiguration": "كان ضبطه مربكا",
 "reasonBugSlowdown": "سبب خللا أو بطئا أو مشكلة توافق",
 "reasonNoLongerNeeded": "لم أعد بحاجة إليه",
 "reasonPrivacyPermissions": "مشكلة خصوصية أو أذونات",
 "reasonOther": "غير ذلك",
 "detailsLabel": "ماذا حدث، أو ماذا كنت تتوقع بدلا من ذلك؟",
 "detailsHelp": "اختياري. تكفي جملة أو جملتان.",
 "featureLabel": "ما الميزة التي قد تجعلك تجربه مرة أخرى؟",
 "featureHelp": "اختياري.",
 "contactLabel": "عنوان للرد",
 "contactHelp": "اختياري. أضفه فقط إذا كنت تريد ردا.",
 "submit": "إرسال الملاحظات",
 "status": "تتم معالجة الملاحظات عبر Formspree.",
 "footerSource": "المصدر"
 },
 "tr": {
 "pageTitle": "MotionBlock Geri Bildirim",
 "metaDescription": "MotionBlock için isteğe bağlı silinme geri bildirimi.",
 "brandHomeLabel": "Oleksandr Molodchyk ana sayfası",
 "navLabel": "Ana gezinme",
 "navProjects": "Projeler",
 "navNow": "Şimdi",
 "navAbout": "Hakkında",
 "navContact": "İletişim",
 "headline": "Uzantıyı geliştirmeye yardım edin",
 "intro": "Eğer MotionBlock hedefi kaçırmışsa, kısa bir nota yeterli. Bu form isteğe bağlıdır ve iletişim bilgisi gerektirmez.",
 "privacyNote": "Uzantı, kaldırıldıktan sonra bu sayfayı yalnızca genel kaynak, sürüm ve tarayıcı dili parametreleriyle açar. Bilerek paylaşmak istemiyorsanız kişisel veri eklemeyin.",
 "reasonLabel": "Neden kaldırdınız?",
 "chooseOne": "Birini seçin",
 "reasonNotEnough": "Beklediğim hareketi veya medyayı engellemedi",
 "reasonBlockedIncorrectly": "Bir şeyi yanlış engelledi veya değiştirdi",
 "reasonSiteCompatibility": "İhtiyacım olan bir web sitesinde çalışmadı",
 "reasonConfiguration": "Yapılandırması kafa karıştırıcıydı",
 "reasonBugSlowdown": "Hata, yavaşlama veya uyumluluk sorunu oluşturdu",
 "reasonNoLongerNeeded": "Artık ihtiyacım yok",
 "reasonPrivacyPermissions": "Gizlilik veya izin endişesi",
 "reasonOther": "Diğer",
 "detailsLabel": "Ne oldu veya bunun yerine ne bekliyordunuz?",
 "detailsHelp": "İsteğe bağlı. Bir iki cümle yeterlidir.",
 "featureLabel": "Hangi özellik tekrar denemenizi sağlar?",
 "featureHelp": "İsteğe bağlı.",
 "contactLabel": "Yanıt adresi",
 "contactHelp": "İsteğe bağlı. Yalnızca yanıt istiyorsanız ekleyin.",
 "submit": "Geri bildirim gönder",
 "status": "Geri bildirim Formspree tarafından işlenir.",
 "footerSource": "Kaynak"
 }
};
