export const LOCALE_COPY_GROUP_7 = {
 "th": {
 "pageTitle": "ข้อเสนอแนะ MotionBlock",
 "metaDescription": "ข้อเสนอแนะการถอนการติดตั้งเพิ่มเติมสําหรับ MotionBlock",
 "brandHomeLabel": "หน้าแรกของ Oleksandr Molodchyk",
 "navLabel": "การนำทางหลัก",
 "navProjects": "โปรเจกต์",
 "navNow": "ตอนนี้",
 "navAbout": "เกี่ยวกับ",
 "navContact": "ติดต่อ",
 "headline": "ช่วยปรับปรุงส่วนขยายนี้",
 "intro": "หาก MotionBlock พลาดเป้า โน้ตสั้น ๆ เพียงตัวเดียวก็เพียงพอแล้ว แบบฟอร์มนี้เป็นทางเลือกและไม่ต้องใช้ข้อมูลติดต่อ",
 "privacyNote": "ส่วนขยายจะเปิดหน้านี้หลังถอนการติดตั้ง โดยมีเพียงพารามิเตอร์ทั่วไปของแหล่งที่มา เวอร์ชัน และภาษาของเบราว์เซอร์ อย่าใส่ข้อมูลส่วนตัวเว้นแต่คุณตั้งใจจะแชร์",
 "reasonLabel": "ทำไมคุณจึงถอนการติดตั้ง?",
 "chooseOne": "เลือกหนึ่งข้อ",
 "reasonNotEnough": "มันไม่ได้ปิดกั้นการเคลื่อนไหวหรือสื่อที่ฉันคาดหวัง",
 "reasonBlockedIncorrectly": "บล็อกหรือเปลี่ยนบางอย่างผิดพลาด",
 "reasonSiteCompatibility": "มันใช้ไม่ได้กับเว็บไซต์ที่ฉันต้องการ",
 "reasonConfiguration": "ตั้งค่ายากหรือสับสน",
 "reasonBugSlowdown": "ทำให้เกิดบั๊ก ช้า หรือปัญหาความเข้ากันได้",
 "reasonNoLongerNeeded": "ฉันไม่ต้องการใช้อีกแล้ว",
 "reasonPrivacyPermissions": "กังวลเรื่องความเป็นส่วนตัวหรือสิทธิ์",
 "reasonOther": "อื่น ๆ",
 "detailsLabel": "เกิดอะไรขึ้น หรือคุณคาดหวังอะไรแทน?",
 "detailsHelp": "ไม่บังคับ หนึ่งหรือสองประโยคก็พอ",
 "featureLabel": "ฟีเจอร์ใดที่จะทำให้คุณลองใช้อีกครั้ง?",
 "featureHelp": "ไม่บังคับ",
 "contactLabel": "ที่อยู่สำหรับตอบกลับ",
 "contactHelp": "ไม่บังคับ ใส่เฉพาะเมื่อคุณต้องการคำตอบ",
 "submit": "ส่งความคิดเห็น",
 "status": "ความคิดเห็นจะถูกประมวลผลโดย Formspree",
 "footerSource": "ซอร์ส"
 },
 "da": {
 "pageTitle": "MotionBlock Feedback",
 "metaDescription": "Valgfri afinstallationsfeedback til MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk s startside",
 "navLabel": "Hovednavigation",
 "navProjects": "Projekter",
 "navNow": "Nu",
 "navAbout": "Om",
 "navContact": "Kontakt",
 "headline": "Hjælp med at forbedre udvidelsen",
 "intro": "Hvis MotionBlock missede målet, er én kort note nok. Denne formular er valgfri og kræver ikke kontaktoplysninger.",
 "privacyNote": "Udvidelsen åbner denne side efter afinstallation kun med generelle parametre for kilde, version og browsersprog. Medtag ikke personlige oplysninger, medmindre du bevidst vil dele dem.",
 "reasonLabel": "Hvorfor afinstallerede du?",
 "chooseOne": "Vælg én",
 "reasonNotEnough": "Den blokerede ikke den bevægelse eller medier, jeg forventede",
 "reasonBlockedIncorrectly": "Den blokerede eller ændrede noget forkert",
 "reasonSiteCompatibility": "Det virkede ikke på en hjemmeside, jeg havde brug for",
 "reasonConfiguration": "Den var forvirrende at konfigurere",
 "reasonBugSlowdown": "Den forårsagede en fejl, forsinkelse eller kompatibilitetsproblem",
 "reasonNoLongerNeeded": "Jeg har ikke længere brug for den",
 "reasonPrivacyPermissions": "Bekymring om privatliv eller tilladelser",
 "reasonOther": "Andet",
 "detailsLabel": "Hvad skete der, eller hvad forventede du i stedet?",
 "detailsHelp": "Valgfrit. En eller to sætninger er nok.",
 "featureLabel": "Hvilken funktion ville få dig til at prøve den igen?",
 "featureHelp": "Valgfrit.",
 "contactLabel": "Svaradresse",
 "contactHelp": "Valgfrit. Angiv den kun, hvis du ønsker et svar.",
 "submit": "Send feedback",
 "status": "Feedback behandles af Formspree.",
 "footerSource": "Kilde"
 },
 "fi": {
 "pageTitle": "MotionBlock Palaute",
 "metaDescription": "Valinnainen poistopalaute MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk in etusivu",
 "navLabel": "Päänavigaatio",
 "navProjects": "Projektit",
 "navNow": "Nyt",
 "navAbout": "Tietoa",
 "navContact": "Yhteys",
 "headline": "Auta parantamaan laajennusta",
 "intro": "Jos MotionBlock epäonnistui, yksi lyhyt nuotti riittää. Tämä lomake on vapaaehtoinen eikä vaadi yhteystietoja.",
 "privacyNote": "Laajennus avaa tämän sivun poistamisen jälkeen vain yleisillä lähde-, versio- ja selaimen kieliparametreilla. Älä lisää henkilötietoja, ellet tarkoituksella halua jakaa niitä.",
 "reasonLabel": "Miksi poistit sen?",
 "chooseOne": "Valitse yksi",
 "reasonNotEnough": "Se ei estänyt odotettua liikettä tai mediaa",
 "reasonBlockedIncorrectly": "Se esti tai muutti jotain virheellisesti",
 "reasonSiteCompatibility": "Se ei toiminut tarvitsemani verkkosivuston kanssa",
 "reasonConfiguration": "Sen määrittäminen oli sekavaa",
 "reasonBugSlowdown": "Se aiheutti virheen, hidastumisen tai yhteensopivuusongelman",
 "reasonNoLongerNeeded": "En tarvitse sitä enää",
 "reasonPrivacyPermissions": "Yksityisyys- tai käyttöoikeushuoli",
 "reasonOther": "Muu",
 "detailsLabel": "Mitä tapahtui tai mitä odotit sen sijaan?",
 "detailsHelp": "Valinnainen. Yksi tai kaksi lausetta riittää.",
 "featureLabel": "Mikä ominaisuus saisi sinut kokeilemaan sitä uudelleen?",
 "featureHelp": "Valinnainen.",
 "contactLabel": "Vastausosoite",
 "contactHelp": "Valinnainen. Lisää vain, jos haluat vastauksen.",
 "submit": "Lähetä palaute",
 "status": "Palaute käsitellään Formspree n kautta.",
 "footerSource": "Lähde"
 },
 "ta": {
 "pageTitle": "MotionBlock பின்னூட்டம்",
 "metaDescription": "MotionBlock க்கான விருப்ப கருத்து நிறுவல் நீக்கம்.",
 "brandHomeLabel": "Oleksandr Molodchyk முகப்பு",
 "navLabel": "முதன்மை வழிசெலுத்தல்",
 "navProjects": "திட்டங்கள்",
 "navNow": "இப்போது",
 "navAbout": "பற்றி",
 "navContact": "தொடர்பு",
 "headline": "நீட்டிப்பை மேம்படுத்த உதவுங்கள்",
 "intro": "MotionBlock குறியைத் தவறவிட்டால், ஒரு சிறிய குறிப்பு போதுமானது. இந்தப் படிவம் விருப்பத்தேர்வுக்குரியது மற்றும் தொடர்புத் தகவல் தேவையில்லை.",
 "privacyNote": "நீட்டிப்பு அகற்றப்பட்ட பிறகு, இந்தப் பக்கம் source, version மற்றும் browser-language போன்ற பொதுவான அளவுருக்களுடன் மட்டும் திறக்கப்படுகிறது. நீங்கள் திட்டமிட்டு பகிர விரும்பினால் தவிர தனிப்பட்ட தரவை சேர்க்க வேண்டாம்.",
 "reasonLabel": "ஏன் அகற்றினீர்கள்?",
 "chooseOne": "ஒன்றைத் தேர்ந்தெடுக்கவும்",
 "reasonNotEnough": "இது நான் எதிர்பார்த்த இயக்கம் அல்லது ஊடகத்தைத் தடுக்கவில்லை",
 "reasonBlockedIncorrectly": "ஏதாவது ஒன்றை தவறாக தடுத்தது அல்லது மாற்றியது",
 "reasonSiteCompatibility": "எனக்குத் தேவையான இணையதளத்தில் இது வேலை செய்யவில்லை",
 "reasonConfiguration": "அமைப்பது குழப்பமாக இருந்தது",
 "reasonBugSlowdown": "பிழை, மந்தம் அல்லது பொருந்துதல் சிக்கலை ஏற்படுத்தியது",
 "reasonNoLongerNeeded": "இனி எனக்கு இது தேவையில்லை",
 "reasonPrivacyPermissions": "தனியுரிமை அல்லது அனுமதி குறித்த கவலை",
 "reasonOther": "மற்றவை",
 "detailsLabel": "என்ன நடந்தது அல்லது அதற்கு பதிலாக என்ன எதிர்பார்த்தீர்கள்?",
 "detailsHelp": "விருப்பமானது. ஒரு அல்லது இரண்டு வாக்கியங்கள் போதும்.",
 "featureLabel": "எந்த அம்சம் இருந்தால் மீண்டும் முயற்சிப்பீர்கள்?",
 "featureHelp": "விருப்பமானது.",
 "contactLabel": "பதில் முகவரி",
 "contactHelp": "விருப்பமானது. பதில் வேண்டுமெனில் மட்டும் சேர்க்கவும்.",
 "submit": "கருத்தை அனுப்பு",
 "status": "கருத்து Formspree மூலம் செயலாக்கப்படுகிறது.",
 "footerSource": "மூலம்"
 },
 "nl": {
 "pageTitle": "MotionBlock Feedback",
 "metaDescription": "Optionele feedback om het verwijderen van de installatie voor MotionBlock.",
 "brandHomeLabel": "Startpagina van Oleksandr Molodchyk",
 "navLabel": "Hoofdnavigatie",
 "navProjects": "Projecten",
 "navNow": "Nu",
 "navAbout": "Over",
 "navContact": "Contact",
 "headline": "Help de extensie verbeteren",
 "intro": "Als MotionBlock de plank mist, is één korte noot genoeg. Dit formulier is optioneel en vereist geen contactgegevens.",
 "privacyNote": "De extensie opent deze pagina na verwijdering alleen met algemene parameters voor bron, versie en browsertaal. Vul geen persoonlijke gegevens in tenzij je die bewust wilt delen.",
 "reasonLabel": "Waarom heb je de extensie verwijderd?",
 "chooseOne": "Kies een optie",
 "reasonNotEnough": "Het blokkeerde niet de motie of media die ik verwachtte",
 "reasonBlockedIncorrectly": "Er werd iets onterecht geblokkeerd of gewijzigd",
 "reasonSiteCompatibility": "Het werkte niet op een website die ik nodig had",
 "reasonConfiguration": "Het was verwarrend om in te stellen",
 "reasonBugSlowdown": "Het veroorzaakte een fout, vertraging of compatibiliteitsprobleem",
 "reasonNoLongerNeeded": "Ik heb het niet meer nodig",
 "reasonPrivacyPermissions": "Zorgen over privacy of machtigingen",
 "reasonOther": "Anders",
 "detailsLabel": "Wat gebeurde er of wat verwachtte je?",
 "detailsHelp": "Optioneel. Een of twee zinnen is genoeg.",
 "featureLabel": "Welke functie zou je opnieuw laten proberen?",
 "featureHelp": "Optioneel.",
 "contactLabel": "Antwoordadres",
 "contactHelp": "Optioneel. Alleen invullen als je een antwoord wilt.",
 "submit": "Feedback verzenden",
 "status": "Feedback wordt verwerkt door Formspree.",
 "footerSource": "Bron"
 },
 "pt_PT": {
 "pageTitle": "MotionBlock Feedback",
 "metaDescription": "Feedback opcional de desinstalação para MotionBlock.",
 "brandHomeLabel": "Página inicial de Oleksandr Molodchyk",
 "navLabel": "Navegação principal",
 "navProjects": "Projetos",
 "navNow": "Agora",
 "navAbout": "Sobre",
 "navContact": "Contacto",
 "headline": "Ajude a melhorar a extensão",
 "intro": "Se MotionBlock falhar, uma nota curta é suficiente. Este formulário é opcional e não requer informações de contacto.",
 "privacyNote": "A extensão abre esta página após a desinstalação apenas com parâmetros genéricos de origem, versão e idioma do navegador. Não inclua dados pessoais, a menos que os queira partilhar intencionalmente.",
 "reasonLabel": "Porque desinstalou?",
 "chooseOne": "Escolha uma opção",
 "reasonNotEnough": "Não bloqueou o movimento nem os meios que eu esperava",
 "reasonBlockedIncorrectly": "Bloqueou ou alterou algo incorretamente",
 "reasonSiteCompatibility": "Não funcionou num site de que eu precisava",
 "reasonConfiguration": "Era confuso de configurar",
 "reasonBugSlowdown": "Causou um erro, lentidão ou problema de compatibilidade",
 "reasonNoLongerNeeded": "Já não preciso",
 "reasonPrivacyPermissions": "Preocupação com privacidade ou permissões",
 "reasonOther": "Outro",
 "detailsLabel": "O que aconteceu ou o que esperava?",
 "detailsHelp": "Opcional. Uma ou duas frases chegam.",
 "featureLabel": "Que funcionalidade o faria experimentar de novo?",
 "featureHelp": "Opcional.",
 "contactLabel": "Endereço para resposta",
 "contactHelp": "Opcional. Inclua apenas se quiser uma resposta.",
 "submit": "Enviar feedback",
 "status": "O feedback é processado pelo Formspree.",
 "footerSource": "Código-fonte"
 },
 "si": {
 "pageTitle": "MotionBlock ප් රතිපෝෂණය",
 "metaDescription": "MotionBlock සඳහා විකල්ප ප්රතිපෝෂණය අස්ථාපනය කරන්න.",
 "brandHomeLabel": "Oleksandr Molodchyk මුල් පිටුව",
 "navLabel": "ප්‍රධාන සංචාලනය",
 "navProjects": "ව්‍යාපෘති",
 "navNow": "දැන්",
 "navAbout": "පිළිබඳ",
 "navContact": "සම්බන්ධ වන්න",
 "headline": "දිගුව වැඩිදියුණු කිරීමට උදව් කරන්න",
 "intro": "MotionBlock ලකුණ මග හැරී ඇත්නම්, එක් කෙටි සටහනක් ප් රමාණවත්ය. මෙම පෝරමය විකල්ප වන අතර සම්බන්ධතා තොරතුරු අවශ්ය නොවේ.",
 "privacyNote": "දිගුව අස්ථාපනය කළ පසු මෙම පිටුව විවෘත කරන්නේ source, version සහ browser-language යන සාමාන්‍ය පරාමිතීන් පමණක් සමඟය. ඔබ අදහස් කරමින් බෙදාගැනීමට කැමති නැත්නම් පුද්ගලික දත්ත ඇතුළත් නොකරන්න.",
 "reasonLabel": "ඔබ එය අස්ථාපනය කළේ ඇයි?",
 "chooseOne": "එකක් තෝරන්න",
 "reasonNotEnough": "එය මා අපේක්ෂා කළ යෝජනාව හෝ මාධ් ය අවහිර කළේ නැත",
 "reasonBlockedIncorrectly": "යමක් වැරදි ලෙස අවහිර කළේ හෝ වෙනස් කළේය",
 "reasonSiteCompatibility": "මට අවශ් ය වෙබ් අඩවියක එය වැඩ කළේ නැත",
 "reasonConfiguration": "වින්‍යාස කිරීම අවුල් සහගත විය",
 "reasonBugSlowdown": "දෝෂයක්, මන්දගාමී වීමක් හෝ අනුකූලතා ගැටලුවක් ඇති කළේය",
 "reasonNoLongerNeeded": "මට එය තවදුරටත් අවශ්‍ය නැත",
 "reasonPrivacyPermissions": "පෞද්ගලිකත්වය හෝ අවසර පිළිබඳ සැලකිල්ල",
 "reasonOther": "වෙනත්",
 "detailsLabel": "කුමක් සිදු වුණාද, නැතහොත් ඒ වෙනුවට ඔබ බලාපොරොත්තු වූයේ කුමක්ද?",
 "detailsHelp": "විකල්ප. වාක්‍යයක් දෙකක් ප්‍රමාණවත්ය.",
 "featureLabel": "කුමන විශේෂාංගයක් තිබුණා නම් ඔබ නැවත උත්සාහ කරයිද?",
 "featureHelp": "විකල්ප.",
 "contactLabel": "පිළිතුරු ලිපිනය",
 "contactHelp": "විකල්ප. පිළිතුරක් අවශ්‍ය නම් පමණක් ඇතුළත් කරන්න.",
 "submit": "ප්‍රතිචාර යවන්න",
 "status": "ප්‍රතිචාර Formspree මඟින් සකසනු ලැබේ.",
 "footerSource": "මූලාශ්‍රය"
 }
};
