export const LOCALE_COPY_GROUP_1 = {
 "de": {
 "pageTitle": "MotionBlock Rückmeldung",
 "metaDescription": "Optionales Deinstallationsfeedback für MotionBlock.",
 "brandHomeLabel": "Startseite von Oleksandr Molodchyk",
 "navLabel": "Hauptnavigation",
 "navProjects": "Projekte",
 "navNow": "Jetzt",
 "navAbout": "Über mich",
 "navContact": "Kontakt",
 "headline": "Hilf mit, die Erweiterung zu verbessern",
 "intro": "Wenn MotionBlock das Ziel verfehlt hat, reicht eine kurze Notiz. Dieses Formular ist optional und erfordert keine Kontaktinformationen.",
 "privacyNote": "Die Erweiterung öffnet diese Seite nach der Deinstallation nur mit allgemeinen Parametern für Quelle, Version und Browsersprache. Gib keine personenbezogenen Daten an, außer du möchtest sie bewusst teilen.",
 "reasonLabel": "Warum hast du deinstalliert?",
 "chooseOne": "Bitte auswählen",
 "reasonNotEnough": "Es blockierte weder die Bewegung noch die Medien, die ich erwartet hatte.",
 "reasonBlockedIncorrectly": "Es wurde etwas fälschlicherweise blockiert oder verändert",
 "reasonSiteCompatibility": "Es funktionierte nicht auf einer Website, die ich brauchte,",
 "reasonConfiguration": "Die Konfiguration war verwirrend",
 "reasonBugSlowdown": "Es gab einen Fehler, eine Verlangsamung oder ein Kompatibilitätsproblem",
 "reasonNoLongerNeeded": "Ich brauche es nicht mehr",
 "reasonPrivacyPermissions": "Datenschutz- oder Berechtigungsbedenken",
 "reasonOther": "Sonstiges",
 "detailsLabel": "Was ist passiert oder was hast du stattdessen erwartet?",
 "detailsHelp": "Optional. Ein oder zwei Sätze reichen.",
 "featureLabel": "Welche Funktion würde dich dazu bringen, es erneut zu versuchen?",
 "featureHelp": "Optional.",
 "contactLabel": "Antwortadresse",
 "contactHelp": "Optional. Nur angeben, wenn du eine Antwort möchtest.",
 "submit": "Feedback senden",
 "status": "Feedback wird über Formspree verarbeitet.",
 "footerSource": "Quellcode"
 },
 "lt": {
 "pageTitle": "MotionBlock Atsiliepimai",
 "metaDescription": "Pasirenkamas MotionBlock pašalinimo atsiliepimas.",
 "brandHomeLabel": "Oleksandr Molodchyk pradžia",
 "navLabel": "Pagrindinė navigacija",
 "navProjects": "Projektai",
 "navNow": "Dabar",
 "navAbout": "Apie",
 "navContact": "Kontaktai",
 "headline": "Padėkite patobulinti plėtinį",
 "intro": "Jei MotionBlock praleido ženklą, pakanka vienos trumpos natos. Ši forma yra neprivaloma ir nereikalauja kontaktinės informacijos.",
 "privacyNote": "Pašalinus plėtinį, šis puslapis atidaromas tik su bendrais šaltinio, versijos ir naršyklės kalbos parametrais. Neįtraukite asmens duomenų, nebent sąmoningai norite jais pasidalyti.",
 "reasonLabel": "Kodėl pašalinote?",
 "chooseOne": "Pasirinkite vieną",
 "reasonNotEnough": "Jis neužblokavo judesio ar žiniasklaidos aš tikėjausi",
 "reasonBlockedIncorrectly": "Jis ką nors neteisingai užblokavo arba pakeitė",
 "reasonSiteCompatibility": "Jis neveikė svetainėje man reikia",
 "reasonConfiguration": "Jį buvo painu konfigūruoti",
 "reasonBugSlowdown": "Jis sukėlė klaidą, sulėtėjimą ar suderinamumo problemą",
 "reasonNoLongerNeeded": "Man jo nebereikia",
 "reasonPrivacyPermissions": "Privatumo arba leidimų susirūpinimas",
 "reasonOther": "Kita",
 "detailsLabel": "Kas nutiko arba ko tikėjotės vietoj to?",
 "detailsHelp": "Neprivaloma. Pakanka vieno ar dviejų sakinių.",
 "featureLabel": "Kokia funkcija paskatintų išbandyti dar kartą?",
 "featureHelp": "Neprivaloma.",
 "contactLabel": "Atsakymo adresas",
 "contactHelp": "Neprivaloma. Įrašykite tik jei norite atsakymo.",
 "submit": "Siųsti atsiliepimą",
 "status": "Atsiliepimą apdoroja Formspree.",
 "footerSource": "Šaltinis"
 },
 "uk": {
 "pageTitle": "MotionBlock Відгуки",
 "metaDescription": "Необов'язковий зворотний зв'язок щодо видалення для MotionBlock.",
 "brandHomeLabel": "Головна сторінка Oleksandr Molodchyk",
 "navLabel": "Основна навігація",
 "navProjects": "Проєкти",
 "navNow": "Зараз",
 "navAbout": "Про мене",
 "navContact": "Контакт",
 "headline": "Допоможіть покращити розширення",
 "intro": "Якщо MotionBlock промахнувся, достатньо однієї короткої ноти. Ця форма є необов'язковою і не потребує контактної інформації.",
 "privacyNote": "Розширення відкриває цю сторінку після видалення лише із загальними параметрами джерела, версії та мови браузера. Не вказуйте персональні дані, якщо не хочете свідомо ними поділитися.",
 "reasonLabel": "Чому ви видалили розширення?",
 "chooseOne": "Оберіть варіант",
 "reasonNotEnough": "Вона не заблокувала рухи чи медіа, яких я очікував.",
 "reasonBlockedIncorrectly": "Воно помилково блокувало або змінювало щось",
 "reasonSiteCompatibility": "Це не спрацювало на потрібному мені сайті",
 "reasonConfiguration": "Налаштування було незрозумілим",
 "reasonBugSlowdown": "Воно спричиняло помилку, уповільнення або проблему сумісності",
 "reasonNoLongerNeeded": "Воно мені більше не потрібне",
 "reasonPrivacyPermissions": "Питання приватності або дозволів",
 "reasonOther": "Інше",
 "detailsLabel": "Що сталося або чого ви очікували?",
 "detailsHelp": "Необов'язково. Достатньо одного-двох речень.",
 "featureLabel": "Яка функція змусила б вас спробувати знову?",
 "featureHelp": "Необов'язково.",
 "contactLabel": "Адреса для відповіді",
 "contactHelp": "Необов'язково. Додайте лише якщо хочете отримати відповідь.",
 "submit": "Надіслати відгук",
 "status": "Відгук обробляється через Formspree.",
 "footerSource": "Джерело"
 },
 "zh_CN": {
 "pageTitle": "MotionBlock 反馈",
 "metaDescription": "可选卸载反馈以供 MotionBlock。",
 "brandHomeLabel": "Oleksandr Molodchyk 主页",
 "navLabel": "主导航",
 "navProjects": "项目",
 "navNow": "近况",
 "navAbout": "关于",
 "navContact": "联系",
 "headline": "帮助改进这个扩展",
 "intro": "如果 MotionBlock 没达到目标，一个短音符就足够了。此表格为可选，无需提供联系方式。",
 "privacyNote": "扩展会在卸载后打开此页面，只带有来源、版本和浏览器语言等通用参数。除非你有意分享，请不要填写个人数据。",
 "reasonLabel": "你为什么卸载？",
 "chooseOne": "选择一项",
 "reasonNotEnough": "它没有阻挡我预期的动作或媒体",
 "reasonBlockedIncorrectly": "错误地屏蔽或更改了某些内容",
 "reasonSiteCompatibility": "它在我需要的网站上无法使用",
 "reasonConfiguration": "配置起来令人困惑",
 "reasonBugSlowdown": "导致错误、变慢或兼容性问题",
 "reasonNoLongerNeeded": "我不再需要它",
 "reasonPrivacyPermissions": "隐私或权限方面的担忧",
 "reasonOther": "其他",
 "detailsLabel": "发生了什么，或者你原本期待什么？",
 "detailsHelp": "可选。一两句话就够了。",
 "featureLabel": "什么功能会让你愿意再试一次？",
 "featureHelp": "可选。",
 "contactLabel": "回复地址",
 "contactHelp": "可选。只有在你想收到回复时才填写。",
 "submit": "发送反馈",
 "status": "反馈由 Formspree 处理。",
 "footerSource": "源代码"
 },
 "eu": {
 "pageTitle": "MotionBlock Iritzia",
 "metaDescription": "Aukerazko desinstalazio iritzia MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk-en hasiera",
 "navLabel": "Nabigazio nagusia",
 "navProjects": "Proiektuak",
 "navNow": "Orain",
 "navAbout": "Honi buruz",
 "navContact": "Kontaktua",
 "headline": "Lagundu luzapena hobetzen",
 "intro": "MotionBlock huts egin baduzu, ohar labur bat nahikoa da. Inprimaki hau aukerakoa da eta ez du kontaktu-informaziorik behar.",
 "privacyNote": "Luzapenak orri hau desinstalatu ondoren irekitzen du, iturburuaren, bertsioaren eta nabigatzaile-hizkuntzaren parametro orokorrekin bakarrik. Ez sartu datu pertsonalik, berariaz partekatu nahi ez badituzu.",
 "reasonLabel": "Zergatik desinstalatu duzu?",
 "chooseOne": "Aukeratu bat",
 "reasonNotEnough": "Ez zuen espero nuen mugimendua edo medioa blokeatu",
 "reasonBlockedIncorrectly": "Zerbait gaizki blokeatu edo aldatu zuen",
 "reasonSiteCompatibility": "Ez zuen funtzionatu behar nuen webgune batean",
 "reasonConfiguration": "Konfiguratzea nahasgarria zen",
 "reasonBugSlowdown": "Errore bat, moteltzea edo bateragarritasun-arazo bat eragin zuen",
 "reasonNoLongerNeeded": "Ez dut gehiago behar",
 "reasonPrivacyPermissions": "Pribatutasun edo baimenen kezka",
 "reasonOther": "Beste bat",
 "detailsLabel": "Zer gertatu zen edo zer espero zenuen horren ordez?",
 "detailsHelp": "Aukerakoa. Esaldi bat edo bi nahikoa dira.",
 "featureLabel": "Zein funtziok bultzatuko zintuzke berriro probatzera?",
 "featureHelp": "Aukerakoa.",
 "contactLabel": "Erantzuteko helbidea",
 "contactHelp": "Aukerakoa. Jarri soilik erantzuna nahi baduzu.",
 "submit": "Bidali iritzia",
 "status": "Iritzia Formspree-k prozesatzen du.",
 "footerSource": "Iturburua"
 },
 "el": {
 "pageTitle": "MotionBlock Ανατροφοδότηση",
 "metaDescription": "Προαιρετικά σχόλια απεγκατάστασης για MotionBlock.",
 "brandHomeLabel": "Αρχική σελίδα Oleksandr Molodchyk",
 "navLabel": "Κύρια πλοήγηση",
 "navProjects": "Έργα",
 "navNow": "Τώρα",
 "navAbout": "Σχετικά",
 "navContact": "Επικοινωνία",
 "headline": "Βοηθήστε να βελτιωθεί η επέκταση",
 "intro": "Αν MotionBlock χάσει το σημάδι, μια σύντομη σημείωση είναι αρκετή. Αυτή η φόρμα είναι προαιρετική και δεν απαιτεί στοιχεία επικοινωνίας.",
 "privacyNote": "Η επέκταση ανοίγει αυτή τη σελίδα μετά την απεγκατάσταση μόνο με γενικές παραμέτρους πηγής, έκδοσης και γλώσσας προγράμματος περιήγησης. Μην συμπεριλάβετε προσωπικά δεδομένα εκτός αν θέλετε σκόπιμα να τα μοιραστείτε.",
 "reasonLabel": "Γιατί κάνατε απεγκατάσταση;",
 "chooseOne": "Επιλέξτε ένα",
 "reasonNotEnough": "Δεν εμπόδισε την κίνηση ή τα μέσα που περίμενα",
 "reasonBlockedIncorrectly": "Απέκλεισε ή άλλαξε κάτι λανθασμένα",
 "reasonSiteCompatibility": "Δεν λειτούργησε σε έναν ιστότοπο που χρειαζόμουν",
 "reasonConfiguration": "Ήταν μπερδεμένο στη ρύθμιση",
 "reasonBugSlowdown": "Προκάλεσε σφάλμα, καθυστέρηση ή πρόβλημα συμβατότητας",
 "reasonNoLongerNeeded": "Δεν το χρειάζομαι πλέον",
 "reasonPrivacyPermissions": "Ανησυχία για ιδιωτικότητα ή δικαιώματα",
 "reasonOther": "Άλλο",
 "detailsLabel": "Τι συνέβη ή τι περιμένατε αντί γι’ αυτό;",
 "detailsHelp": "Προαιρετικό. Μία ή δύο προτάσεις αρκούν.",
 "featureLabel": "Ποια λειτουργία θα σας έκανε να το δοκιμάσετε ξανά;",
 "featureHelp": "Προαιρετικό.",
 "contactLabel": "Διεύθυνση απάντησης",
 "contactHelp": "Προαιρετικό. Συμπληρώστε το μόνο αν θέλετε απάντηση.",
 "submit": "Αποστολή σχολίων",
 "status": "Τα σχόλια επεξεργάζονται από το Formspree.",
 "footerSource": "Πηγή"
 },
 "ml": {
 "pageTitle": "MotionBlock ഫീഡ്ബാക്ക്",
 "metaDescription": "MotionBlock-നായി ഓപ്ഷണൽ ഫീഡ് ബാക്ക് അൺഇൻസ്റ്റാൾ ചെയ്യുക.",
 "brandHomeLabel": "Oleksandr Molodchyk ഹോം",
 "navLabel": "പ്രധാന നാവിഗേഷൻ",
 "navProjects": "പ്രോജക്റ്റുകൾ",
 "navNow": "ഇപ്പോൾ",
 "navAbout": "കുറിച്ച്",
 "navContact": "ബന്ധപ്പെടുക",
 "headline": "എക്സ്റ്റൻഷൻ മെച്ചപ്പെടുത്താൻ സഹായിക്കുക",
 "intro": "MotionBlock മാർക്ക് നഷ്ടപ്പെടുത്തിയാൽ, ഒരു ഹ്രസ്വ കുറിപ്പ് മതി. ഈ ഫോം നിർബന്ധമല്ല, സമ്പർക്ക വിവരങ്ങൾ ആവശ്യമില്ല.",
 "privacyNote": "എക്സ്റ്റൻഷൻ അൺഇൻസ്റ്റാൾ ചെയ്തതിന് ശേഷം ഈ പേജ് പൊതുവായ source, version, browser-language പരാമീറ്ററുകളോടെ മാത്രമാണ് തുറക്കുന്നത്. വ്യക്തിപരമായ ഡാറ്റ മനപ്പൂർവ്വം പങ്കിടാൻ ആഗ്രഹിക്കുന്നില്ലെങ്കിൽ ഉൾപ്പെടുത്തരുത്.",
 "reasonLabel": "എന്തുകൊണ്ടാണ് അൺഇൻസ്റ്റാൾ ചെയ്തത്?",
 "chooseOne": "ഒന്ന് തിരഞ്ഞെടുക്കുക",
 "reasonNotEnough": "ഞാൻ പ്രതീക്ഷിച്ച പ്രമേയത്തെയോ മാധ്യമങ്ങളെയോ ഇത് തടഞ്ഞില്ല",
 "reasonBlockedIncorrectly": "എന്തെങ്കിലും തെറ്റായി ബ്ലോക്ക് ചെയ്യുകയോ മാറ്റുകയോ ചെയ്തു",
 "reasonSiteCompatibility": "എനിക്ക് ആവശ്യമുള്ള ഒരു വെബ് സൈറ്റിൽ ഇത് പ്രവർത്തിച്ചില്ല",
 "reasonConfiguration": "കോൺഫിഗർ ചെയ്യുന്നത് ആശയക്കുഴപ്പമായിരുന്നു",
 "reasonBugSlowdown": "ബഗ്, മന്ദഗതി, അല്ലെങ്കിൽ അനുയോജ്യത പ്രശ്നം ഉണ്ടാക്കി",
 "reasonNoLongerNeeded": "ഇനി ആവശ്യമില്ല",
 "reasonPrivacyPermissions": "സ്വകാര്യതയോ അനുമതികളോ സംബന്ധിച്ച ആശങ്ക",
 "reasonOther": "മറ്റുള്ളവ",
 "detailsLabel": "എന്താണ് സംഭവിച്ചത്, അല്ലെങ്കിൽ പകരം എന്താണ് പ്രതീക്ഷിച്ചത്?",
 "detailsHelp": "ഐച്ഛികം. ഒരു രണ്ടുവാക്യം മതി.",
 "featureLabel": "ഏത് സവിശേഷതയാണെങ്കിൽ വീണ്ടും പരീക്ഷിക്കും?",
 "featureHelp": "ഐച്ഛികം.",
 "contactLabel": "മറുപടി വിലാസം",
 "contactHelp": "ഐച്ഛികം. മറുപടി വേണമെങ്കിൽ മാത്രം ചേർക്കുക.",
 "submit": "ഫീഡ്‌ബാക്ക് അയയ്ക്കുക",
 "status": "ഫീഡ്‌ബാക്ക് Formspree പ്രോസസ് ചെയ്യുന്നു.",
 "footerSource": "ഉറവിടം"
 }
};
