export const LOCALE_COPY_GROUP_3 = {
 "lv": {
 "pageTitle": "MotionBlock Atsauksmes",
 "metaDescription": "Neobligātas atinstalēšanas atsauksmes par MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk sākumlapa",
 "navLabel": "Galvenā navigācija",
 "navProjects": "Projekti",
 "navNow": "Tagad",
 "navAbout": "Par",
 "navContact": "Kontakti",
 "headline": "Palīdziet uzlabot paplašinājumu",
 "intro": "Ja MotionBlock nokavējis atzīmi, pietiek ar vienu īsu piezīmi. Šī veidlapa nav obligāta, un tai nav nepieciešama kontaktinformācija.",
 "privacyNote": "Pēc atinstalēšanas paplašinājums atver šo lapu tikai ar vispārīgiem avota, versijas un pārlūka valodas parametriem. Neiekļaujiet personas datus, ja vien apzināti nevēlaties tos kopīgot.",
 "reasonLabel": "Kāpēc atinstalējāt?",
 "chooseOne": "Izvēlieties vienu",
 "reasonNotEnough": "Tas nebloķēja kustību vai medijus, ko es gaidīju",
 "reasonBlockedIncorrectly": "Tas kaut ko bloķēja vai mainīja nepareizi",
 "reasonSiteCompatibility": "Tas nedarbojās man vajadzīgā vietnē",
 "reasonConfiguration": "To bija mulsinoši konfigurēt",
 "reasonBugSlowdown": "Tas izraisīja kļūdu, palēninājumu vai saderības problēmu",
 "reasonNoLongerNeeded": "Man tas vairs nav vajadzīgs",
 "reasonPrivacyPermissions": "Bažas par privātumu vai atļaujām",
 "reasonOther": "Cits",
 "detailsLabel": "Kas notika vai ko gaidījāt tā vietā?",
 "detailsHelp": "Neobligāti. Pietiek ar vienu vai diviem teikumiem.",
 "featureLabel": "Kāda funkcija liktu jums to izmēģināt vēlreiz?",
 "featureHelp": "Neobligāti.",
 "contactLabel": "Atbildes adrese",
 "contactHelp": "Neobligāti. Norādiet tikai tad, ja vēlaties atbildi.",
 "submit": "Sūtīt atsauksmi",
 "status": "Atsauksmi apstrādā Formspree.",
 "footerSource": "Avots"
 },
 "sr": {
 "pageTitle": "MotionBlock Повратне информације",
 "metaDescription": "Опционо деинсталирате повратне информације за MotionBlock.",
 "brandHomeLabel": "Почетна страница Oleksandr Molodchyk-а",
 "navLabel": "Главна навигација",
 "navProjects": "Пројекти",
 "navNow": "Сада",
 "navAbout": "О мени",
 "navContact": "Контакт",
 "headline": "Помозите да се проширење побољша",
 "intro": "Ако MotionBlock промашили циљ, довољна је једна кратка напомена. Овај образац је опциони и не захтева контакт информације.",
 "privacyNote": "Проширење после деинсталације отвара ову страницу само са општим параметрима извора, верзије и језика прегледача. Не уносите личне податке осим ако намерно желите да их поделите.",
 "reasonLabel": "Зашто сте деинсталирали?",
 "chooseOne": "Изаберите једно",
 "reasonNotEnough": "Није блокирао кретање или медије које сам очекивао",
 "reasonBlockedIncorrectly": "Нешто је погрешно блокирао или променио",
 "reasonSiteCompatibility": "Није успело на сајту који ми је био потребан",
 "reasonConfiguration": "Конфигурисање је било збуњујуће",
 "reasonBugSlowdown": "Изазвао је грешку, успоравање или проблем са компатибилношћу",
 "reasonNoLongerNeeded": "Више ми није потребан",
 "reasonPrivacyPermissions": "Забринутост за приватност или дозволе",
 "reasonOther": "Друго",
 "detailsLabel": "Шта се догодило или шта сте очекивали уместо тога?",
 "detailsHelp": "Опционо. Једна или две реченице су довољне.",
 "featureLabel": "Која функција би вас навела да га поново пробате?",
 "featureHelp": "Опционо.",
 "contactLabel": "Адреса за одговор",
 "contactHelp": "Опционо. Наведите само ако желите одговор.",
 "submit": "Пошаљи повратне информације",
 "status": "Повратне информације обрађује Formspree.",
 "footerSource": "Извор"
 },
 "am": {
 "pageTitle": "MotionBlock ግብረመልስ",
 "metaDescription": "አማራጭ ለ MotionBlock ግብረመልስ ማራገፍ።",
 "brandHomeLabel": "የ Oleksandr Molodchyk መነሻ ገጽ",
 "navLabel": "ዋና አሰሳ",
 "navProjects": "ፕሮጀክቶች",
 "navNow": "አሁን",
 "navAbout": "ስለ",
 "navContact": "እውቂያ",
 "headline": "ቅጥያውን ለማሻሻል ይርዱ",
 "intro": "MotionBlock ምልክቱን ካመለጠዎት አንድ አጭር ማስታወሻ በቂ ነው። ይህ ቅጽ አማራጭ ነው እና የእውቂያ መረጃ አያስፈልገውም.",
 "privacyNote": "ቅጥያው ከተወገደ በኋላ ይህን ገጽ የሚከፍተው የምንጭ፣ የስሪት እና የአሳሽ ቋንቋ አጠቃላይ መለኪያዎችን ብቻ በመጠቀም ነው። ሆን ብለው ማጋራት ካልፈለጉ የግል መረጃ አያስገቡ።",
 "reasonLabel": "ለምን አስወገዱት?",
 "chooseOne": "አንዱን ይምረጡ",
 "reasonNotEnough": "የጠበቅኩትን እንቅስቃሴ ወይም ሚዲያ አላገደም",
 "reasonBlockedIncorrectly": "አንድ ነገር በስህተት አገደ ወይም ቀየረ",
 "reasonSiteCompatibility": "በምፈልገው ድር ጣቢያ ላይ አልሰራም",
 "reasonConfiguration": "ማዋቀሩ ግራ የሚያጋባ ነበር",
 "reasonBugSlowdown": "ስህተት፣ መቀዝቀዝ ወይም የተኳኋኝነት ችግኝ ፈጠረ",
 "reasonNoLongerNeeded": "ከእንግዲህ አልፈልገውም",
 "reasonPrivacyPermissions": "የግላዊነት ወይም የፍቃድ ጭንቀት",
 "reasonOther": "ሌላ",
 "detailsLabel": "ምን ተፈጠረ ወይም በምትኩ ምን ጠበቁ?",
 "detailsHelp": "አማራጭ። አንድ ወይም ሁለት ዓረፍተ ነገር በቂ ነው።",
 "featureLabel": "እንደገና እንዲሞክሩት የሚያደርግ ምን ባህሪ ነው?",
 "featureHelp": "አማራጭ።",
 "contactLabel": "የመልስ አድራሻ",
 "contactHelp": "አማራጭ። መልስ ከፈለጉ ብቻ ያክሉት።",
 "submit": "አስተያየት ላክ",
 "status": "አስተያየት በ Formspree ይሰራል።",
 "footerSource": "ምንጭ"
 },
 "es": {
 "pageTitle": "MotionBlock Comentarios",
 "metaDescription": "Retroalimentación opcional de desinstalación para MotionBlock.",
 "brandHomeLabel": "Inicio de Oleksandr Molodchyk",
 "navLabel": "Navegación principal",
 "navProjects": "Proyectos",
 "navNow": "Ahora",
 "navAbout": "Acerca de",
 "navContact": "Contacto",
 "headline": "Ayuda a mejorar la extensión",
 "intro": "Si MotionBlock fallado, basta con una nota corta. Este formulario es opcional y no requiere información de contacto.",
 "privacyNote": "La extensión abre esta página después de desinstalarse solo con parámetros genéricos de origen, versión e idioma del navegador. No incluyas datos personales salvo que quieras compartirlos intencionalmente.",
 "reasonLabel": "¿Por qué la desinstalaste?",
 "chooseOne": "Elige una opción",
 "reasonNotEnough": "No bloqueó el movimiento ni el medio que esperaba",
 "reasonBlockedIncorrectly": "Bloqueó o cambió algo incorrectamente",
 "reasonSiteCompatibility": "No funcionó en una web que necesitaba",
 "reasonConfiguration": "Era confusa de configurar",
 "reasonBugSlowdown": "Causó un error, lentitud o problema de compatibilidad",
 "reasonNoLongerNeeded": "Ya no la necesito",
 "reasonPrivacyPermissions": "Preocupación por privacidad o permisos",
 "reasonOther": "Otro",
 "detailsLabel": "¿Qué pasó o qué esperabas en su lugar?",
 "detailsHelp": "Opcional. Una o dos frases son suficientes.",
 "featureLabel": "¿Qué función haría que la probaras de nuevo?",
 "featureHelp": "Opcional.",
 "contactLabel": "Dirección para responder",
 "contactHelp": "Opcional. Inclúyela solo si quieres una respuesta.",
 "submit": "Enviar comentarios",
 "status": "Los comentarios se procesan con Formspree.",
 "footerSource": "Código fuente"
 },
 "cs": {
 "pageTitle": "MotionBlock Zpětná vazba",
 "metaDescription": "Volitelná zpětná vazba k odinstalaci pro MotionBlock.",
 "brandHomeLabel": "Domovská stránka Oleksandra Molodchyka",
 "navLabel": "Hlavní navigace",
 "navProjects": "Projekty",
 "navNow": "Teď",
 "navAbout": "O mně",
 "navContact": "Kontakt",
 "headline": "Pomozte rozšíření zlepšit",
 "intro": "Pokud MotionBlock minul, stačí jedna krátká poznámka. Tento formulář je volitelný a nevyžaduje kontaktní údaje.",
 "privacyNote": "Rozšíření po odinstalování otevře tuto stránku pouze s obecnými parametry zdroje, verze a jazyka prohlížeče. Neuvádějte osobní údaje, pokud je nechcete záměrně sdílet.",
 "reasonLabel": "Proč jste rozšíření odinstalovali?",
 "chooseOne": "Vyberte jednu možnost",
 "reasonNotEnough": "Neblokoval jsem pohyb ani média, které jsem očekával",
 "reasonBlockedIncorrectly": "Něco blokovalo nebo měnilo nesprávně",
 "reasonSiteCompatibility": "Na webu, který jsem potřeboval, to nefungovalo",
 "reasonConfiguration": "Nastavení bylo matoucí",
 "reasonBugSlowdown": "Způsobovalo chybu, zpomalení nebo problém s kompatibilitou",
 "reasonNoLongerNeeded": "Už ho nepotřebuji",
 "reasonPrivacyPermissions": "Obava o soukromí nebo oprávnění",
 "reasonOther": "Jiné",
 "detailsLabel": "Co se stalo nebo co jste očekávali místo toho?",
 "detailsHelp": "Volitelné. Stačí jedna nebo dvě věty.",
 "featureLabel": "Jaká funkce by vás přiměla rozšíření zkusit znovu?",
 "featureHelp": "Volitelné.",
 "contactLabel": "Adresa pro odpověď",
 "contactHelp": "Volitelné. Uveďte ji jen tehdy, pokud chcete odpověď.",
 "submit": "Odeslat zpětnou vazbu",
 "status": "Zpětnou vazbu zpracovává Formspree.",
 "footerSource": "Zdroj"
 },
 "kn": {
 "pageTitle": "MotionBlock ಪ್ರತಿಕ್ರಿಯೆ",
 "metaDescription": "MotionBlock ಗಾಗಿ ಐಚ್ಛಿಕ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಅಸ್ಥಾಪಿಸಿ.",
 "brandHomeLabel": "Oleksandr Molodchyk ಮುಖಪುಟ",
 "navLabel": "ಮುಖ್ಯ ನ್ಯಾವಿಗೇಶನ್",
 "navProjects": "ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು",
 "navNow": "ಈಗ",
 "navAbout": "ಬಗ್ಗೆ",
 "navContact": "ಸಂಪರ್ಕ",
 "headline": "ವಿಸ್ತರಣೆಯನ್ನು ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡಿ",
 "intro": "MotionBlock ಗುರುತನ್ನು ತಪ್ಪಿಸಿಕೊಂಡರೆ, ಒಂದು ಸಣ್ಣ ಟಿಪ್ಪಣಿ ಸಾಕು. ಈ ನಮೂನೆಯು ಐಚ್ಛಿಕವಾಗಿದೆ ಮತ್ತು ಸಂಪರ್ಕ ಮಾಹಿತಿಯ ಅಗತ್ಯವಿಲ್ಲ.",
 "privacyNote": "ವಿಸ್ತರಣೆ ಅನ್‌ಇನ್‌ಸ್ಟಾಲ್ ಆದ ನಂತರ ಈ ಪುಟವನ್ನು ಮೂಲ, ಆವೃತ್ತಿ ಮತ್ತು ಬ್ರೌಸರ್ ಭಾಷೆಯ ಸಾಮಾನ್ಯ ಪರಾಮೀಟರ್‌ಗಳೊಂದಿಗೆ ಮಾತ್ರ ತೆರೆಯುತ್ತದೆ. ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಹಂಚಿಕೊಳ್ಳಲು ಬಯಸದೇ ಇದ್ದರೆ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಸೇರಿಸಬೇಡಿ.",
 "reasonLabel": "ನೀವು ಏಕೆ ಅನ್‌ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿದ್ದೀರಿ?",
 "chooseOne": "ಒಂದನ್ನು ಆಯ್ಕೆಮಾಡಿ",
 "reasonNotEnough": "ಇದು ನಾನು ನಿರೀಕ್ಷಿಸಿದ ಚಲನೆ ಅಥವಾ ಮಾಧ್ಯಮವನ್ನು ನಿರ್ಬಂಧಿಸಲಿಲ್ಲ",
 "reasonBlockedIncorrectly": "ಏನನ್ನಾದರೂ ತಪ್ಪಾಗಿ ತಡೆಗಟ್ಟಿತು ಅಥವಾ ಬದಲಾಯಿಸಿತು",
 "reasonSiteCompatibility": "ಇದು ನನಗೆ ಅಗತ್ಯವಿರುವ ವೆಬ್ ಸೈಟ್ ನಲ್ಲಿ ಕೆಲಸ ಮಾಡಲಿಲ್ಲ",
 "reasonConfiguration": "ಕಾನ್ಫಿಗರ್ ಮಾಡುವುದು ಗೊಂದಲಕರವಾಗಿತ್ತು",
 "reasonBugSlowdown": "ದೋಷ, ನಿಧಾನಗತಿ ಅಥವಾ ಹೊಂದಾಣಿಕೆ ಸಮಸ್ಯೆ ಉಂಟುಮಾಡಿತು",
 "reasonNoLongerNeeded": "ಇದು ಇನ್ನು ನನಗೆ ಬೇಕಿಲ್ಲ",
 "reasonPrivacyPermissions": "ಗೌಪ್ಯತೆ ಅಥವಾ ಅನುಮತಿ ಕುರಿತು ಕಳವಳ",
 "reasonOther": "ಇತರೆ",
 "detailsLabel": "ಏನು ಸಂಭವಿಸಿತು ಅಥವಾ ಬದಲು ನೀವು ಏನು ನಿರೀಕ್ಷಿಸಿದ್ದೀರಿ?",
 "detailsHelp": "ಐಚ್ಛಿಕ. ಒಂದು ಅಥವಾ ಎರಡು ವಾಕ್ಯ ಸಾಕು.",
 "featureLabel": "ಯಾವ ವೈಶಿಷ್ಟ್ಯ ಇದನ್ನು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಲು ನಿಮಗೆ ಪ್ರೇರಣೆ ನೀಡುತ್ತದೆ?",
 "featureHelp": "ಐಚ್ಛಿಕ.",
 "contactLabel": "ಉತ್ತರ ವಿಳಾಸ",
 "contactHelp": "ಐಚ್ಛಿಕ. ಉತ್ತರ ಬೇಕಿದ್ದರೆ ಮಾತ್ರ ಸೇರಿಸಿ.",
 "submit": "ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ",
 "status": "ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು Formspree ಸಂಸ್ಕರಿಸುತ್ತದೆ.",
 "footerSource": "ಮೂಲ"
 },
 "it": {
 "pageTitle": "MotionBlock Feedback",
 "metaDescription": "Feedback opzionale per la disinstallazione per MotionBlock.",
 "brandHomeLabel": "Home di Oleksandr Molodchyk",
 "navLabel": "Navigazione principale",
 "navProjects": "Progetti",
 "navNow": "Ora",
 "navAbout": "Informazioni",
 "navContact": "Contatto",
 "headline": "Aiuta a migliorare l'estensione",
 "intro": "Se MotionBlock mancato il bersaglio, basta una breve nota. Questo modulo è opzionale e non richiede informazioni di contatto.",
 "privacyNote": "L'estensione apre questa pagina dopo la disinstallazione solo con parametri generici di origine, versione e lingua del browser. Non inserire dati personali a meno che tu voglia condividerli intenzionalmente.",
 "reasonLabel": "Perché hai disinstallato?",
 "chooseOne": "Scegli un'opzione",
 "reasonNotEnough": "Non ha bloccato il movimento né il supporto che mi aspettavo",
 "reasonBlockedIncorrectly": "Bloccava o modificava qualcosa in modo errato",
 "reasonSiteCompatibility": "Non ha funzionato su un sito web di cui avevo bisogno",
 "reasonConfiguration": "Era confusa da configurare",
 "reasonBugSlowdown": "Causava bug, rallentamenti o problemi di compatibilità",
 "reasonNoLongerNeeded": "Non mi serve più",
 "reasonPrivacyPermissions": "Preoccupazione per privacy o autorizzazioni",
 "reasonOther": "Altro",
 "detailsLabel": "Che cosa è successo o che cosa ti aspettavi?",
 "detailsHelp": "Facoltativo. Bastano una o due frasi.",
 "featureLabel": "Quale funzione ti farebbe riprovare?",
 "featureHelp": "Facoltativo.",
 "contactLabel": "Indirizzo per la risposta",
 "contactHelp": "Facoltativo. Inseriscilo solo se vuoi una risposta.",
 "submit": "Invia feedback",
 "status": "Il feedback viene gestito da Formspree.",
 "footerSource": "Sorgente"
 }
};
