export const LOCALE_COPY_GROUP_5 = {
 "ru": {
 "pageTitle": "MotionBlock Отзывы",
 "metaDescription": "Опционально обратная связь по удалению для MotionBlock.",
 "brandHomeLabel": "Главная страница Oleksandr Molodchyk",
 "navLabel": "Основная навигация",
 "navProjects": "Проекты",
 "navNow": "Сейчас",
 "navAbout": "О проекте",
 "navContact": "Контакт",
 "headline": "Помогите улучшить расширение",
 "intro": "Если MotionBlock промахнулся, одной короткой ноты достаточно. Эта форма является необязательной и не требует контактной информации.",
 "privacyNote": "Расширение открывает эту страницу после удаления только с общими параметрами источника, версии и языка браузера. Не указывайте персональные данные, если не хотите намеренно ими поделиться.",
 "reasonLabel": "Почему вы удалили расширение?",
 "chooseOne": "Выберите вариант",
 "reasonNotEnough": "Это не заблокировало ожидаемое движение или медиа",
 "reasonBlockedIncorrectly": "Оно ошибочно блокировало или изменяло что-то",
 "reasonSiteCompatibility": "Это не сработало на нужном мне сайте",
 "reasonConfiguration": "Настройка была непонятной",
 "reasonBugSlowdown": "Оно вызывало ошибку, замедление или проблему совместимости",
 "reasonNoLongerNeeded": "Оно мне больше не нужно",
 "reasonPrivacyPermissions": "Вопросы приватности или разрешений",
 "reasonOther": "Другое",
 "detailsLabel": "Что произошло или чего вы ожидали?",
 "detailsHelp": "Необязательно. Достаточно одного-двух предложений.",
 "featureLabel": "Какая функция заставила бы вас попробовать снова?",
 "featureHelp": "Необязательно.",
 "contactLabel": "Адрес для ответа",
 "contactHelp": "Необязательно. Укажите только если хотите получить ответ.",
 "submit": "Отправить отзыв",
 "status": "Отзыв обрабатывается через Formspree.",
 "footerSource": "Источник"
 },
 "ka": {
 "pageTitle": "MotionBlock კავშირი",
 "metaDescription": "სურვილისამებრ წაშალეთ გამოხმაურება MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk-ის მთავარი გვერდი",
 "navLabel": "მთავარი ნავიგაცია",
 "navProjects": "პროექტები",
 "navNow": "ახლა",
 "navAbout": "შესახებ",
 "navContact": "კონტაქტი",
 "headline": "დაგვეხმარეთ გაფართოების გაუმჯობესებაში",
 "intro": "თუ MotionBlock გამოტოვეთ ნიშანი, ერთი მოკლე შენიშვნა საკმარისია. ეს ფორმა არჩევითია და არ საჭიროებს საკონტაქტო ინფორმაციას.",
 "privacyNote": "გაფართოება წაშლის შემდეგ ამ გვერდს ხსნის მხოლოდ წყაროს, ვერსიისა და ბრაუზერის ენის ზოგადი პარამეტრებით. პირადი მონაცემები არ შეიყვანოთ, თუ მათი განზრახ გაზიარება არ გსურთ.",
 "reasonLabel": "რატომ წაშალეთ?",
 "chooseOne": "აირჩიეთ ერთი",
 "reasonNotEnough": "მან არ დაბლოკა შუამდგომლობა ან მედია, რომელსაც ველოდი",
 "reasonBlockedIncorrectly": "რაღაცას არასწორად ბლოკავდა ან ცვლიდა",
 "reasonSiteCompatibility": "ეს არ მუშაობდა ვებსაიტზე, რომელიც მჭირდებოდა",
 "reasonConfiguration": "მისი კონფიგურაცია დამაბნეველი იყო",
 "reasonBugSlowdown": "იწვევდა შეცდომას, შენელებას ან თავსებადობის პრობლემას",
 "reasonNoLongerNeeded": "აღარ მჭირდება",
 "reasonPrivacyPermissions": "კონფიდენციალურობის ან ნებართვების შეშფოთება",
 "reasonOther": "სხვა",
 "detailsLabel": "რა მოხდა ან რას ელოდით ამის ნაცვლად?",
 "detailsHelp": "სურვილისამებრ. ერთი-ორი წინადადება საკმარისია.",
 "featureLabel": "რომელი ფუნქცია გაიძულებდათ ხელახლა გეცადათ?",
 "featureHelp": "სურვილისამებრ.",
 "contactLabel": "პასუხის მისამართი",
 "contactHelp": "სურვილისამებრ. მიუთითეთ მხოლოდ თუ პასუხი გსურთ.",
 "submit": "გამოხმაურების გაგზავნა",
 "status": "გამოხმაურებას ამუშავებს Formspree.",
 "footerSource": "წყარო"
 },
 "et": {
 "pageTitle": "MotionBlock Tagasiside",
 "metaDescription": "Valikuline desinstalli tagasiside MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk i avaleht",
 "navLabel": "Põhinavigeerimine",
 "navProjects": "Projektid",
 "navNow": "Praegu",
 "navAbout": "Teave",
 "navContact": "Kontakt",
 "headline": "Aita laiendust paremaks teha",
 "intro": "Kui MotionBlock eksis, piisab ühest lühikesest nootist. See vorm on vabatahtlik ega nõua kontaktandmeid.",
 "privacyNote": "Laiendus avab selle lehe pärast eemaldamist ainult üldiste allika, versiooni ja brauseri keele parameetritega. Ärge lisage isikuandmeid, välja arvatud juhul, kui soovite neid teadlikult jagada.",
 "reasonLabel": "Miks eemaldasite laienduse?",
 "chooseOne": "Valige üks",
 "reasonNotEnough": "See ei blokeerinud ootatud liikumist ega meediat",
 "reasonBlockedIncorrectly": "See blokeeris või muutis midagi valesti",
 "reasonSiteCompatibility": "See ei töötanud veebisaidil, mida mul vaja oli",
 "reasonConfiguration": "Seda oli segane seadistada",
 "reasonBugSlowdown": "See põhjustas vea, aeglustumise või ühilduvusprobleemi",
 "reasonNoLongerNeeded": "Ma ei vaja seda enam",
 "reasonPrivacyPermissions": "Privaatsuse või lubade mure",
 "reasonOther": "Muu",
 "detailsLabel": "Mis juhtus või mida ootasite selle asemel?",
 "detailsHelp": "Valikuline. Ühest või kahest lausest piisab.",
 "featureLabel": "Milline funktsioon paneks teid seda uuesti proovima?",
 "featureHelp": "Valikuline.",
 "contactLabel": "Vastuse aadress",
 "contactHelp": "Valikuline. Lisage ainult siis, kui soovite vastust.",
 "submit": "Saada tagasiside",
 "status": "Tagasisidet töötleb Formspree.",
 "footerSource": "Allikas"
 },
 "sv": {
 "pageTitle": "MotionBlock Feedback",
 "metaDescription": "Valfri avinstallationsfeedback för MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk s startsida",
 "navLabel": "Huvudnavigering",
 "navProjects": "Projekt",
 "navNow": "Nu",
 "navAbout": "Om",
 "navContact": "Kontakt",
 "headline": "Hjälp till att förbättra tillägget",
 "intro": "Om MotionBlock missade målet räcker en kort ton. Detta formulär är frivilligt och kräver ingen kontaktinformation.",
 "privacyNote": "Tillägget öppnar den här sidan efter avinstallation med endast generiska parametrar för källa, version och webbläsarspråk. Ange inga personuppgifter om du inte avsiktligt vill dela dem.",
 "reasonLabel": "Varför avinstallerade du?",
 "chooseOne": "Välj ett alternativ",
 "reasonNotEnough": "Den blockerade inte den rörelse eller media jag förväntade mig",
 "reasonBlockedIncorrectly": "Det blockerade eller ändrade något felaktigt",
 "reasonSiteCompatibility": "Det fungerade inte på en webbplats jag behövde",
 "reasonConfiguration": "Det var förvirrande att konfigurera",
 "reasonBugSlowdown": "Det orsakade en bugg, långsamhet eller kompatibilitetsproblem",
 "reasonNoLongerNeeded": "Jag behöver det inte längre",
 "reasonPrivacyPermissions": "Integritets- eller behörighetsfråga",
 "reasonOther": "Annat",
 "detailsLabel": "Vad hände eller vad förväntade du dig i stället?",
 "detailsHelp": "Frivilligt. En eller två meningar räcker.",
 "featureLabel": "Vilken funktion skulle få dig att prova igen?",
 "featureHelp": "Frivilligt.",
 "contactLabel": "Svarsadress",
 "contactHelp": "Frivilligt. Ange bara om du vill ha ett svar.",
 "submit": "Skicka feedback",
 "status": "Feedback behandlas av Formspree.",
 "footerSource": "Källa"
 },
 "te": {
 "pageTitle": "MotionBlock అభిప్రాయం",
 "metaDescription": "MotionBlock కోసం ఐచ్ఛిక అభిప్రాయాన్ని అన్ఇన్ స్టాల్ చేయండి.",
 "brandHomeLabel": "Oleksandr Molodchyk హోమ్",
 "navLabel": "ప్రధాన నావిగేషన్",
 "navProjects": "ప్రాజెక్టులు",
 "navNow": "ఇప్పుడు",
 "navAbout": "గురించి",
 "navContact": "సంప్రదింపు",
 "headline": "ఎక్స్‌టెన్షన్‌ను మెరుగుపరచడంలో సహాయపడండి",
 "intro": "MotionBlock మార్కును కోల్పోతే, ఒక చిన్న నోట్ సరిపోతుంది. ఈ పత్రం ఐచ్ఛికం మరియు దీనికి సంప్రదింపు సమాచారం అవసరం లేదు.",
 "privacyNote": "ఎక్స్‌టెన్షన్ అన్‌ఇన్‌స్టాల్ అయిన తర్వాత ఈ పేజీ source, version మరియు browser-language వంటి సాధారణ పరామితులతో మాత్రమే తెరుచుకుంటుంది. మీరు ఉద్దేశపూర్వకంగా పంచుకోవాలనుకుంటే తప్ప వ్యక్తిగత డేటాను చేర్చవద్దు.",
 "reasonLabel": "మీరు ఎందుకు అన్‌ఇన్‌స్టాల్ చేశారు?",
 "chooseOne": "ఒకదాన్ని ఎంచుకోండి",
 "reasonNotEnough": "ఇది నేను ఊహించిన కదలిక లేదా మీడియాను నిరోధించలేదు",
 "reasonBlockedIncorrectly": "ఏదో ఒకదాన్ని తప్పుగా బ్లాక్ చేసింది లేదా మార్చింది",
 "reasonSiteCompatibility": "నాకు అవసరమైన వెబ్ సైట్ పై ఇది పనిచేయలేదు",
 "reasonConfiguration": "కాన్ఫిగర్ చేయడం గందరగోళంగా ఉంది",
 "reasonBugSlowdown": "బగ్, మందగింపు లేదా అనుకూలత సమస్య కలిగించింది",
 "reasonNoLongerNeeded": "ఇక నాకు అవసరం లేదు",
 "reasonPrivacyPermissions": "గోప్యత లేదా అనుమతులపై ఆందోళన",
 "reasonOther": "ఇతర",
 "detailsLabel": "ఏం జరిగింది లేదా దాని బదులు మీరు ఏమి ఆశించారు?",
 "detailsHelp": "ఐచ్ఛికం. ఒకటి రెండు వాక్యాలు చాలు.",
 "featureLabel": "ఏ ఫీచర్ ఉంటే మీరు మళ్లీ ప్రయత్నిస్తారు?",
 "featureHelp": "ఐచ్ఛికం.",
 "contactLabel": "ప్రత్యుత్తర చిరునామా",
 "contactHelp": "ఐచ్ఛికం. సమాధానం కావాలంటే మాత్రమే చేర్చండి.",
 "submit": "అభిప్రాయం పంపండి",
 "status": "అభిప్రాయం Formspree ద్వారా ప్రాసెస్ చేయబడుతుంది.",
 "footerSource": "మూలం"
 },
 "vi": {
 "pageTitle": "MotionBlock Phản hồi",
 "metaDescription": "Phản hồi gỡ cài đặt tùy chọn cho MotionBlock.",
 "brandHomeLabel": "Trang chủ Oleksandr Molodchyk",
 "navLabel": "Điều hướng chính",
 "navProjects": "Dự án",
 "navNow": "Hiện tại",
 "navAbout": "Giới thiệu",
 "navContact": "Liên hệ",
 "headline": "Giúp cải thiện tiện ích",
 "intro": "Nếu MotionBlock bỏ lỡ mục tiêu, một nốt ngắn là đủ. Biểu mẫu này là tùy chọn và không yêu cầu thông tin liên hệ.",
 "privacyNote": "Tiện ích mở trang này sau khi gỡ cài đặt chỉ với các tham số chung về nguồn, phiên bản và ngôn ngữ trình duyệt. Đừng gửi dữ liệu cá nhân trừ khi bạn chủ động muốn chia sẻ.",
 "reasonLabel": "Vì sao bạn gỡ cài đặt?",
 "chooseOne": "Chọn một lý do",
 "reasonNotEnough": "Nó không chặn chuyển động hoặc phương tiện truyền thông mà tôi mong đợi",
 "reasonBlockedIncorrectly": "Chặn hoặc thay đổi nhầm thứ gì đó",
 "reasonSiteCompatibility": "Nó không hoạt động trên một trang web tôi cần",
 "reasonConfiguration": "Khó cấu hình",
 "reasonBugSlowdown": "Gây lỗi, chậm hoặc vấn đề tương thích",
 "reasonNoLongerNeeded": "Tôi không còn cần nữa",
 "reasonPrivacyPermissions": "Lo ngại về quyền riêng tư hoặc quyền truy cập",
 "reasonOther": "Khác",
 "detailsLabel": "Điều gì đã xảy ra hoặc bạn mong đợi điều gì?",
 "detailsHelp": "Tùy chọn. Một hoặc hai câu là đủ.",
 "featureLabel": "Tính năng nào sẽ khiến bạn thử lại?",
 "featureHelp": "Tùy chọn.",
 "contactLabel": "Địa chỉ nhận trả lời",
 "contactHelp": "Tùy chọn. Chỉ điền nếu bạn muốn nhận phản hồi.",
 "submit": "Gửi phản hồi",
 "status": "Phản hồi được xử lý bởi Formspree.",
 "footerSource": "Mã nguồn"
 },
 "mk": {
 "pageTitle": "MotionBlock Повратни информации",
 "metaDescription": "Опционална повратна информација за деинсталирање за MotionBlock.",
 "brandHomeLabel": "Почетна страница на Oleksandr Molodchyk",
 "navLabel": "Главна навигација",
 "navProjects": "Проекти",
 "navNow": "Сега",
 "navAbout": "За",
 "navContact": "Контакт",
 "headline": "Помогнете да се подобри проширувањето",
 "intro": "Ако MotionBlock промаши, една кратка нота е доволна. Овој формулар е опционален и не бара контакт информации.",
 "privacyNote": "Проширувањето ја отвора оваа страница по деинсталирање само со општи параметри за извор, верзија и јазик на прелистувачот. Не внесувајте лични податоци освен ако намерно сакате да ги споделите.",
 "reasonLabel": "Зошто го деинсталиравте?",
 "chooseOne": "Изберете едно",
 "reasonNotEnough": "Не го блокираше движењето или медиумите што ги очекував",
 "reasonBlockedIncorrectly": "Погрешно блокираше или промени нешто",
 "reasonSiteCompatibility": "Не функционираше на веб-страницата што ми требаше",
 "reasonConfiguration": "Беше збунувачко за конфигурирање",
 "reasonBugSlowdown": "Предизвика грешка, забавување или проблем со компатибилност",
 "reasonNoLongerNeeded": "Повеќе не ми треба",
 "reasonPrivacyPermissions": "Загриженост за приватност или дозволи",
 "reasonOther": "Друго",
 "detailsLabel": "Што се случи или што очекувавте наместо тоа?",
 "detailsHelp": "Изборно. Доволни се една или две реченици.",
 "featureLabel": "Која функција би ве натерала повторно да го пробате?",
 "featureHelp": "Изборно.",
 "contactLabel": "Адреса за одговор",
 "contactHelp": "Изборно. Внесете само ако сакате одговор.",
 "submit": "Испрати повратни информации",
 "status": "Повратните информации ги обработува Formspree.",
 "footerSource": "Извор"
 }
};
