export const LOCALE_COPY_GROUP_6 = {
 "hi": {
 "pageTitle": "MotionBlock प्रतिक्रिया",
 "metaDescription": "MotionBlock के लिए वैकल्पिक अनइंस्टॉल फीडबैक",
 "brandHomeLabel": "Oleksandr Molodchyk होम",
 "navLabel": "मुख्य नेविगेशन",
 "navProjects": "प्रोजेक्ट",
 "navNow": "अभी",
 "navAbout": "परिचय",
 "navContact": "संपर्क",
 "headline": "एक्सटेंशन को बेहतर बनाने में मदद करें",
 "intro": "यदि MotionBlock निशान से चूक गए हैं, तो एक छोटा नोट पर्याप्त है। यह प्रपत्र वैकल्पिक है और इसके लिए संपर्क जानकारी की आवश्यकता नहीं है.",
 "privacyNote": "एक्सटेंशन अनइंस्टॉल होने के बाद यह पेज केवल सामान्य source, version और browser-language पैरामीटर के साथ खोलता है। व्यक्तिगत डेटा शामिल न करें, जब तक आप जानबूझकर उसे साझा नहीं करना चाहते।",
 "reasonLabel": "आपने इसे क्यों हटाया?",
 "chooseOne": "एक विकल्प चुनें",
 "reasonNotEnough": "इसने उस गति या मीडिया को अवरुद्ध नहीं किया जिसकी मुझे उम्मीद थी",
 "reasonBlockedIncorrectly": "इसने कुछ गलत तरीके से ब्लॉक या बदल दिया",
 "reasonSiteCompatibility": "यह उस वेबसाइट पर काम नहीं करता था जिसकी मुझे आवश्यकता थी",
 "reasonConfiguration": "इसे कॉन्फ़िगर करना उलझनभरा था",
 "reasonBugSlowdown": "इससे बग, धीमापन या compatibility समस्या हुई",
 "reasonNoLongerNeeded": "अब मुझे इसकी जरूरत नहीं है",
 "reasonPrivacyPermissions": "गोपनीयता या permission की चिंता",
 "reasonOther": "अन्य",
 "detailsLabel": "क्या हुआ या आप क्या अपेक्षा कर रहे थे?",
 "detailsHelp": "वैकल्पिक। एक या दो वाक्य काफी हैं।",
 "featureLabel": "कौन-सा फीचर आपको इसे फिर आजमाने के लिए प्रेरित करेगा?",
 "featureHelp": "वैकल्पिक।",
 "contactLabel": "उत्तर के लिए पता",
 "contactHelp": "वैकल्पिक। केवल तभी जोड़ें जब आप उत्तर चाहते हैं।",
 "submit": "प्रतिक्रिया भेजें",
 "status": "प्रतिक्रिया Formspree द्वारा संसाधित की जाती है।",
 "footerSource": "स्रोत"
 },
 "fil": {
 "pageTitle": "MotionBlock Feedback",
 "metaDescription": "Opsyonal na feedback sa pag-uninstall para sa MotionBlock.",
 "brandHomeLabel": "Home ni Oleksandr Molodchyk",
 "navLabel": "Pangunahing nabigasyon",
 "navProjects": "Mga proyekto",
 "navNow": "Ngayon",
 "navAbout": "Tungkol",
 "navContact": "Contact",
 "headline": "Tumulong pagandahin ang extension",
 "intro": "Kung hindi MotionBlock nakuha ang marka, sapat na ang isang maikling tala. Ang form na ito ay opsyonal at hindi nangangailangan ng impormasyon sa pakikipag-ugnay.",
 "privacyNote": "Binubuksan ng extension ang pahinang ito pagkatapos i-uninstall gamit lang ang pangkalahatang source, version, at browser-language parameters. Huwag maglagay ng personal data maliban kung sinasadya mong ibahagi ito.",
 "reasonLabel": "Bakit mo ito in-uninstall?",
 "chooseOne": "Pumili ng isa",
 "reasonNotEnough": "Hindi nito hinarang ang paggalaw o media na inaasahan ko",
 "reasonBlockedIncorrectly": "May maling na-block o nabago",
 "reasonSiteCompatibility": "Hindi ito gumagana sa isang website na kailangan ko",
 "reasonConfiguration": "Nakakalito itong i-configure",
 "reasonBugSlowdown": "Nagdulot ito ng bug, pagbagal, o compatibility issue",
 "reasonNoLongerNeeded": "Hindi ko na ito kailangan",
 "reasonPrivacyPermissions": "Alalahanin sa privacy o permissions",
 "reasonOther": "Iba pa",
 "detailsLabel": "Ano ang nangyari o ano ang inaasahan mo?",
 "detailsHelp": "Opsyonal. Sapat na ang isa o dalawang pangungusap.",
 "featureLabel": "Anong feature ang magpapasubok sa iyo ulit?",
 "featureHelp": "Opsyonal.",
 "contactLabel": "Address para sa reply",
 "contactHelp": "Opsyonal. Ilagay lang ito kung gusto mo ng reply.",
 "submit": "Ipadala ang feedback",
 "status": "Pinoproseso ang feedback sa Formspree.",
 "footerSource": "Source"
 },
 "no": {
 "pageTitle": "MotionBlock Tilbakemelding",
 "metaDescription": "Valgfri avinstalleringstilbakemelding for MotionBlock.",
 "brandHomeLabel": "Oleksandr Molodchyk startside",
 "navLabel": "Hovednavigasjon",
 "navProjects": "Prosjekter",
 "navNow": "Nå",
 "navAbout": "Om",
 "navContact": "Kontakt",
 "headline": "Hjelp med å forbedre utvidelsen",
 "intro": "Hvis MotionBlock bommet, er én kort kommentar nok. Dette skjemaet er valgfritt og krever ikke kontaktinformasjon.",
 "privacyNote": "Utvidelsen åpner denne siden etter avinstallering bare med generelle parametere for kilde, versjon og nettleserspråk. Ikke inkluder personopplysninger med mindre du bevisst vil dele dem.",
 "reasonLabel": "Hvorfor avinstallerte du?",
 "chooseOne": "Velg én",
 "reasonNotEnough": "Den blokkerte ikke bevegelsen eller mediet jeg forventet",
 "reasonBlockedIncorrectly": "Den blokkerte eller endret noe feil",
 "reasonSiteCompatibility": "Det fungerte ikke på en nettside jeg trengte",
 "reasonConfiguration": "Den var forvirrende å konfigurere",
 "reasonBugSlowdown": "Den forårsaket en feil, treghet eller kompatibilitetsproblem",
 "reasonNoLongerNeeded": "Jeg trenger den ikke lenger",
 "reasonPrivacyPermissions": "Bekymring for personvern eller tillatelser",
 "reasonOther": "Annet",
 "detailsLabel": "Hva skjedde, eller hva forventet du i stedet?",
 "detailsHelp": "Valgfritt. En eller to setninger er nok.",
 "featureLabel": "Hvilken funksjon ville fått deg til å prøve den igjen?",
 "featureHelp": "Valgfritt.",
 "contactLabel": "Svaradresse",
 "contactHelp": "Valgfritt. Legg den bare inn hvis du vil ha svar.",
 "submit": "Send tilbakemelding",
 "status": "Tilbakemeldingen behandles av Formspree.",
 "footerSource": "Kilde"
 },
 "he": {
 "pageTitle": "MotionBlock משוב",
 "metaDescription": "משוב אופציונלי להסרת MotionBlock.",
 "brandHomeLabel": "דף הבית של Oleksandr Molodchyk",
 "navLabel": "ניווט ראשי",
 "navProjects": "פרויקטים",
 "navNow": "עכשיו",
 "navAbout": "אודות",
 "navContact": "יצירת קשר",
 "headline": "עזרו לשפר את התוסף",
 "intro": "אם MotionBlock פספסת, תו קצר אחד מספיק. טופס זה הוא אופציונלי ואינו דורש פרטי קשר.",
 "privacyNote": "התוסף פותח את הדף הזה לאחר ההסרה רק עם פרמטרים כלליים של מקור, גרסה ושפת הדפדפן. אל תכללו מידע אישי אלא אם אתם רוצים לשתף אותו במכוון.",
 "reasonLabel": "למה הסרתם?",
 "chooseOne": "בחרו אפשרות אחת",
 "reasonNotEnough": "זה לא חסם את התנועה או המדיה שציפיתי להם.",
 "reasonBlockedIncorrectly": "הוא חסם או שינה משהו בטעות",
 "reasonSiteCompatibility": "זה לא עבד באתר שהייתי צריך",
 "reasonConfiguration": "ההגדרה שלו הייתה מבלבלת",
 "reasonBugSlowdown": "הוא גרם לתקלה, האטה או בעיית תאימות",
 "reasonNoLongerNeeded": "אני כבר לא צריך אותו",
 "reasonPrivacyPermissions": "חשש מפרטיות או מהרשאות",
 "reasonOther": "אחר",
 "detailsLabel": "מה קרה או מה ציפיתם במקום זאת?",
 "detailsHelp": "אופציונלי. משפט או שניים מספיקים.",
 "featureLabel": "איזו תכונה תגרום לכם לנסות אותו שוב?",
 "featureHelp": "אופציונלי.",
 "contactLabel": "כתובת לתשובה",
 "contactHelp": "אופציונלי. הוסיפו רק אם אתם רוצים תשובה.",
 "submit": "שליחת משוב",
 "status": "המשוב מעובד באמצעות Formspree.",
 "footerSource": "מקור"
 },
 "ja": {
 "pageTitle": "MotionBlock フィードバック",
 "metaDescription": "オプションでアンインストールフィードバック MotionBlock。",
 "brandHomeLabel": "Oleksandr Molodchyk ホーム",
 "navLabel": "メインナビゲーション",
 "navProjects": "プロジェクト",
 "navNow": "現在",
 "navAbout": "概要",
 "navContact": "連絡先",
 "headline": "拡張機能の改善にご協力ください",
 "intro": "もし的外れ MotionBlock、短い音一つで十分です。このフォームは任意で、連絡先情報は必要ありません。",
 "privacyNote": "拡張機能はアンインストール後、このページを source、version、ブラウザ言語の一般的なパラメータだけで開きます。意図して共有する場合を除き、個人情報は入力しないでください。",
 "reasonLabel": "アンインストールした理由は何ですか？",
 "chooseOne": "1つ選択",
 "reasonNotEnough": "期待していた動きやメディアの動きは阻まれませんでした",
 "reasonBlockedIncorrectly": "何かを誤ってブロックまたは変更した",
 "reasonSiteCompatibility": "必要なウェブサイトでは動作しませんでした",
 "reasonConfiguration": "設定が分かりにくかった",
 "reasonBugSlowdown": "バグ、遅延、互換性の問題が発生した",
 "reasonNoLongerNeeded": "もう必要ない",
 "reasonPrivacyPermissions": "プライバシーまたは権限が気になった",
 "reasonOther": "その他",
 "detailsLabel": "何が起きましたか、または何を期待していましたか？",
 "detailsHelp": "任意です。1、2文で十分です。",
 "featureLabel": "どの機能があればもう一度試したいですか？",
 "featureHelp": "任意です。",
 "contactLabel": "返信先",
 "contactHelp": "任意です。返信を希望する場合のみ入力してください。",
 "submit": "フィードバックを送信",
 "status": "フィードバックは Formspree によって処理されます。",
 "footerSource": "ソース"
 },
 "hr": {
 "pageTitle": "MotionBlock Povratne informacije",
 "metaDescription": "Opcionalna povratna informacija o deinstalaciji za MotionBlock.",
 "brandHomeLabel": "Početna stranica Oleksandra Molodchyka",
 "navLabel": "Glavna navigacija",
 "navProjects": "Projekti",
 "navNow": "Sada",
 "navAbout": "O meni",
 "navContact": "Kontakt",
 "headline": "Pomozite poboljšati proširenje",
 "intro": "Ako MotionBlock promašili, dovoljna je jedna kratka nota. Ovaj obrazac je opcionalan i ne zahtijeva kontakt podatke.",
 "privacyNote": "Proširenje otvara ovu stranicu nakon deinstalacije samo s općim parametrima izvora, verzije i jezika preglednika. Nemojte unositi osobne podatke osim ako ih namjerno želite podijeliti.",
 "reasonLabel": "Zašto ste deinstalirali?",
 "chooseOne": "Odaberite jednu opciju",
 "reasonNotEnough": "Nije blokirao pokret ili medije koje sam očekivao",
 "reasonBlockedIncorrectly": "Nešto je pogrešno blokiralo ili promijenilo",
 "reasonSiteCompatibility": "Nije radilo na web stranici koja mi je trebala",
 "reasonConfiguration": "Konfiguracija je bila zbunjujuća",
 "reasonBugSlowdown": "Uzrokovalo je grešku, usporenje ili problem kompatibilnosti",
 "reasonNoLongerNeeded": "Više mi ne treba",
 "reasonPrivacyPermissions": "Briga oko privatnosti ili dopuštenja",
 "reasonOther": "Ostalo",
 "detailsLabel": "Što se dogodilo ili što ste očekivali umjesto toga?",
 "detailsHelp": "Neobavezno. Dovoljna je jedna ili dvije rečenice.",
 "featureLabel": "Koja bi vas značajka navela da pokušate ponovno?",
 "featureHelp": "Neobavezno.",
 "contactLabel": "Adresa za odgovor",
 "contactHelp": "Neobavezno. Uključite samo ako želite odgovor.",
 "submit": "Pošalji povratne informacije",
 "status": "Povratne informacije obrađuje Formspree.",
 "footerSource": "Izvor"
 },
 "mr": {
 "pageTitle": "MotionBlock अभिप्राय",
 "metaDescription": "MotionBlock साठी पर्यायी अनइन्स्टॉल फीडबॅक.",
 "brandHomeLabel": "Oleksandr Molodchyk मुख्यपृष्ठ",
 "navLabel": "मुख्य नेव्हिगेशन",
 "navProjects": "प्रकल्प",
 "navNow": "आता",
 "navAbout": "बद्दल",
 "navContact": "संपर्क",
 "headline": "एक्स्टेंशन सुधारण्यास मदत करा",
 "intro": "जर MotionBlock मार्क चुकला तर एक छोटी टीप पुरेशी आहे. हा फॉर्म पर्यायी आहे आणि संपर्क माहितीची आवश्यकता नाही.",
 "privacyNote": "एक्स्टेंशन अनइन्स्टॉल झाल्यानंतर हे पृष्ठ फक्त सामान्य source, version आणि browser-language पॅरामीटर्ससह उघडते. तुम्हाला जाणीवपूर्वक शेअर करायचे नसल्यास वैयक्तिक माहिती देऊ नका.",
 "reasonLabel": "तुम्ही ते का अनइन्स्टॉल केले?",
 "chooseOne": "एक निवडा",
 "reasonNotEnough": "त्याने मला अपेक्षित असलेल्या हालचाली किंवा माध्यमांना रोखले नाही",
 "reasonBlockedIncorrectly": "काहीतरी चुकीचे ब्लॉक केले किंवा बदलले",
 "reasonSiteCompatibility": "मला आवश्यक असलेल्या वेबसाइटवर हे कार्य करत नाही",
 "reasonConfiguration": "कॉन्फिगर करणे गोंधळात टाकणारे होते",
 "reasonBugSlowdown": "बग, मंदी किंवा सुसंगतता समस्या निर्माण झाली",
 "reasonNoLongerNeeded": "आता मला त्याची गरज नाही",
 "reasonPrivacyPermissions": "गोपनीयता किंवा परवानग्यांबद्दल चिंता",
 "reasonOther": "इतर",
 "detailsLabel": "काय झाले किंवा त्याऐवजी तुम्हाला काय अपेक्षित होते?",
 "detailsHelp": "ऐच्छिक. एक-दोन वाक्ये पुरेशी आहेत.",
 "featureLabel": "कोणते वैशिष्ट्य तुम्हाला पुन्हा प्रयत्न करायला लावेल?",
 "featureHelp": "ऐच्छिक.",
 "contactLabel": "उत्तराचा पत्ता",
 "contactHelp": "ऐच्छिक. उत्तर हवे असल्यासच जोडा.",
 "submit": "अभिप्राय पाठवा",
 "status": "अभिप्राय Formspree द्वारे प्रक्रिया केला जातो.",
 "footerSource": "स्रोत"
 }
};
